### PR TITLE
 Vector tile drawing for .mvt and .pbf format

### PR DESCRIPTION
**Pull request by vershwal**
Related #3742.

### CODE REVIEW

**Comment by mmd-osm** [comment]
I don't know if this is a good place to report some issues. Testing a few mvt + geojson example file in https://github.com/mapbox/mapnik-vector-tile/tree/master/examples/data produced some mixed results:

14_8716_8015.vector.mvt: takes several minutes to load, feels quite slow, browser becomes somewhat unresponsive.
14_2620_6331-barrier_line.geojson: returns the error message on javascript console, otherwise no feedback to user.

```
VM26:1 Uncaught SyntaxError: Unexpected token o in JSON at position 1
    at JSON.parse (<anonymous>)
    at parseSaveAndZoom (mvt.js:180)
    at FileReader.<anonymous> (mvt.js:236)
```
This makes me wonder a bit, if those files would be ok for testing.

**Comment by mmd-osm** [comment]
> Do you think this layer should also draw geojson along with mvt?

Not sure about this one, maybe you should discuss this with your mentors. In any case, if a user uploads some unknown format or broken file, some kind of error message would be incredibly helpful to find out what's going on.

> if the code works with some small tiles then we can start working on the performance part next

Ok, sounds fine to me.

**Comment by vershwal** [comment]
> if a user uploads some unknown format or broken file, some kind of error message would be incredibly helpful to find out what's going on.

Ya, this sounds good! Will do that. Thanks.

**Comment by bhousel** [comment]
Thanks @vershwal this is a great start!

Quick update on this - I changed a few things below and merged the code:
- I replaced `d3_fetch` (a newer API which isn't supported on IE11)  with `d3_request` (traditional XHR)
- There are still some todos in the code
- I commented out the item from the map data panel.

Next action for me:
- We really should just combine the "gpx" and "mvt" layers into a single module which handles all overlay data.  They each currently register a drag-and-drop handler and these handlers are conflicting with each other.  Also they have misleading names.  And it's just redundant and confusing to have two things.  So I'm going to combine them 😅 

Next action for @vershwal : 
So the code was merged but is commented out and not ready yet. I didn't want your PR to diverge too much from `master`.  The `vershwal:check` branch was not really current when you started the work, so that's why the merge above did some weird things to the PR.  Going forward I'd like to work more disciplined like this:
- set main iD repo as your origin remote (you are a collaborator so this is ok)
`git remote set-url origin git@github.com:openstreetmap/iD.git`
- pull from `master` frequently, but avoid developing on that branch or pushing to it
`git checkout master && git pull origin master`
- create feature branches off of `master` before working on something
`git checkout -b new_thing`
- try to check in a little bit of work every day, and push to your feature branch.
`git push origin new_thing`

We can chat on Slack more if you have questions!

**Pull request merged**
