### PR TITLE
add preset to address interpolation

### PR DESCRIPTION
**Pull request by willemarcel**
https://wiki.openstreetmap.org/wiki/Addresses#Using_interpolation

### CODE REVIEW

**Comment by bhousel** [comment]
I'm still considering whether we want to support this.. Anyone have thoughts?

Reading here: https://wiki.openstreetmap.org/wiki/Addresses#Using_interpolation
it seems like it is easy for users to make mistakes.  We don't have a way yet of prompting them that they are supposed to put house numbers along the line, and the wiki reference does not link directly to that page of documentation.

This PR doesn't include any of the extras mentioned in #1316, and I feel like the trend in OSM has shifted since then to just mapping all the address points.

**Comment by willemarcel** [comment]
@bhousel I changed the https://wiki.openstreetmap.org/w/index.php?title=Key:addr:interpolation link to redirect to the interpolation section of the `Key:addr` page.

My opinion is that, as this preset will not be listed in one of the main categories, probably the only way to someone find it is to search for 'interpolation'. So I believe who will use it knows what is doing.

In most Argentina cities the blocks are squares with 100m long in each face, so they use interpolation a lot. Currently if a user clicks in a interpolation line he won't have information about what it is. It just shows the label `Line`, so I think it'll be more educative to have this preset.

If you approve it, I suggest to change the label from `Interpolation` to `Address Interpolation`.

**Comment by pnorman** [comment]
We should have *something* for interpolation so existing objects display correctly.

**Comment by willemarcel** [comment]
@bhousel Have you made a decision on this? If you think users should not be encouraged to create interpolations, I could add `"searchable": false` to the preset.

**Comment by bhousel** [comment]
Sorry for the delay @willemarcel & @pnorman - I agree we should add this.

I have a suspicion that what I did for #4353 and #3241 might conflict with an address interpolation preset.  I just need to set aside a few hours to check it out and really think through the issues.

**Comment by ignaciolep** [comment]
Hi! In Argentina (and [many other places around the world](https://taginfo.openstreetmap.org/keys/addr:interpolation#map)) we have most of the addresses mapped with addr:interpolation. Unfortunately, iD shows them as a generic line.

As iD now has the autofix feature, it would be great to have a preset for addr:interpolation what would autoadd/autofix the addr:housenumber and addr:street tags in the nodes of the addr:interpolation lines.

**Comment by quincylvania** [comment]
I added a version of this PR with an unsearchable "Address Interpolation" preset and an associated field. I'm leaving the initial issue open since that also covers rendering.

> As iD now has the autofix feature, it would be great to have a preset for addr:interpolation what would autoadd/autofix the addr:housenumber and addr:street tags in the nodes of the addr:interpolation lines.

@ignaciolep Interesting idea! It seems really difficult though.

**Pull request closed without merging**
