### PR TITLE
Pluralize localizable strings

### LINKED ISSUE #597: Better i18n plural support
Multiselect produces translations like "Deleted {n} objects", which we're currently translating without real plural form support.

### PR DESCRIPTION
**Pull request by 1ec5**
UI strings that include counts now use the appropriate plural form in English and (once translations are updated) in other languages. When looking up a translation and one of the tokens is numeric, look one level deeper in the translation file for the CLDR plural form corresponding to the numeric token.

singular plural

In order to support this feature for all the languages that iD supports, with all their varying pluralization rules, this change introduces dependencies on:

* [cldr-core](https://github.com/unicode-cldr/cldr-core/), which supplies plural rules for a _number_ of languages (part of [cldr-data](https://github.com/rxaviers/cldr-data-npm/))
* [CLDRPluralRuleParser](https://github.com/santhoshtr/CLDRPluralRuleParser/), which parses a plural rule, determining whether it matches the given number (used by MediaWiki)

This works locally using `npm start`, but I’d like someone to double-check that I’m including these dependencies correctly. (All we need is a single JSON file from cldr-core, not the entire package.)

Keying off numbers in token replacements means any number formatting that occurs before calling `t()` will defeat the pluralization logic therein. Unlike the unit formatting that occurs in `t()`’s callers (as of #4672), number formatting needs to happen inside `t()`.

More to come:

* [x] Depend on cldr-core and CLDRPluralRuleParser
* [x] Look up pluralized translations in `t()`
* [x] Pluralize some strings in core.yaml
* [ ] Move number formatting into `t()`
* [ ] Combine manually pluralized strings like `restriction.controls.via_up_to_one`/`restriction.controls.via_up_to_two`
* [ ] Break up `validations.many_deletions` into strings with one pluralized word each
* [x] Mention plural format in contributing documentation
* [ ] Update changelog

Fixes #597.

### CODE REVIEW

**Comment by bhousel** [comment]
> This works locally using npm start, but I’d like someone to double-check that I’m including these dependencies correctly. (All we need is a single JSON file from cldr-core, not the entire package.)

Looks great!  Rollup will include only the single JSON file 👍 

> Keying off numbers in token replacements means any number formatting that occurs before calling t() will defeat the pluralization logic therein. Unlike the unit formatting that occurs in t()’s callers (as of #4672), number formatting needs to happen inside t().

Ok, that makes sense.  I don't know how often in the code we pass stringified numbers to `t()` but it is probably not too much work to change these.

**Comment by magol** [comment]
Any work on this PR?

**Comment by 1ec5** [comment]
Sorry, I don’t know when I’ll get a chance to get back to this PR, but it’s certainly something I’d like to get in eventually. (At some point, browser support for `Intl.PluralRules` would improve enough that we could radically simplify this PR.)

**Comment by quincylvania** [comment]
To be clear, this was closed automatically when I renamed the `master` branch, but it was two years old.

I'd like to spend some time soon to get pluralization right as we work on expanding iD's global usability (see #7713).

**Pull request closed without merging**
