### PR TITLE
 Add ability to resize to PhotoViewer #4930

### PR DESCRIPTION
**Pull request by kratico**
Related to https://github.com/openstreetmap/iD/issues/4930

@bhousel Could you check how to resize Bing StreetSide?

### CODE REVIEW

**Comment by bhousel** [comment]
This looks awesome, I'll check it out today..

**Comment by cbeddow** [comment]
Following this to see when it's merged

**Comment by bhousel** [comment]
Thanks for this @kratico & @cbeddow - I made a few slight changes and just merged it:
- added resize for OpenStreetCam and Bing Streetside
- prevent resize up from exceeding the size of the map window
- when map resizes down, shrink photo viewer if needed
- slightly increased the size of the resize handle buttons

It's really awesome!  👏 

mapillary resize

**Comment by tordans** [comment]
@bhousel the resize does not seem to work for me at https://www.openstreetmap.org/edit#map=20/52.47332/13.44890

Screenshot:
bildschirmfoto 2018-08-06 um 11 25 42

Operating System Mac OSX 10
Web Browser Chrome 69.0.3494

Am I doing it wrong?

**Comment by bhousel** [comment]
> Am I doing it wrong?

It looks right to me-  if you open the developer console, do you see any warnings?

It does look like you are using the webgl viewer (there is a fallback option if webgl were not working, but I think it would render differently in this case).

**Comment by bhousel** [comment]
> I re-tested it with some browsers, now it is working with all. I don't know why it did't before. Thanks for the help and the feature!

good to hear, thanks!

**Pull request merged**
