### PR TITLE
Add access_simple field to basketball, tennis & garden presets (#3336)

### PR DESCRIPTION
**Pull request by Psigio**
Hi,

I've added access_simple tags to basketball, tennis courts & garden as requested in #3336 - please can you review my changes?

Thanks,

Jon

### CODE REVIEW

**Comment by Psigio** [comment]
Just had a thought - not sure if you would prefer it if I checked-in the autogenerated files created by the `make` command?  Please reply on this thread if you do and I can add them to the pull request.

**Comment by bhousel** [comment]
Yes, it's important to check in those generated files.  One of them is picked up by the Transifex site every night - this lets us translate the presets and fields.

I prefer if when people edit presets, they also run `make` before submitting the pull request.  But I'm not super strict about it and don't mind running it for people who are new or are editing on the GitHub website code editor.

**Comment by Psigio** [comment]
Ok, done - checked in on the pull request and the Travis build has completed!  Only the presets.json file had changed (which I'm guessing makes sense, since the yaml and locale file only seem to contain the detail of the names of the presets)

**Comment by bhousel** [comment]
Thanks!

**Pull request merged**
