### PR TITLE
Excrement Bag Dispenser: improve name and remove unnecessary fields

### PR DESCRIPTION
**Pull request by SelfishSeahorse**

### CODE REVIEW

**Comment by quincylvania** [comment]
@SelfishSeahorse Looks good! Can you run `npm run build` and commit the derived changes too?

**Comment by SelfishSeahorse** [comment]
@quincylvania: I currently don't have access to my own computer but i can do it a week or so.

**Comment by quincylvania** [comment]
@SelfishSeahorse No problem, I took care of it for you. Thanks again!

**Comment by SelfishSeahorse** [comment]
@quincylvania: Thank you!

**Pull request merged**
