### PR TITLE
Support rendering `direction` on vertices (stop sign, traffic_signals, etc)

### LINKED ISSUE #3815: Adjust rendering of node/vertex with direction
Followup from #3115..

Some node/vertex features in OSM can have a direction.  stop signs, traffic signals, billboards.
The normal method to tag this is `direction=forward` or `direction=backward` (although, this being OSM, there are of course [alternative bizarro tag schemes](https://wiki.openstreetmap.org/wiki/Key:direction)).

Anyway, what we do with directional vertices currently is - the same as any other interestingly tagged vertex, just show it as a circle with a dot (or in some cases a maki icon):

screenshot 2017-02-03 10 35 28

But maybe we can do something else to indicate that there is a direction:

screenshot 2017-02-03 10 35 28 copy  screenshot 2017-02-03 10 53 21

### PR DESCRIPTION
**Pull request by bhousel**
- [x] #3003
- [x] #3815 
- [x] #4271 
- [x] #4455 
- [x] #4013 
- [x] #3610
- [x] update walkthrough
- [x] update presets
- [x] fix turn restrictions editor
(updated: scope creep)

Something I threw together today - I still might adjust the marker style a bit, and I'm not 100% sure if it handles all of the tag cases correctly.

#### `highway=stop` with `direction=forward` / `direction=backward`
screenshot 2017-12-07 16 42 35

#### This is what it does for `stop=all` or `direction=both`
screenshot 2017-12-07 16 43 04

### CODE REVIEW

**Comment by iandees** [comment]
An arrow is kinda confusing to me. Is that the direction of travel or the direction the sign would be facing?

**Comment by bhousel** [comment]
> An arrow is kinda confusing to me. Is that the direction of travel or the direction the sign would be facing?

Yeah, this is a hard problem.  Currently, the arrowhead faces whatever the direction tag says: "Forward" or "Backward" - so that's "direction of travel".  

Even those words are not great - I don't think an untrained mapper would really be able to understand this concept, or even why stop signs (and even moreso traffic signals) would need a direction.  The help text is not very helpful either.

screenshot 2017-12-07 19 02 22

I'd definitely welcome some ideas on how to make this easier.

**Comment by bhousel** [comment]
Some other design thoughts.. whatever we do needs to:
- have good contrast on top of everything
- be distinct from both the oneway markers and the streetlevel photo view cones
- look good very close to or under the vertex (even when the vertex has a selection halo)

**Comment by bhousel** [comment]
@iandees I do kind of like the viewfield a little better, what do you think?

screenshot 2017-12-08 11 58 32screenshot 2017-12-08 11 58 21

**Comment by iandees** [comment]
Yea, that makes more sense I think. I was also going to suggest something like that but with a flat line perpendicular to the incoming way representing the top of the sign/signal.

**Comment by bhousel** [comment]
So this functionality is turning out to be pretty cool.  I have directions rendered for a bunch of things now (street signs, cameras, etc).

The main issue remaining is that a point with directions disappears when dragged.

nodrag-directional

I know why - it's because vertices aren't displayed during a drag, which is also #3003.

**Comment by bhousel** [comment]
This PR is pretty wild... Here's the overview:

- I wanted to show directions on vertices and put some view cones around them to do that (#3815). This is useful for mapping street signs and traffic signals.
- Then I wanted to put the view cones on standalone nodes too, to support surveillance cameras and stuff that is not on a way.
- To make that look good, the nodes needed to render like vertices (circles), not markers.  We already do this in wireframe mode, so I thought "no big deal".
- This worked ok, but then you couldn't drag the nodes around because we don't render vertices while dragging (#3003).
- So I made the vertices visible during dragging.  (also rotating, moving, etc)
- Now with vertices being rendered, having text drawn on top of them while the user dragged them around was a big issue, so I had to fix the label placement. (#4271).
- Rendering the vertices while dragging and drawing broke a bunch of other things.  I needed to get much more strict about which things can be targets and where the pointer events can go (only to certain vertices and segments along a way).
- So I added invisible touch targets to control which things can listen to pointer events, and a debugging mode to make them visible and see what's going on.  
- These touch targets are circles around the vertices and MultiLineString geojson segments along the ways, and the targets allowed me to again say where it is ok for a line to loop back on itself (#4455)
- If we can draw touch targets, we might as well also draw "nope" targets (which are parts along the line or vertices that the user specifically can't interact with.  
- This let me prevent the user from drawing self-intersecting polygons or lines that return back on themselves (#4013).
- Then I realized we didn't need a lot of complicated drawing code anymore, which used temporary nodes and segments to get around the problems of targeting the way that the user was drawing. (2be62ff is pretty wild)
- Then I realized that if we can draw targets for connecting and for not connecting, we can have the not-connecting targets do useful things like change the cursor and put the line back where it was.
- I made it transitionable, because it looks cool:  

nope2

Anyway that's what is new.  It will merge soon!
Some things that we can do later:
- Use the nope targets to prevent users from joining things that should not join (e.g. power lines with roads) or from dragging things where they should not go (e.g. a junction that zig-zags across several roads)
- Not having the temporary drawing objects anymore simplifies the draw code a lot!  This will make it easier to do square building drawing mode.  (yes one of my next priorities for early 2018)

**Comment by iandees** [comment]
Great work, @bhousel! I've been following along on your commits and this has gotten wild. What a great way to end the year. Happy Holidays! 🍰 🎉

**Comment by 1ec5** [comment]
🎉

if you give a mouse a cookie

**Comment by bhousel** [comment]
Happy New Year!   Time to merge this thing already!  🎉🎆🎊🍾 

It will show up in http://preview.ideditor.com/master shortly, and I encourage anyone who is interested to try it out there...

**Comment by fidelis-assis** [comment]
Hi,

I like the new viewfield for direction but aren't forward and backward reversed?

**Comment by bhousel** [comment]
> I like the new viewfield for direction but aren't forward and backward reversed?

I don't think they are reversed.  For example, a stop sign that affects forward travel will be pointed backwards so the cars can see it:

screenshot 2018-02-20 09 48 35

But if you found a situation that we are rendering incorrectly, please open an issue and me know!

**Comment by fidelis-assis** [comment]
2018-02-20 11:49 GMT-03:00 Bryan Housel <notifications@github.com>:

> I like the new viewfield for direction but aren't forward and backward
> reversed?
>
> I don't think they are reversed. For example, a stop sign that affects
> forward travel will be pointed backwards so the cars can see it:
>
Thanks for your quick answer. Your explanation is clear but the value used
for direction and the viewfield shown confuse me. If the stop sign points
backwards relatively to the way direction and I'm mapping its direction
(where it faces to), why tag it with 'forward' as in this example and not
'backward'?

In your example, the viewfield looks backwards (I think), what is OK, after
all the stop sign faces backwards, but the value for direction is
'forward'. What am I missing?

-- Fidelis Assis

**Comment by bhousel** [comment]
> If the stop sign points
> backwards relatively to the way direction and I'm mapping its direction
> (where it faces to), why tag it with 'forward' as in this example and not
> 'backward'?

Oh yeah, I left out an important detail in that screenshot above.  The `direction=forward/backward` tag works relative to the direction _that the way is drawn_, not the direction of the sign.  A funny thing about these tags - if you reverse the way, iD also needs to (and does) reverse the `direction=*` tag.

See:  
- https://wiki.openstreetmap.org/wiki/Key:direction#Forward_and_backward
- https://wiki.openstreetmap.org/wiki/Tag:highway=stop#Tagging_minor_road_stops

The main reason that I started rendering these viewfields is because it's nearly impossible (especially for casual mappers) to understand how the direction apply to a way.

**Comment by fidelis-assis** [comment]
2018-02-20 14:32 GMT-03:00 Bryan Housel <notifications@github.com>:

> If the stop sign points
> backwards relatively to the way direction and I'm mapping its direction
> (where it faces to), why tag it with 'forward' as in this example and not
> 'backward'?
>
> Oh yeah, I left out an important detail in that screenshot above. The
> direction=forward/backward tag works relative to the direction *that the
> way is drawn*, not the direction of the sign.
>
OK, I understand that. Just to make myself clearer, let's consider a oneway
road with a stop sign (or a traffic calming - that was my initial
motivation, I was confused when checking a few tagged with forward). On a
oneway road, all stop signs and traffic calmings face backwards because the
drawing direction is the same as the traffic flow (perhaps a few old
exceptions). So, I was thinking they, if tagged with direction (unnecessary
for one-way roads anyway, also for two-way roads when affect both
directions), the value should be *backward*. But the viewfield in this case
shows the opposite direction.

In the example below, both traffic calmings were tagged with forward,
probably because the mapper wanted to align the viewfield correctly. Again,
in this case the direction isn't necessary.

Ex:
https://www.openstreetmap.org/edit?node=349338170#map=19/-23.02126/-43.44967

I extract speedcams for GPS from OSM. If 'forward' is the right value in
these cases I'll have to change how I calculate direction when it matters
(ex: traffic calming or speed sensor acting on a single direction on a
two-way road).

A funny thing about these tags - if you reverse the way, iD also needs to
> (and does) reverse the direction=* tag.
>
Nice. Does it also reverse if the value is in degrees?


> See:
>
>    - https://wiki.openstreetmap.org/wiki/Key:direction#
>    Forward_and_backward
>    - https://wiki.openstreetmap.org/wiki/Tag:highway=stop#
>    Tagging_minor_road_stops
>
> The main reason that I started rendering these viewfields is because it's
> nearly impossible (especially for casual mappers) to understand how the
> direction apply to a way.
>
Yes, I think it's a very helpful facility. Thanks for adding it!

-- Fidelis

**Pull request merged**
