### PR TITLE
OSM API /map call: support Overpass JSON format 

### PR DESCRIPTION
**Pull request by mmd-osm**
---

This pull request is about parsing performance, for context see https://github.com/openstreetmap/iD/issues/1727#issuecomment-26099201

---
The code in here adds parsing logic for an OSM/[Overpass based JSON](http://overpass-api.de/output_formats.html) format, which I implemented as part of https://github.com/zerebubuth/openstreetmap-cgimap/pull/153.

As the deployment of the JSON format to production is currently delayed due to missing support on the Rails port, the code in here is "silent" and inactive. To enable the new JSON parser, a few more changes would be needed:

*  loadFromAPI: 
    - call to `return parseXML(payload, callback, options);` needs to be replaced by  `return parseJSON(payload, callback, options); `
    - `d3_xml(url, { signal: controller.signal })` needs to be replaced by `d3_json(url, { signal: controller.signal })` 

* loadTile 
    - API endpoint expects ".json" suffix to trigger JSON output, hence `var path = '/api/0.6/map?bbox=';` needs to be replaced by `var path = '/api/0.6/map.json?bbox=';` 

(replacing would depend on some flag to allow switching between XML and JSON formats)

JSON output can be tested on the dev instance _master.apis.dev.openstreetmap.org_. Halifax in Nova Scotia has plenty of test data.

Unit tests are currently missing. I’m not sure if we can simply copy the existing XML ones and have them parse json instead. Or maybe something else?

---

Upstream dependencies:
* https://github.com/openstreetmap/openstreetmap-website/pull/2485 (for moving JSON support to production)

### CODE REVIEW

**Comment by bhousel** [comment]
Nice!  It would be great to use this someday!

> Unit tests are currently missing. I’m not sure if we can simply copy the existing XML ones and have them parse json instead. Or maybe something else?

Yes, I'd modify `loadFromAPI` somehow.. It currently just calls `parseXML`, but if it could inspect they payload, then you could test it against both XML and JSON payloads to make sure it works with both.

I'm just going to merge as-is, since it's dead code anyway..

**Comment by mmd-osm** [comment]
In my loadFromAPI method, I'm deriving a `use_json` flag based on the path being passed on as paramter: `var use_json = path.includes(".json");`  and do all switching based on that flag. `loadTile` is the place to either go for a `map?bbox` or `map.json?bbox` URL. 

I'm not quite sure what's next here, i.e. if we should add some optional URL parameter to enable/disable JSON (like we do say for backgrounds), or have some try/fallback mechanism.

**Comment by bhousel** [comment]
> Currently, I don't see the need to JSON enable any of the other endpoints. Let's focus on /map first. I'm not quite sure what's next here, i.e. if we should add some optional URL parameter to enable/disable JSON (like we do say for boundaries), or have some try/fallback mechanism.

Can we test this yet, maybe against dev server?

**Comment by mmd-osm** [comment]
Yes, you can already test the cgimap version against https://master.apis.dev.openstreetmap.org

**Comment by mmd-osm** [comment]
I've noticed @quincylvania changed some of the object lookups to also use json. Currently there's a hardcoded `visible` value in jsonparsers.{node,way,relation}:

```
visible: true,
```

Now looking at https://api.openstreetmap.org/api/0.6/node/3006673214/4.json, you'll notice that in case the object has been deleted, there will be an additional "visible" attribute.

My suggestion would be to use the `obj.visible` flag if is it part of the API payload, otherwise assume "true" as default:


```
visible: obj.visible ?? true,
```

(or something similar accomplishing the same task)

**Comment by quincylvania** [comment]
> I've noticed @quincylvania changed some of the object lookups to also use json

@mmd-osm Yep! I tried to use as many of the JSON endpoints as possible

> My suggestion would be to use the obj.visible flag if is it part of the API payload, otherwise assume "true" as default

Sounds good, thanks for flagging this 👍

**Pull request merged**
