### PR TITLE
Enhancements to Background, Map Data, Help panes

### PR DESCRIPTION
**Pull request by bhousel**
I've been working on these for a few days, so I'm going to just roll a few semi-related things into one PR.

- [x] #4601
- [x] #4553 
- [x] #4570 
- [x] #4546 
- [x] #4635
- [x] #2211  😏

### CODE REVIEW

**Comment by bhousel** [comment]
The .gif doesn't do this justice, but here's what I've been working on the past few days.  These sliders make it possible to improve any imagery. I'm pretty excited about it 😄  

This feature uses CSS filters to close #2211, something that's been in the back of my mind for a while.  It will work well in Chrome and Firefox and some partial to full support in Safari, Edge, and not sure about IE11.

imagery adjustment

This spun off from an effort to slightly improve the usability of the side panes.  The sliders replace the old "brightness buttons", which were a bit confusing to people (they did not look like buttons) and could only do steps from 25%, 50%, 70%, 100%.

**Comment by boothym** [comment]
Talking of the background pane - is it possible to do something like in this image https://github.com/openstreetmap/iD/issues/3453#issuecomment-258199010 and hide all background > 20 years old in a "historic imagery" dropdown? Because the background list is now quite long for mappers in the UK.

**Comment by bhousel** [comment]
> Talking of the background pane - is it possible to do something like in this image #3453 (comment) and hide all background > 20 years old in a "historic imagery" dropdown? Because the background list is now quite long for mappers in the UK.

This is a really good idea.. I don't want to extend the scope of the PR right now but I do want to think about letting people customize the background imagery list.. e.g. add more / or remove the ones that they never want to see.   I'll reopen and add some comment to #3453

**Comment by bhousel** [comment]
This was merged!  As always, please test out the new Background pane on http://preview.ideditor.com/master/ - thanks 🙇

**Pull request merged**
