### PR TITLE
Switch Wikipedia list to osmlab/wmf-sitematrix

### LINKED ISSUE #2682: Wikipedia list is outdated
[wikipedia.json](https://github.com/openstreetmap/iD/blob/master/data/wikipedia.json) lists 285 Wikipedias, but [Wikimedia’s site matrix](https://meta.wikimedia.org/wiki/Special:SiteMatrix?uselang=en) lists 288 and new Wikipedias are added somewhat regularly as they graduate from Wikimedia Incubator. iD’s build process should call the [MediaWiki API](https://en.wikipedia.org/wiki/Special:ApiSandbox#action=sitematrix&format=json) to regenerate the list more easily.

/cc @aaronlidman

### PR DESCRIPTION
**Pull request by 1ec5**
This PR switches the list of Wikipedias to the one maintained in [osmlab/wmf-sitematrix](https://github.com/osmlab/wmf-sitematrix). That list comes from the MediaWiki API, so it’ll be easy to update. Some things to note, however:

 - The MediaWiki API sorts the wikis by ISO 639 language code rather than article count.
 - Closed wikis are filtered out. Do we need them in iD?

Fixes #2682.

/cc @aaronlidman

### CODE REVIEW

**Comment by bhousel** [comment]
> The MediaWiki API sorts the wikis by ISO 639 language code rather than article count.

[This line](https://github.com/openstreetmap/iD/blob/master/js/id/ui/preset/wikipedia.js#L77) seems to expect English first, but could probably just be replaced with an 'en'.

> Closed wikis are filtered out. Do we need them in iD?

I think not.  They're usually closed because they have no meaningful pages.

**Comment by 1ec5** [comment]
> [This line](https://github.com/openstreetmap/iD/blob/master/js/id/ui/preset/wikipedia.js#L77) seems to expect English first, but could probably just be replaced with an 'en'.

@bhousel, good point. I beefed up the logic to fall back to the browser’s locale, or, failing that, English.

**Comment by 1ec5** [comment]
Another consequence of using this list is that some language names (español) start with a lowercase letter, per CLDR. Is that desirable, or should we title-case these names in iD?

**Comment by bhousel** [comment]
@1ec5 I'm really sorry, I thought this was merged already!

**Comment by bhousel** [comment]
> Another consequence of using this list is that some language names (español) start with a lowercase letter, per CLDR. Is that behavior desirable, or should we title-case these names in iD?

Not a big deal, we'll fix it with #2457 when we switch the language list to something better.

**Pull request merged**
