### PR TITLE
Remove an item from the multiselect list

### LINKED ISSUE #2950: Multiselect list: Icon to remove an item from list and selection
Each item of the multiselect list should have an icon which is removing the item from the list, and the associated feature from the selection.

This could be used to refine shift+drag selections.

This would also solve  Handle coincident ways #1239 if all coincident ways were selected on mouse click.

A prerequisite for this issue is #2949

### PR DESCRIPTION
**Pull request by ebrelsford**
Fixes #2950

### CODE REVIEW

**Comment by bhousel** [comment]
Thanks @ebrelsford for contributing this at SOTM-US hack day!   

I made a slight change to the code so that the geometry and close icons would be classed differently.   With the old code `items.selectAll('use')` it was possible to trigger a list redraw, causing things like this:

screenshot 2016-07-26 15 35 56

So I added a class and replaced that selection with `items.selectAll('.entity-geom-icon use')`, so if the redraw does happen, it won't break the close buttons:

screenshot 2016-07-26 16 03 42

**Comment by ebrelsford** [comment]
Makes sense, thanks for the merge @bhousel !

**Comment by slhh** [comment]
Thanks @ebrelsford for contributing this.

Unfortunately, it doesnt work with Firefox. The close icons are positioned too low and don't seem to be active buttons (neither in the shown position, nor in the expected position) . Clicking there just selects the item from the list.
multiselect close icon issue

I have tested with Firefox 47.0 and 47.0.1 on Windows 10.
Clearing the cache has not solved the issue.

With Edge it works fine here.
The usability is somewhat limited, because it might not be possible to find the correct item to be removed in case of multiple items of the same type, for example residential buildings in @bhousel 's screenshot.
This needs #2949 to be solved.

**Comment by ebrelsford** [comment]
@bhousel Fixing the styling is easy enough, but it seems that Firefox is not going to allow children of buttons to listen for clicks (didn't realize!). Okay for me to make these elements `div`s rather than `button`s?

**Comment by bhousel** [comment]
cool, I didn't realize that either - yes make them divs!

**Pull request merged**
