### PR TITLE
Avoid exporting all of d3.js just so we can use it in tests

### PR DESCRIPTION
**Pull request by darthgera123**
Commented out the bit and made the required addition of the script file

### CODE REVIEW

**Comment by bhousel** [comment]
That's the first step - now the challenge is to get the tests to pass!

**Comment by darthgera123** [comment]
just check with the latest commit please

**Comment by bhousel** [comment]
> just check with the latest commit please

Travis still shows that the tests are failing.. If you run them locally in your dev environment, it will probably give you some messages about what the issues are that need to be fixed.

**Comment by bhousel** [comment]
Closing here, as this isn't going anywhere.

**Pull request closed without merging**
