### PR TITLE
Copy paste features

### PR DESCRIPTION
**Pull request by bhousel**
This is for #642 
(these commits were split off from #2489)

Foundation and tests for entity copy/paste is there, need to add:
- [X] behaviors (keybindings)
- [X] handle circular, self-referencing relation graphs

### CODE REVIEW

**Comment by bhousel** [comment]
[These tests](https://github.com/openstreetmap/iD/blob/90147b23dbf314f975c2cae56b97b9f8508984ac/test/spec/core/relation.js#L94-L121) fail and I have no idea why.  

Entering the same commands into a browser dev console works fine.

**Comment by bhousel** [comment]
This is working really well now!  I have it bound to ⌘-C and ⌘-V for now, just as behaviors (not operations). 

I have to say it is pretty awesome being able to do this in iD:
copy_paste

@jfirebaugh, @aaronlidman check it out when you have a chance..

**Comment by aaronlidman** [comment]
@bhousel This works fantastically.

I only noticed one weird behavior. After pasting items, they don't follow the hidden behavior on zoom as other items of the same type.

hihizoom

**Comment by bhousel** [comment]
> I only noticed one weird behavior. Pasted items don't follow the same hidden behavior on zoom as other items of the same type.

Oh, that's a weird behavior with feature filtering.  We don't hide things that the user just created (i.e. anything with a negative id).

**Comment by aaronlidman** [comment]
Ah, makes sense :+1:

**Comment by talllguy** [comment]
Very exciting feature! Would it let me copy the attributes of a point to a polygon?

**Comment by bhousel** [comment]
> Very exciting feature! Would it let me copy the attributes of a point to a polygon?

Actually iD can already do that..  Just select both the point and polygon and click the Merge button.  The point will be removed and its tags will get merged into the polygon.

**Comment by talllguy** [comment]
@bhousel Bryan thanks for the heads up on that!

**Comment by bhousel** [comment]
@talllguy Yeah it's super useful!  There is an open issue #815 to make point-area merging more discoverable.

**Comment by nighto** [comment]
Excellent, that's the only feature I missed from other editors for the everyday mapping. Thanks!

**Pull request merged**
