### PR TITLE
Update connection.js

### PR DESCRIPTION
**Pull request by schwindp**
Removed browser and platform as changeset tags. I don't really see a need for pushing this information into the OSM database

(better force the need for a changelog comment when uploading, but that's another issue)

### CODE REVIEW

**Comment by bhousel** [comment]
@ImreSamu is producing a very useful set of statistics (see #2633) which helps us know how iD is being used.  We do sometimes run into platform or browser bugs that we need to workaround, and it's good to know how many users are affected by these.  To limit the amount of data gathered, we only log the major browser version (not all the way down to patch level) and don't capture the OS version at all.  In fact, these tags that iD saves in the changeset are far less uniquely identifying than the JOSM version tag.

All that said, I do understand that some users are uncomfortable about seeing information about their browser and OS saved in their changeset tags.  

As a compromise how about this:  instead of removing the tags completely, I can honor the user's `doNotTrack` preference (supported by all major browsers now) and if it is set we will save nothing but the iD version tag?

**Comment by bhousel** [comment]
looping in @pnorman because I value his opinion here...

**Comment by schwindp** [comment]
While I understand the reason to have user statistics (or at least statistics how many % of users might be affected by a code change), isn't it at least possible to anonymously sample that data? Writing those tags into changesets is unfortunately fully user-traceable.

**Comment by bhousel** [comment]
> While I understand the reason to have user statistics (or at least statistics how many % of users might be affected by a code change), isn't it at least possible to anonymously sample that data?

iD and its various forks are hosted on several websites other than openstreetmap.org.  Some of those sites use analytics to gather anonymous statistics and some don't.  Either way, we don't have or want access to our partners' analytics data.


> Writing those tags into changesets is unfortunately fully user-traceable.

Again, I'm willing to exclude the tags if a user has `doNotTrack` set.  Is this something that would satisfy your concerns, or are we going to continue talking past each other?

**Comment by pnorman** [comment]
I think we should always be recording iD version, hosting site, and locale. These are useful for mappers for seeing why a user made a particular mistake. If any third party hosting an iD instance doesn't want it disclosed, they can patch out the hosting site as they are by definition hosting their own copy of iD.

I don't see the value for mappers in knowing the OS and browser a user mapped from. I don't think we've had any bugs that would manifest themselves in changesets that have been specific to a browser or OS. The browser-specific bugs tend to be ones where something doesn't work.

Full browser version is already recorded in the server logs by means of user-agent, not just for iD on osm.org, but any iD uploading to osm.org. If we need usage information, I'd rather get them there, even if they might be mixed with an insignificant percentage of P2.

**Comment by schwindp** [comment]
I'm fully satisfied with the proposal by @pnorman - normal users just don't know the "donotTrack" feature.
No one should have the need to opt out in order to not have personal data collected.

**Comment by ImreSamu** [comment]
I am  _also_  fully satisfied with the proposal by @pnorman
For  "Translation QA" -  the 2 most important info :  "iD version" and "locale".

And my latest osm changeset statistics : https://gist.github.com/ImreSamu/2b31315ef2328cb482c7

**Comment by bhousel** [comment]
Sounds good, if everybody is happy with dropping these then I'll merge it...

**Pull request merged**
