### PR TITLE
Fields and default layer for man_made:bridge

### PR DESCRIPTION
**Pull request by LaszloEr**
- Added name, bridge type, layer and maxweight fields
- default layer should be set to 1 (like it is for highway=bridge)

### CODE REVIEW

**Comment by lakedistrictOSM** [comment]
Thanks for this PR, this is a much needed improvement.

**Comment by vershwal** [comment]
Great @LaszloEr!! Seems like some changes are required in the code. After you do the changes suggested by @SilentSpike do not forget to build the project before you push the changes. You can do it by running the command `npm run build`
Thanks!!

**Comment by LaszloEr** [comment]
I added the missing commas, this is what it looks like:
bridge

**Comment by Nakaner** [comment]
I don't think that adding a default `layer=1` is a good idea. It bears the risk that users who don't care for the `layer` tag add a bridge which has a different layer than the road on it.

It is easier for both data consumers and mappers to find objects without a certain tag than objects where a tag which was set by default is wrong.

**Comment by LaszloEr** [comment]
Good point. The reason why I wanted to add it as the default is because setting the bridge attribute on roads also adds it there automatically, probably because it's the correct for 99% of all bridges.

**Comment by bhousel** [comment]
Thanks @LaszloEr - this seems ok to me 👍

**Pull request merged**
