### PR TITLE
improve release algorithm

### PR DESCRIPTION
**Pull request by edpop**
Escape '\*' characters for correct display in Markdown.
Do not add force dist/locales/\*.json files, that are not ignored in master branch.

### CODE REVIEW

**Comment by bhousel** [comment]
Hmm, I kind of like being able to copy and paste these lines into the shell.. Can we instead wrap the whole thing in a `<code>` block or something?

**Comment by pnorman** [comment]
> Hmm, I kind of like being able to copy and paste these lines into the shell..

You should be able to with this change

image

> Can we instead wrap the whole thing in a <code> block or something?

Yes, a different format might be more useful since the checkboxes aren't really useful.

**Comment by edpop** [comment]
Still needs escaping :(

```<code>git add -f dist/*.css dist/*.js dist/img/*.svg dist/mapillary-js/</code>```

### Update and tag release branch
- [ ] <code>git add -f dist/*.css dist/*.js dist/img/*.svg dist/mapillary-js/</code>

Strange behaviour, star character shows before .svg

**Comment by pnorman** [comment]
> Strange behaviour, star character shows before .svg

The first two mark a section of italics.

**Comment by edpop** [comment]
You right.
I found only this solution.

    - [ ] ```git add -f dist/*.css dist/*.js dist/img/*.svg dist/locales/*.json dist/mapillary-js/```

### Update and tag release branch
- [ ] ```git add -f dist/*.css dist/*.js dist/img/*.svg dist/locales/*.json dist/mapillary-js/```

But now the source text is harder to copy.

**Comment by bhousel** [comment]
>Yes, a different format might be more useful since the checkboxes aren't really useful.

Agree, I really don't need the checkboxes.. This file is mostly for my own use to make sure I do all the steps.  It doesn't really need to look pretty.. Even this would be fine:

```bash
$ thing1
$ thing2
$ thing3
$ thing4
```

**Pull request merged**
