### PR TITLE
Fix pressing Escape with only one active node in area

### LINKED ISSUE #5941: Escape throws an error when drawing area with only one point
```
[Error] TypeError: undefined is not an object (evaluating 'entity.id')
	isInvalidGeometry (iD.js:60348)
	checkGeometry (iD.js:60313)
	finish (iD.js:60522)
	call (iD.js:786)
	ret (iD.js:30157)
	testBindings (iD.js:28419)
	bubble (iD.js:28477)
	(anonymous function) (iD.js:1527)
```

Possibly related: #5911

### PR DESCRIPTION
**Pull request by jguthrie100**
Fixes #5941

### CODE REVIEW

**Comment by jguthrie100** [comment]
press-escape-with-one-node-in-area

**Comment by quincylvania** [comment]
Thanks, @jguthrie100 👍👍

**Comment by maxgrossman** [comment]
...yay! Awesome for coming in for the quick bug fix @jguthrie100! 

Though I'm still stuck on feeling it is a little weird that some times the graph's `childNodes` method returns the # of nodes that the way obj has and other times it does not. Could it be that there a more problematic graph-related bug we need to investigate that this relatively innocuous bug has just brought light to.

**Comment by quincylvania** [comment]
@bhousel Do you know of any reason `childNodes` wouldn't return all the nodes?

**Comment by bhousel** [comment]
> @bhousel Do you know of any reason childNodes wouldn't return all the nodes?

Maybe it was called on a stale graph?  I can check this week..

**Pull request merged**
