### PR TITLE
Add simple access to advertising

### PR DESCRIPTION
**Pull request by ToastHawaii**
"Who can change the content of the board?" option added based on the Wiki page.

### CODE REVIEW

**Comment by quincylvania** [comment]
@ToastHawaii Hmm the meaning of this field seems ambiguous on these… I could also assume it refers to who can view or approach the feature.

**Comment by ToastHawaii** [comment]
@quincylvania Thanks for pointing that out. I add the visibility tag and moved the access tag to the more field section. I think this helps to improve the clarity.

Both are part of the documentation on the wiki pages eg. for board https://wiki.openstreetmap.org/wiki/Tag%3Aadvertising%3Dboard. The access property was add for 3 years.
Based on the taginfo the access tag is used many times in comination mit advertising https://taginfo.openstreetmap.org/keys/advertising#combinations 

Do you think it needs more? Is there anything I can do to make it less ambiguous?

**Comment by quincylvania** [comment]
@ToastHawaii Okay, if people are using this tag then it seems okay to have it under `moreFields`. Thanks for understanding 🤙

**Comment by ToastHawaii** [comment]
@quincylvania Thanks

**Pull request merged**
