### PR TITLE
(Don't merge yet)This is a small start for heathcare:speciality pre sets

### PR DESCRIPTION
**Pull request by ferdinand0101**
#7272 
This is a small test for Allergology 
I'd like to know if I'm doing this correctly.
Thanks.

### CODE REVIEW

**Comment by bhousel** [comment]
@ferdinand0101 Let's not do this.. It's generating a lot of notifications and I don't think we want to add a preset for every kind of medical specialty.

**Comment by ferdinand0101** [comment]
okay
1. sorry about the notifications I din't think about that when pushing each one to my branch
2. I understood it from the issue that while maybe not every most should be added

**Comment by ferdinand0101** [comment]
okay I'll create a new pr which should enable the field to be list but I won't do anything with the pre sets

**Comment by bhousel** [comment]
> 2\. understood it from the issue that while maybe not every most should be added

I really don't think we want presets for these at all..

_I'm trying to take a hands-off approach to iD these days, and let people work through tagging issues on their own.._ but.. there are hundreds of medical specialties and it's a multi-valued tag.  We can't really add a preset for every one right?   Many doctors offices will have a handful of specialties.

**Comment by bhousel** [comment]
> okay I'll create a new pr which should enable the field to be list but I won't do anything with the pre sets

Doesn't iD have this already?

I see this:

Screenshot 2020-01-23 10 25 20

**Comment by ferdinand0101** [comment]
Yes it seems like it has it.
But when I was in the folder creating it it wasn't there and I had to create it but now I can also see it anyways I guess it's all done.

**Pull request closed without merging**
