### PR TITLE
Quantify 'large' download

### PR DESCRIPTION
**Pull request by davidgilbertson**
'Large' on its own doesn't really convey any information :)

### CODE REVIEW

**Comment by bhousel** [comment]
Thanks @davidgilbertson & Happy New Year!  👍

**Comment by davidgilbertson** [comment]
That is the fastest I have ever seen a PR merged!

**Comment by bhousel** [comment]
This is the drunkest I've ever merged a PR!

**Comment by davidgilbertson** [comment]
I am honoured to have been a part of it.

**Pull request merged**
