### PR TITLE
added function to strip whitespace from searches

### PR DESCRIPTION
**Pull request by NateGrobe**
This is my solution for issue #7467

### CODE REVIEW

**Comment by secan** [comment]
Hi,
may I suggest you a simpler approach to solve the issue? Rather than splitting the string into an array of single characters, filtering out the white spaces and re-joining the array of characters in a single string, you could simply use the JavaScript bult-in function `String.prototype.replace()` (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/replace)

```javascript
function stripWhitespace(val) {
    return val.replace(/ /g, '');
}
```

**Comment by NateGrobe** [comment]
Hey,
I agree that replace is a better solution for this.
Out of curiosity, is there any advantage to using regex over a simple whitespace like `return val.replace(' ', '');`?

**Comment by secan** [comment]
If you use  a string (e.g. `' '`) only the first occurrence will be replaced while the regex allows you to replace all the occurrences (the "g" in `\ \g` stands for "globally").

> Out of curiosity, is there any advantage to using regex over a simple whitespace like `return val.replace(' ', '');`?

**Comment by NateGrobe** [comment]
Oh ok makes sense. Thanks!

**Comment by secan** [comment]
You're welcome

**Comment by quincylvania** [comment]
@NateGrobe Thanks for working on this! Sorry for the delay in responding, no one had been working on iD full-time for awhile.

Unfortunately, I merged this prematurely and had to revert. In testing, I noticed there's an issue with the original task described in #7467. If we only strip whitespace from the query and not the test strings, then it makes it impossible to search for things with whitespaces, like "South Broad Street". If you're still interested in working on iD feel free to open a new PR and we can work through a solution 🙂

@secan Thanks for the assistance here.

**Comment by ahmedragab96** [comment]
Hello @quincylvania, I am new to open source contributing and I'm interested to work on fixing this with you if possible.

**Comment by quincylvania** [comment]
@ahmedragab96 Thanks, but I think this is something @NateGrobe or myself should take care of. There are plenty of [other issues](https://github.com/openstreetmap/iD/issues) you can check out!

**Pull request merged**
