### PR TITLE
solves #9992

### PR DESCRIPTION
**Pull request by ramith-kulal**

### CODE REVIEW

**Review by matkoniecz — COMMENTED** [review]
is deleting bunch of svg files intentional?

**Comment by ramith-kulal** [comment]
> is deleting bunch of svg files intentional?

Sorry about the SVG file mix-up. I'm a newbie in open source and was fixing an issue when things went sideways. Any thoughts on why? Would really appreciate some guidance.

**Comment by matkoniecz** [comment]
No idea how it happened. Have you edited online, in browser? Locally?

If you know how to do it: I would reset branch and redo that single-line change.

If you do not know how: close this PR and open a new one doing just intended change.

**Comment by ramith-kulal** [comment]
> No idea how it happened. Have you edited online, in browser? Locally?
> 
> If you know how to do it: I would reset branch and redo that single-line change.
> 
> If you do not know how: close this PR and open a new one doing just intended change.

 I made the changes locally. I'm unfamiliar with resetting the branch, so I'll go ahead and close this PR. I'll open a new one

**Pull request closed without merging**
