### PR TITLE
Call leisure=swimming_pool something like 'Swimming pool (water area …

### PR DESCRIPTION
**Pull request by kepta**
Adds swimming pool facility to presets

Issue:https://github.com/openstreetmap/iD/issues/2927

### CODE REVIEW

**Comment by kepta** [comment]
@bhousel review ?

**Comment by bhousel** [comment]
This is really good!

A few minor nitpicks:
* Can you make a subfolder under `leisure` called `sports_centre`, then rename `swimming_facility.json` to `swimming.json` and put it in there.  (If we get more requests for subtypes of sports centres, they will go in the subfolder.  The `pitch` subtypes follow this convention too.)
* Rename `sports_center.json` to `sports_centre.json`.   (I know you didn't create this, it was this way already.  But we try to follow the convention of having the file named the same thing as the tag, so we may as well correct it now.)
* Remove `vertex` geometry type from the Swimming Pool and Swimming Pool Facility presets.
* Add a `leisure=water_park` preset (requested in #2927) <br/>
(icon = `swimming`, fields = `operator`, `address`; geometry = `point`, `area`)
* Add `terms` (to help place them properly in search results):
  *  "Swimming Pool" :   `"terms": ["dive", "water"]`
  *  "Swimming Pool Facility" :   `"terms": ["dive", "water"]`
  *  "Water Park" :   `"terms": ["swim", "pool", "dive"]`

**Comment by kepta** [comment]
@bhousel check now?

**Comment by bhousel** [comment]
Changes look good!  I'll merge them today.

The conflicts are because of differences in the minified json files..  This is something I did in c2833ba that is causing a lot of problems for everyone lately, so I think I'm just going to revert that change.  `git` can't diff those files correctly when the file is just condensed down to a single line.

**Comment by bhousel** [comment]
merged in fe246c6

**Pull request closed without merging**
