### PR TITLE
try some placeholder values for breathe.js

### PR DESCRIPTION
**Pull request by kepta**
I tried to use some reasonable values for the fills and radius.

I guess we want a bit more fine grained placeholder values?

ref: https://github.com/openstreetmap/iD/issues/3919

### CODE REVIEW

**Comment by bhousel** [comment]
I tested with the Chrome 59 profiler to see if these changes make a difference but it's not really clear to me.  I think there is a benefit but I will need to do some more testing when I'm more awake.  Also, Chrome changed their profiler around 58 so I'm not super familiar with the new Performance tab.

One thing for sure, the max line width will need to be wider.  It is obscured on thick roads. 

The reason we used `s.style` before (to get the calculated style) was because:
- When the user changes a line preset, it may have a new width .  e.g. changing from a think line `highway=residential` to a thin line `highway=service`, or `power=line`
- When the user toggles wireframe everything has small width and needs to change.

**Comment by bhousel** [comment]
Hey @kepta, last night Chrome 60 installed itself, so I took a look with the new profiler and I'm not sure whether querying the style is causing frame drops anymore.

Let's chat this week about performance stuff. There is a LOT in here that I don't understand and it would be great for us both to learn more about it.

**Comment by kepta** [comment]
@bhousel sounds great.

**Comment by bhousel** [comment]
closing as stale

**Pull request closed without merging**
