### PR TITLE
Load WMS tiles if EPSG:3857 (or equivalent) is supported by source

### LINKED ISSUE #1141: WMS support
via http://www.microformats.dk/2013/03/22/se-et-preview-af-det-nye-id-openstreetmap-redigeringsv%C3%A6rkt%C3%B8j/ + http://www.microformats.dk/2013/03/14/sadan-kalder-du-geodatastyrelsens-wms-tjenester-fra-josm/

Question is really whether there will be many WMS providers that support EPSG:900913

### PR DESCRIPTION
**Pull request by tyrasd**
partially fixes #1141.

### CODE REVIEW

**Comment by bhousel** [comment]
This looks great @tyrasd - is it still a WIP?  

It looks like you are planning to replace the `'{proj}'` with whichever supported projection `editor-layer-index` contains (currently hardcoded to 'EPSG:3857', which is the most common anyway).

**Comment by tyrasd** [comment]
> is it still a WIP? It looks like you are planning to replace the '{proj}' with whichever supported projection editor-layer-index contains (currently hardcoded to 'EPSG:3857', which is the most common anyway).

Yeah, I'd like to still fix that hardcoded EPSG code [there](https://github.com/openstreetmap/iD/pull/4814/files#diff-5029207b7599da40f52ba1ddec797e50R116) (there might be some obscure services just supporting for example `EPSG:900913` but not `EPSG:3857`).

Also, before we merge/release this, it would be good if we checked the respective WMS layers in ELI and add missing information like geographic extent – I think I saw quite a few of these claiming to be world-wide (`"geometry": null`) which actually aren't.

**Comment by tyrasd** [comment]
I'd say this can be merged now.

**Comment by bhousel** [comment]
Awesome @tyrasd - this is going to open up lots more imagery available for use in iD.. thank you!
I'm going to merge and add some test for the token replacement..

**Pull request merged**
