### PR TITLE
Add newer Hungarian ortophotos

### PR DESCRIPTION
**Pull request by Yogurt4**
A newer layer of the official all-country orthophotos were generated and now are available.

### CODE REVIEW

**Comment by tordans** [comment]
The aerial imagery is something that has to be added to the editor layer index. They will be pulled from there. 

Please make separate PRs for the other  changes in here.

**Comment by Yogurt4** [comment]
Hi,

> The aerial imagery is something that has to be added to the editor layer index. They will be pulled from there.

And where can I find that? This file was the only one I found the old layers in, both by name and by id.

> Please make separate PRs for the other changes in here.

I don't understand why Github made a PR with 4 commits (including my previous PR that is already merged in the main repo). Or is it compulsory to create a new fork for each modification?

**Comment by danieldegroot2** [comment]
> where can I find that?

See https://github.com/osmlab/editor-layer-index/tree/gh-pages/sources/europe/hu

or create issue here https://github.com/osmlab/editor-layer-index/issues ('new issue' button, top right)

> is it compulsory to create a new fork for each modification?

No, you can create a new branch on your existing fork for separate PRs to the same repo. See https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-and-deleting-branches-within-your-repository
But in this case you should create a fork of editor-layer-index repo instead and add a new branch there.

**Comment by tordans** [comment]
I will closed this PR with reference to https://github.com/openstreetmap/iD/pull/10224#issuecomment-2085272803

**Pull request closed without merging**
