### PR TITLE
fixes issue #2504

### LINKED ISSUE #2504: Introductory help text
The introductory help text (help on the side-bar) states

```markdown
Edits that you make on this map will be visible to everyone who uses
OpenStreetMap. In order to make an edit, you'll need a
[free OpenStreetMap account](https://www.openstreetmap.org/user/new).
```

Although technically correct, when viewed on OpenStreetMap.org this text can only be seen by someone who already has an account, so directing them to /user/new is not helpful.

A second more minor problem is that it directs to www.openstreetmap.org, and I was using the dev site, so it was the wrong link anyways.

### PR DESCRIPTION
**Pull request by harkirat96**
Changes core.yaml to fix #2504

### CODE REVIEW

**Comment by harkirat96** [comment]
Apologies for the previous pull request.

**Comment by jfirebaugh** [comment]
Thanks!

**Comment by pnorman** [comment]
I'm not sure this really fixes the issue. Anyone who sees this text will have already logged in.

**Comment by harkirat96** [comment]
If it is so then this text is irrelevant.We could delete this part from the file.

**Pull request merged**
