### PR TITLE
Added pencil icon.

### LINKED ISSUE #4798: 'Edit custom background' should have pencil icon, not magnifying glass
gm
'Edit custom background' should have pencil icon, not magnifying glass.

### PR DESCRIPTION
**Pull request by vershwal**
Fixes #4798.
Hey @bhousel!
I have added a new pencil icon and changed the icon for 'Edit custom background' from magnifying glass to pencil icon.
It was also mentioned in the issue that the text should say "Edit custom background URL template" and not "Edit custom background" but it was not discussed, so should I change the text too?

### CODE REVIEW

**Comment by bhousel** [comment]
Before|After
---|---
screenshot 2018-03-19 18 23 54|screenshot 2018-03-19 18 24 07

Thanks @vershwal 
It looks ok - can you adjust the width of the button so that it looks a bit more centered?

Also, did you draw it or find it somewhere?  Just want to make sure it is license compatible with this project. If there is any doubt, I can just redraw the icon from scratch - this is fine too.

**Comment by vershwal** [comment]
Hey @bhousel!!
I will adjust the width that is fine. But I didn't draw it from scratch. I found it [here](https://thenounproject.com/term/pencil/70731/) and then adjusted the code to fit it in our [iD-sprite.src.svg](https://github.com/openstreetmap/iD/blob/4b1f8a8f61a0d57ec015fbee91ed6375616755c2/svg/iD-sprite.src.svg). I was not aware of the licence part. Please check that. And if there is any doubt, I would love to draw it myself. I would have to learn it as this is my first time with SVG drawing, but that would be fun.

**Comment by vershwal** [comment]
Hey @bhousel!! I have modified the icon. I am sure that this one will be license compatible with this project.
Please check.
Before : 
screen shot 2018-03-23 at 11 22 55 pm
After:
screen shot 2018-03-23 at 11 34 14 pm

**Comment by bhousel** [comment]
The new icon looks really good ❤️ Thank you!

**Comment by vershwal** [comment]
Thank you @bhousel!!

**Pull request merged**
