### PR TITLE
added Kneipp Water Cure preset

### LINKED ISSUE #7313: kneipp_water_cure - Icon and more fields needed
Kneipp Water Cure Places are now common. An icon in iD would be very good. In addition, certain fields should be activated by default, such as:
 
kneipp_water_cure:foot=yes/no
kneipp_water_cure:arm=yes/no
kneipp_water_cure:face=yes/no
fee=yes/no
opening_hours=*
barrier=handrail
leisure=barefoot

More info about possible Tags:
https://wiki.openstreetmap.org/wiki/DE:Tag:amenity%3Dkneipp_water_cure

### PR DESCRIPTION
**Pull request by animesh-007**
added Kneipp Water Cure preset fixes #7313

### CODE REVIEW

**Comment by bhousel** [comment]
Can you rename the `facility.json` file to `kneipp_water_cure_multi.json` and make it like this?
```js
{
    "key": "kneipp_water_cure:",
    "type": "multiCombo",
    "label": "Basin Types"
}
```

This will make it a combo for picking the different `kneipp_water_cure:*` tags.  (The way you have it, iD would try to use a `facility` tag for this, which is wrong).

**Comment by animesh-007** [comment]
@bhousel I have committed the suggested changes.

**Comment by bhousel** [comment]
> @bhousel I have committed the suggested changes.

I still see a facility file.  can you `git rm` it ?

**Comment by bhousel** [comment]
looks good @animesh-007 , thanks for sticking with it! 👍

**Comment by animesh-007** [comment]
Thanks for merging it.

**Pull request merged**
