### PR TITLE
Rewrite Help and split into smaller chunks

### PR DESCRIPTION
**Pull request by manfredbrandl**
[WIP, do not merge] New help contens and text parts to help translators.

### CODE REVIEW

**Comment by bhousel** [comment]
This looks good!  Do you want to continue with the rest of the content?  I think I'd prefer to merge all of the changes at once (instead of across multiple PRs) so that translators don't need to keep coming back later.

**Comment by manfredbrandl** [comment]
> This looks good! Do you want to continue with the rest of the content? I think I'd prefer to merge all of the changes at once (instead of across multiple PRs) so that translators don't need to keep coming back later.
Okay, i will update all help texts and ask for review. Please do not merge now.

**Comment by manfredbrandl** [comment]
@bhousel you may merge now, but i don't know what to do with the Travis-CI-Error.

**Comment by manfredbrandl** [comment]
I give it a fresh try.

**Pull request closed without merging**
