### PR TITLE
Replace nested ternary expressions

### PR DESCRIPTION
**Pull request by quincylvania**
Nested ternary expressions can be inaccessible to beginners and are unnecessarily difficult to read for developers of all levels. For an open source app like iD, I contend it's better to avoid them. This PR enables the [no-nested-ternary](https://eslint.org/docs/rules/no-nested-ternary) linting rule and replaces all existing usage with less complex syntax.

### CODE REVIEW

**Review by kymckay — APPROVED** [review]
A sensible change

**Comment by quincylvania** [comment]
@bhousel Is there a wider reason you don't like this or just personal preference? I don't care strongly about this change, but I do think we should try to make the code as readable as possible for newcomers.

**Comment by bhousel** [comment]
> @bhousel Is there a wider reason you don't like this or just personal preference?

Just personal preference - I find concise code much easier to skim over.

**Comment by quincylvania** [comment]
Okay, maybe let's leave the rule disabled for now and just convert some of the most complex expressions.

https://github.com/openstreetmap/iD/blob/15c8e060f8444231076573db08383ca342bff0ce/modules/behavior/draw_way.js#L241-L242

**Pull request closed without merging**
