### PR TITLE
Update FAQ.md

### PR DESCRIPTION
**Pull request by GPSpilot**
self-explanatory

### CODE REVIEW

**Comment by danieldegroot2** [comment]
This doesn't solve any issues, but ok.

I initially can't find where to give feedback on imagery. The [fresh imagery page](https://labs.mapbox.com/bites/00240/) linked in [this article](https://blog.mapbox.com/a-year-of-improving-openstreetmap-with-map-feedback-598ac755abee) is still available. Not sure if they are still using it though.

**Comment by GPSpilot** [comment]
Wikipedia encourages editors to notate broken links as such, in order to encourage other editors to fix the broken links.  Shouldn't the Openstreetmap help articles do the same?
In that sense, it solves the issue of a broken link not being noted as such.



-----Original Message-----

**Comment by bryceco** [comment]
That paragraph should just be deleted. It implies that there is a feedback link for MapBox somewhere when in fact no such link exists.

**Comment by tyrasd** [comment]
I asked the community team at Mapbox what the current solution(s) exist to provide feedback about their imagery.

> That paragraph should just be deleted.

I'd like to only do this if there really is no way to provide feedback (or I don't hear from them in a reasonable time).

**Comment by 1ec5** [comment]
The Mapbox Feedback tool that this FAQ links to went away at some point last year. In its place, there’s a new [Mapbox Contribute](https://www.mapbox.com/contribute/) tool – this is what the “Improve This Map” link points to. But it only solicits edits to addresses, speed limits, etc., not product feedback at the moment.

**Review by pnorman — CHANGES_REQUESTED** [review]
Given the time without getting an updated link from Mapbox and them removing any way to report broken imagery, I'd remove the Mapbox line entirely.

**Pull request merged**
