### PR TITLE
Walkthrough updates

### PR DESCRIPTION
**Pull request by bhousel**
I'm going to work over the next few ~~days~~ weeks to close a bunch of issues with our walkthrough.  This will involve some bug fixing, but also I'll add some new content to teach the new right-click menu and address some of the more common OSM newbie errors..

see: [issues tagged walkthrough-help](https://github.com/openstreetmap/iD/issues?q=is%3Aopen+is%3Aissue+label%3Awalkthrough-help)

- [x] #2381
- [x] #2386
- [x] #3067
- [x] #3068
- [x] #3085
- [x] #3121 
- [x] #3403
- [x] #3675
- [x] #3680
- [x] #3925
- [x] #3936

### CODE REVIEW

**Comment by iandees** [comment]
Some feedback as I'm going through:

- The walkthrough asks you to "Select road from …" but the entry in the presets menu is "road features" because it's a group of presets. That might be confusing.
- The last step before it asks you to practice with more lines says to name the road, but the attributes pane isn't focusable because the "fog of tutorial" blocks it out.

**Comment by bhousel** [comment]
> The walkthrough asks you to "Select road from …" but the entry in the presets menu is "road features" because it's a group of presets. That might be confusing.

Good point.. I did notice that some steps of the walkthrough we token-replace the name into the message (e.g. "Choose {name}") and other places it's part of the translation string itself (e.g. "Choose Cafe").  I'm going to switch them all over to doing the former.

> The last step before it asks you to practice with more lines says to name the road, but the attributes pane isn't focusable because the "fog of tutorial" blocks it out.

Thanks, just fixed it in b923a6d 👍

**Comment by bhousel** [comment]
This is coming along really well and almost finished.. A few more things:

- [ ] Adjust timings (some things go too slow or fast)
- [ ] For playground step, make sure user really added Description field and not some other field
- [ ] Use token replace for preset/category names
- [ ] Try to shrink graph some more by renumbering ids
- [ ] More localization of names, ideally _all_ the names
- [ ] Adjust buildings tooltip illustration (it's not terrible but I don't love it)
- [ ] Teach realigning roads by moving nodes, adding midpoints (this is #2381)
- [ ] Teach deleting roads too (e.g. create some paper street development and have user delete it)

**Comment by iandees** [comment]
One more thing to consider is to review the user testing report that I did with CUTGroup in Chicago a few years ago. These people were newbies to iD and went through the walkthrough.

http://www.smartchicagocollaborative.org/cutgroup-6-openstreetmap-editor/

**Comment by bhousel** [comment]
Ran through this again today with a few people new to editing.. Here are my notes:

Jargon:
- [ ] People don't like the word "features"
- [ ] "main pane" as in "The main pane shows us the feature's attributes.." (Navigation Chapter)
- [ ] People don't like the word "nodes" (Areas Chapter)
- [ ] We say "Feature Editor" but sidebar says "Edit Feature"
- [ ] Define "presets" - or don't say "explore the presets" (play step, Areas Chapter)

Confusing:
- [ ] Teach zoom in/out
- [ ] Play step should find a way to remove the curtain before instructing the user to "Try moving the map and clicking..." or make it clearer that nothing will happen until they click OK.
- [ ] In point placement step, make sure to say that the mouse needs to be positioned where the point should go.. It's not _quite_ as simple as "hit spacebar to place the point" (Points Chapter)
- [ ] Teach that you can finish an area by clicking again on the last point placed?
- [ ] Be less strict about where the endpoint can go, when updating the line shape (Lines Chapter)

Bugs:
- [ ] In Buildings step, Adjust scrollTop so that "Building Features" is not all the way at the bottom
- [ ] Point hit target is still too big, causing overeager point snapping. We should not extend the hit target beyond the rendered points.  This causes problems when tracing areas/buildings.
- [ ] Undo while in draw-line mode leaves the `wTemp` temporary end segment.

**Comment by lukasmartinelli** [comment]
I can already edit/move stuff around in Navigation step (probably ok?).

q5gnyk2oom

You can move features out of the focus box and then no longer select it.

hvxilvsnsb

After the Navigation step I should click on Points. If I instead click on OK and then start dragging points/polys around - I am stuck without instructions until I click on the Points step again.

rqobillg19

**Comment by bhousel** [comment]
Thanks for your feedback @lukasmartinelli !
> I can already edit/move stuff around in Navigation step (probably ok?).

Yes this is ok, we reset the editing graph to known states at certain points in the tutorial - this is just in case the user decides to delete the thing right before we ask them to select it.

> You can move features out of the focus box and then no longer select it.

Good catch, I'll improve this so the box tracks the item as the user drags it.

> After the Navigation step I should click on Points. If I instead click on OK and then start dragging points/polys around - I am stuck without instructions until I click on the Points step again.

Yes this confused some of my other testers too.  I'll need to adjust the messaging a bit to make sure users don't forget that they need to click the next chapter to continue.

**Comment by PolyglotOpenstreetmap** [comment]
I'm going through the tutorial for the first time of my life, a little bit more and I'll be weaned of JOSM :-)

I'm having a problem in the lines step. I can't seem to add a node on Flower street to start adding a street going north. It's also not 'highlighted'.

Oh, now I notice that this is because I hadn't been following the instructions to the letter.

When deleting 12th Avenue, it reappeared (I used del key, maybe that wasn't right)

Moving on to buildings

I noticed that I can also finish a building shape by clicking enter or esc. space adds another node. Of course I accidentally pressed space with the mouse in the wrong place, then went on to tag it as a building. Then I got to the explanation of how to square the building, but that failed. If I had been a new user that would probably have confused me. Admittedly I don't have any suggestions how it would be possible to get back on track, when things start going south like that.

Anyway, being able to betatest like that is nifty feature (of github?)

I think what I would like to see is a dedicated way to draw buildings (accessible using 4 maybe?).Clicking on three corners would create a rectangular shape and then the mapper can move on. Simply tag them building=yes automatically.

The other thing I'd like is to use less nodes for circular buildings. Couldn't that number be made dependent on the size/surface of the building? 9-11 nodes per hut is more than enough to show that they are round shapes.

Maybe I'll propose to mentor a GSoC project to accomplish that next year, but it would be better if it would appear in iD sooner than that. HOT validators are really overwhelmed with the flood of buildings that are mapped poorly. My pet peeve is that I can not press 's' to  square the shape, while drawing it. I'm afraid that this is inherent to iD though, so it would be hard to solve. 
Pressing 's' starts searching in the tags.
So I'm still working on the geometry, but iD all of a sudden moves to tagging the shape. This is probably due to me being used to JOSM where keys pressed are always shortcut keys performing some action and tags are either added in the dedicated 'pane' or looking through the presets, after pressing F3.

Polyglot

**Comment by M1dgard** [comment]
This is great! So much better. \o/

Mostly it seems to be pretty fool-proof, but not in all situations:

* [ ] The most serious one: adding a name before you're asked to causes your beloved cafe to disappear.  
Adding a name before you're asked to causes the point to be deleted

* [ ] No, it's not.  
Changing the type of the Town Hall doesn't cause any reaction. Not disastrous but not very clean either  
Changing the type of the Town Hall doesn't cause any reaction. Not disastrous but not very clean either


* [ ] Selecting the building instead of the cafe.  
It's possible to (accidentally) select the building instead of the cafe, leaving you in the Feature Editor with the wrong feature

* [ ] First creating a non-intersection, and then an intersection is still possible. Extremely silly shapes are possible too, maybe you would like to catch this. (Both things depicted.)  
A completely messed up road, it has non-intersections with the other road and a ridiculous shape

**Comment by bhousel** [comment]
Thanks for the feedback everyone!  Over the past few days I've added a bunch of extra code to try to handle all of the situations where a user might get stuck.  This is a _much_ bigger challenge than with the old walkthrough code!  For example, the trainee can start adding some information to a feature, then undo all the way back to where the feature is an untagged area, which brings back the "choose preset" screen.  The previous walkthrough disabled undo in order to prevent situations like this, but I like better being able to teach about undo, and having the walkthrough work mostly the same way "real" editing works.

There are still a few things that need cleanup, but I'm getting pretty close to merging this so that the translators can get to work.

If you want to share this new walkthrough with anyone, please do so, and encourage them to post their feedback here on this PR, or reach out to me directly on OSMUS Slack or IRC (see [README](https://github.com/openstreetmap/iD#participate) for how to get on these).

Here is a tweet that you can share:
https://twitter.com/bhousel/status/853227516676501504

**Comment by mmdolbow** [comment]
Comments/feedback:
- In "Navigation", the last dialog, it says "Try moving the map and clicking on some other features...." but you can't move the map or click at that point in the walkthrough. NBD because when you click "OK", you can. This repeats at the end of each section. Maybe a small "Click OK to practice...." or a tooltip?
- When finishing a line, clicking again on the last node is suggested. Double-clicking also works I believe. I'm not sure which is better to suggest, but I usually do the double-click thing, because it's how I finish an area.

Bug? After clicking the checkbox to clear the attributes dialog for a building, I got stuck in a screen like shown below. Nothing worked at that point - I was getting a cursor change when hovering over buttons, making them appear clickable, but clicking didn't produce anything. It's almost like I got stuck between the transitions.
id-walkthrough-stuck

**Comment by M1dgard** [comment]
I remember seeing a similar situation to the one @mmdolbow describes ("stuck in a screen") but couldn't reproduce it.

**Comment by samanpwbb** [comment]
This tutorial is a huge improvement. With a track pad, "right click" isn't meaningful:
 
screen shot 2017-04-15 at 2 23 41 pm

EIther say "right click or control + click" or do feature detection and cater the text to the user's setup.

**Comment by bhousel** [comment]
> Bug? After clicking the checkbox to clear the attributes dialog for a building, I got stuck in a screen like shown below.

Thanks @mmdolbow!  I fixed that today.

**Comment by bhousel** [comment]
> This tutorial is a huge improvement. With a track pad, "right click" isn't meaningful:
> Either say "right click or control + click" or do feature detection and cater the text to the user's setup.

Good suggestion, @samanpwbb 👍   I added some additional words to the welcome chapter, and a small interactive button-pressing task to make sure the user can left and right click.

**Comment by bhousel** [comment]
Just a heads up, I'm planning to merge this today! 🎉 

There are a few bugs in the snapping and undo behaviors, but I can fix those after it merges.
If there are any more last minute suggestions for adjusting the language before we unleash the translators on all this new content, let me know!

**Comment by magol** [comment]
@bhousel 
Great job to create this walkthrough. I'm now working to localize it, and I have found some issues

- When I select a node, It do not view the localized street name.
- The adress format should be localized to. In Sweden, the attribute "state" has no meaning and the fields is in the wrong ordet. 
- In addition, I have noted that it is somewhat inconsistent with period in the end of sentence of some instructions.

image

**Comment by bhousel** [comment]
Thanks for the feedback @magol!  I moved your comments to a new issue #3976

**Comment by althio** [comment]
Is there some robust link we can use to refer to the walkthrough, a 'start the walkthrough' url ?

**Comment by bhousel** [comment]
> Is there some robust link we can use to refer to the walkthrough, a 'start the walkthrough' url ?

Not currently - users are prompted to start it their first time using iD, or they can start it by opening the Help screen.  But we don't have a url parameter to autostart the walkthrough, if that's what you mean?

**Comment by althio** [comment]
> we don't have a url parameter to autostart the walkthrough, if that's
what you mean?

Yes. That would be handy.

**Comment by bhousel** [comment]
>>Not currently - users are prompted to start it their first time using iD, or they can start it by opening the Help screen and clicking a button there. But we don't have a url parameter to autostart the walkthrough, if that's what you mean?
>
> Yes. That would be handy.

ok added #4111 for this

**Pull request merged**
