### PR TITLE
Avoid zorroing connected ways when moving a way

### PR DESCRIPTION
**Pull request by bhousel**
The simple case wasn't too bad:
zorro1

These get tricker, handling endpoints, closed ways, etc
zorro2

zorro3

I'm mostly happy with how it works, may make a few improvements before merging.

### CODE REVIEW

**Comment by tyrasd** [comment]
Wow, this is soo neat. :+1:

**Comment by jfirebaugh** [comment]
This is awesome!

One thing I notice is that the end result is path-dependent. Sometimes even when you move the line back to the original position, the intersection winds up in a different place:

nozorro

**Comment by jfirebaugh** [comment]
This could also avoid un-intersected crossings:

nozorro

**Comment by bhousel** [comment]
I did have a thought that instead of just allowing the non-intersection vertices to move freely, I should make a scale matrix and apply it to them instead.  I think that might make them move more naturally.

So maybe.. 
Intersections = figure out best placement and snap it there
Endpoints = move freely
All other vertices = scale

I did a refactor last night that is doing a better job at picking where the intersection should be (e.g. when 2 ways cross, fixing the zorro on the moving way can introduce one on the fixed way and v.v.).  I'll push soon..

**Comment by bhousel** [comment]
This is done today too!
@jfirebaugh the issues that you noticed before are working much better now.

This was one of those features where I had to try it every possible wrong way before settling on something that works well.

**Comment by bhousel** [comment]
Planning to merge this tomorrow if no further comment.

**Pull request merged**
