### PR TITLE
Flexbox buttons in top bar

### LINKED ISSUE #4356: Flexbox the buttons
This is like #4349 in that sometimes we should be better at layout long things in narrow space.  The solution is usually to just use [flexbox](https://css-tricks.com/snippets/css/a-guide-to-flexbox/), which gives us more control over how and whether things are allowed to wrap.

Currently our buttons are just floated things with fixed width, but I think we can use flexbox for layout instead.  If the buttons themselves are also flexbox containers for the icon and text, I think we might be able to drop the text labels when there is not room for them, leaving only the icons.  (This is a bit more elegant than just dropping the labels with a media query).

This is at around 750px wide screen.  It's worse for languages that use longer words:
screenshot 2017-09-18 09 36 11

cc @kepta

### PR DESCRIPTION
**Pull request by bhousel**
closes #4356

- Makes the "Sidebar" toggle button permanent but removes the label
- Did some things to the "Save" button to make it the same width whether there
  is a count or not (prevents the buttons from jumping when pressing undo/redo)
- Removes a lot of the floated col rules that aren't used much anymore

flexbox buttons

I'd like to figure out collapsing away the labels and leaving only icons on very narrow screens.  
(I know I can use a media query for this)

### CODE REVIEW

**Comment by bhousel** [comment]
Flexbox is also nice because most things Just Work when right-to-left. 

flexbox buttons rtl

**Comment by quincylvania** [comment]
Good call on removing the sidebar label and adding a shortcut! A couple notes:

- I assume the constant-width Save button works with longer localized text?
- When condensed, it looks like the margin between the sidebar button and the mode buttons is smaller than the margin between the other buttons.
- We might consider moving the spinner out of the top bar and recovering that space. The spinner is the only non-button up there anyway.

**Comment by slhh** [comment]
I think a button to collapse the sidebar would be more intuitive if it were placed within the sidebar.

Editing with collapsed sidebar is somewhat dangerous because users might not be aware which feature they are really editing. To mitigate the risk, when the sidebar is collapsed, place the feature type name and icon of the selected featureas a button in the topbar (in the column where the sidebar was). This can be the button to uncollapse the sidebar. Having to click on the feature type to open the sidebar to edit the feature properties seems to be intuitive.

When multiple features are selected, the uncollapsing button might contain a selection summary like "10 nodes, 3 way, 2 relations" (but with words replaced by icons).

**Comment by quincylvania** [comment]
@slhh When I was implementing the sidebar collapse I tried making the "open sidebar" button preview the selected feature, much like you describe, but it turned out to be a larger design challenge than expected. It might be worth pursuing in the future.

For now, the sidebar automatically opens whenever the user selects a feature, meaning the only way they can edit a feature with the sidebar closed is if they close it _after_ they select it. In my estimation, this makes accidental edits unlikely.

**Comment by bhousel** [comment]
btw I changed the sidebar resizer a bit today.. It keeps the map still now, which I find a lot easier to use. 

keep map still

**Comment by quincylvania** [comment]
@bhousel That's a great improvement! It had been visually unwieldy.

**Comment by bhousel** [comment]
Although now this can happen 🤔 

sidebar hides point

**Comment by bhousel** [comment]
sorry @quincylvania I just realized I forgot to answer your questions!

> * I assume the constant-width Save button works with longer localized text?

Yes!.. It's actually tricky.  The count span has a larger min-width to hold up to about a 3 digit number, but the label can grow if the word is longer.  When the save count goes away, the label jumps to the right slightly.. It's opaque so hard to see, but that's ok.  The important thing is that the undo/redo buttons don't jump!

save button

> * When condensed, it looks like the margin between the sidebar button and the mode buttons is smaller than the margin between the other buttons.

Good noticing!  I think it's because the sidebar button is just sitting by itself, and the other groupings have another div with padding there.  I will fix it 👍 

> * We might consider moving the spinner out of the top bar and recovering that space. The spinner is the only non-button up there anyway.

Yes, now with things more responsive, it looks a little weird to reserve space for it when it's not there, and it's not something the user can interact with.  Maybe we should put it at the bottom near the status-y things.

**Comment by bhousel** [comment]
I was so annoyed at the save button changing its width and moving the undo/redo buttons that I recorded an image of that yesterday too 😆 

jumpy save

**Comment by jguthrie100** [comment]
> Although now this can happen 
> 
> sidebar hides point

This would be fixed by #4128 (or you could pan only if the feature falls under the sidebar)

**Comment by bhousel** [comment]
> (or you could pan only if the feature falls under the sidebar)

I'll see how this option feels.. It sounds like a good idea.

**Comment by quincylvania** [comment]
> I was so annoyed at the save button changing its width and moving the undo/redo buttons that I recorded an image of that yesterday too 😆

Oh that is annoying. I didn't notice it during my implementation. Thanks for the fix!

> Yes, now with things more responsive, it looks a little weird to reserve space for it when it's not there, and it's not something the user can interact with. Maybe we should put it at the bottom near the status-y things.

Sounds like a good solution to me.

**Comment by bhousel** [comment]
> Oh that is annoying. I didn't notice it during my implementation. Thanks for the fix!

It wasn't in your implementation - it only started once I switched them to flexbox and the buttons could resize more.

**Comment by bhousel** [comment]
I've added a function to check the toolbars for overflow, and drop elements that we don't need on narrow screens (like the button labels and loading spinner).. 

responsive top bar

**Comment by bhousel** [comment]
I just added some code to address https://github.com/openstreetmap/iD/pull/5455#issuecomment-435557142 - so the sidebar will not obscure selected things when it expands.  This works for OSM stuff (entities and notes) as well as external data.

sidebar avoid entity

This is good to merge now!

**Pull request merged**
