### PR TITLE
Post office should have opening_hours instead collection_times

### PR DESCRIPTION
**Pull request by HolgerJeromin**

### CODE REVIEW

**Comment by bhousel** [comment]
You are right - thank you!

**Comment by gileri** [comment]
Couldn't they have both ? Usually there is a specific time each day when the collected mail is sent to a sorting/distribution site, and past this time the mail would be collected/sent the next day; which is very much like a post_box.

**Comment by HolgerJeromin** [comment]
This is probably not easy to verify.

**Comment by gileri** [comment]
In france, [post office collection times are available on lapostefr.fr](http://imgur.com/ZwTL3VF), the official website for post offices (see bottom of picture).

I think that you can get collection times in post offices by asking at the counter, and I trust it can be qualified as "easily verifiable", even if it need a survey.

**Pull request merged**
