### PR TITLE
Module for iD.Detect()

### PR DESCRIPTION
**Pull request by bhousel**
Re #3179 
This PR moves the `iD.detect()` iife into a module under `util`.
(I still export it as `iD.Detect()` so that embedding code like the rails site can test whether iD is supported.)

This PR also removes the `start.js` and `end.js` wrappers around `id.js`, because there is almost nothing left to wrap.

@tmcw @kepta for the review?

### CODE REVIEW

**Comment by kepta** [comment]
It looks good to me.

My only concern is that we might give `util/detect.js` a special treatment. 
Till now, every other submodule is expected to be picked off from its `index.js` file.

**Comment by bhousel** [comment]
> My only concern is that we might give util/detect.js a special treatment. 
> Till now, every other submodule is expected to be picked off from the submodule/index.js file.

`util/jxon` and `util/diff3` are like this too..

I don't really know why we still have the `index.js` files unless we are planning to break them back up into submodules again.  I hope so, because that way made more sense to me.

Put another way, I liked the namespaces we used to have, so I kind of prefer code like:
```js
import * as actions from '../actions/index';
...
context.perform(actions.Disconnect(params), ...)
```

instead of the current:
```js
import { Disconnect as DisconnectAction } from '../actions/index';
...
context.perform(DisconnectAction(params), ...);
```

Having every file make up it's own names for the things in the other files is just weird to me.

**Comment by tmcw** [comment]
> Put another way, I liked the namespaces we used to have, so I kind of prefer code like:

I prefer it too on an aesthetic level and it is a bit easier to write, but it comes with disadvantages that I think outweigh the benefits:

* `import * as actions` means that rollup cannot do tree-shaking at all, so there's no chance for the file to optimize any part of actions _out_ - you're importing everything, so it'll include everything. Specifying specific parts of actions lets tree-shaking happen.
* `import { Disconnect } from './actions'` will throw a _compile time error_ if you misspell the import as disconnect or Disconect. Importing an object and then referencing a method on it, like `actions.Disconnect`, will delay this error to runtime, which may be also the time a user is using iD.

**Comment by kepta** [comment]
Imho,
we should consider 'util' as a sub module and abstract away its internal
directory structure.
By that I mean,
To keep the index.js as a place import anything from the 'util' sub module.

Put another way,
Is there any disadvantage to using

import { Detect } from 'util/index'

Instead of

import { Detect } from 'util/detect'

**Comment by tmcw** [comment]
I'm not terribly opinionated either way. Right now, for jxon and diff3, as @bhousel pointed out, we're using `util/` as a stopping place before those modules become external and we start to say `import merge from 'diff3'` instead of touching util at all. In those cases, I don't see much reason to import them _via_ `util/index`, since that import will soon change anyway, to the external module.

I can see `util/index` as having the advantage that you can import multiple utils at the same time, but that advantage doesn't really come into effect here since there's only one place we import Detect in the entire codebase.

**Comment by kepta** [comment]
Ok I wasn't aware of the fact that `util` is just a transition thing.
Lets go ahead with this PR 😎.

**Comment by tmcw** [comment]
:shipit:

**Pull request merged**
