### PR TITLE
preset for man_made=monitoring_station

### LINKED ISSUE #4532: preset for man_made=monitoring_station
http://wiki.openstreetmap.org/wiki/Tag:man_made%3Dmonitoring_station

### PR DESCRIPTION
**Pull request by abdeldjalil09**
Resolves #4532

### CODE REVIEW

**Comment by bhousel** [comment]
Thanks @abdeldjalil09 👍   I'm going to squash these commits into a single commit, then fix a spelling mistake..

**Comment by abdeldjalil09** [comment]
How to edit/add multiple files in single commit ?

**Comment by bhousel** [comment]
> How to edit/add multiple files in a single commit ?

The best way to work on iD is to make a fork of iD on GitHub, then follow the instructions in the [README.md](https://github.com/openstreetmap/iD/blob/master/README.md) to set up a local copy of iD.  

You should ideally leave the `master` branch alone, so that you can always keep it in sync with the main iD.  When you want to change files, you make a "feature" branch just for the changes:

``` bash
git checkout -b <branchname>
```
(replace `<branchname>` with something that says what you're working on, e.g. `monitoring_station`)

Then you can change the files however you want to and test by visiting `http://localhost:8080/`.  

Then do this when you are happy with the changes:

``` bash
git add <files>
git commit
git push <remote> <branchname>
```
(e.g. `git push origin monitoring_station`)

And open a pull request from your fork to the main iD.  

I know it sounds like kind of a lot, and it is nice that GitHub has a built in editor that handles these steps for you automatically, but having a fork and a local copy of iD where you can test things is very useful and will save you time in the long run.  After you've done it a few times, working with git will become automatic.

GitHub also made a really great tutorial on how to use git: https://try.github.io

**Comment by abdeldjalil09** [comment]
"http://localhost:8080/" doesn't work

**Comment by bhousel** [comment]
> "http://localhost:8080/" doesn't work

What have you tried?  I'm pretty sure if you follow the README steps [starting here](https://github.com/openstreetmap/iD#prerequisites), you should end up with a working local copy of iD.  If not, please let us know so we can update the README  👍

**Pull request merged**
