### PR TITLE
Update help and walkthrough for touch interactions

### LINKED ISSUE #7692: Update documentation and walkthrough for touch interactions
iD has historically been tailored for mouse and keyboard input only. Now that we're supporting touch and stylus pointers, the help materials need updating.

### PR DESCRIPTION
**Pull request by quincylvania**
Closes #7692.

Creating a PR for this since the documentation is foundational and the more eyes we can get on it the better. Also, this will invalidate the translations of lots of long strings, so I'd like to get it right the first time.

My strategy for the walkthrough is only showing instructions specific to the last-used input device. I suspect most users will use the same input device throughout the entire walkthrough, but this is adaptive nonetheless.

### CODE REVIEW

**Comment by quincylvania** [comment]
So since we have to change a lot of strings anyway for touch support, it's a good opportunity for some other upgrades.

I added a whole lot more placeholders so the labels in the documentation will always match the labels in the UI. The walkthrough strings now use the same placeholder list as the help pane. I also made the inline hotkey styling consistent with tooltips and the shortcuts lists.

I've finished updating the walkthrough. When possible, I tried to use the same strings for both mouse and touch interactions. When interaction instructions are required, iD detects if the mapper is using touch or not. The possibility of an attached keyboard is left open.

The help pane isn't done yet, but I might go ahead and merge anyway so translators can get started.
 
IMG_0005

**Comment by quincylvania** [comment]
Merging since I'm pretty happy with this and I didn't get any pushback. I'll notify translators about what's going on and give them a few days to hack away at the changes.

**Comment by quincylvania** [comment]
Here are screenshots of some of the updated sections featuring a whole bunch of new, custom icons!

-----

Screen Shot 2020-07-13 at 2 39 13 PM

-----

Screen Shot 2020-07-13 at 2 39 41 PM

-----

Screen Shot 2020-07-13 at 2 40 00 PM

-----

Screen Shot 2020-07-13 at 2 40 16 PM

-----

Screen Shot 2020-07-13 at 2 39 32 PM

**Comment by maro-21** [comment]
> I'll notify translators about what's going on and give them a few days to hack away at the changes.

Whew, 164 strings.
Polish and Spanish are ready!
Please wait a little for German and Japanese before releasing the new version!

**Comment by quincylvania** [comment]
@maro-21 Thanks a bundle!! I'm planning to wait until Monday or so. #7786

**Pull request merged**
