### PR TITLE
Adding streetsign layer

### PR DESCRIPTION
**Pull request by peterneubauer**

### CODE REVIEW

**Comment by peterneubauer** [comment]
Guys,
what is the best way to merge this into a small PR that only contains my changes?

**Comment by bhousel** [comment]
I was planning to just checkout the latest master to a new branch and git cherry pick your things onto it.  I can probably do it this afternoon.

**Comment by peterneubauer** [comment]
Awesome, thanks a lot!

**Comment by peterneubauer** [comment]
That's cool,
Thanks Bryan!

**Pull request closed without merging**
