### PR TITLE
4489 add missing office presets

### PR DESCRIPTION
**Pull request by Nmargolis**
Adds association, advertising_agency, and surveyor office presets as requested in #4489. 

This is my first time contributing, so I'm very open to feedback!!

I also noticed there were several other presets missing that are on the [OSM Wiki](https://wiki.openstreetmap.org/wiki/Key:office) (see below). Should those be added as part of a separate issue?

Here are the other ones on the OSM Wiki:
- adoption_agency
- charity
- energy_supplier
- forestry
- foundation
- guide
- logistics
- moving_company
- notary
- private_investigator
- quango
- religion
- tax
- tax_advisor
- travel_agent
- water_utility

### CODE REVIEW

**Comment by abdeldjalil09** [comment]
We need also :
office=tax_advisor --> https://wiki.openstreetmap.org/wiki/Tag:office=tax_advisor
office=quango --> https://wiki.openstreetmap.org/wiki/Tag:office=quango
office=water_utility --> https://wiki.openstreetmap.org/wiki/Tag:office=water_utility
office=forestry --> https://wiki.openstreetmap.org/wiki/Tag:office=forestry
office=foundation --> https://wiki.openstreetmap.org/wiki/Tag:office=foundation

**Comment by bhousel** [comment]
Looks great @Nmargolis!    You can add the other ones on the list to this PR also, and we'll merge them all together.

There are a few cases where I would probably change the names to be a bit more recognizable to a US-English speaker, but overall it's ok.  (e.g. "Association" I would call a "Nonprofit Organization Office")

**Comment by bhousel** [comment]
Wow that was fast, thanks @Nmargolis .. Is this ready to merge?

**Comment by Nmargolis** [comment]
thanks @bhousel! 🎉

**Pull request merged**
