### PR TITLE
Preset for natural=tree_row

### PR DESCRIPTION
**Pull request by Stalfur**
Preset for natural=tree_row

### CODE REVIEW

**Comment by jfirebaugh** [comment]
The diff here is empty -- want to give it another go?

**Comment by Stalfur** [comment]
Yarr, I'm brilliant at gitting.. hang on.

**Comment by pnorman** [comment]
It's failing travis with

```
Writing location.js file
PhantomJS is already installed at /usr/local/phantomjs/bin/phantomjs.
editor-imagery-index@0.0.0 node_modules/editor-imagery-index
node build.js
Unknown preset field: height in preset Tree row
make: *** [data/data.js] Error 1
npm ERR! Test failed.  See above for more details.
npm ERR! not ok code 0
```

**Comment by Stalfur** [comment]
Removed height field

**Comment by bhousel** [comment]
720b261 includes `tree_row`, so I'm closing this.

@Stalfur next time you want to add a preset, ping me on IRC and I'll walk you through your git setup.

**Pull request closed without merging**
