### PR TITLE
Adds preset for seamark:type=buoy_lateral

### LINKED ISSUE #5285: Create preset for seamark:type=buoy_lateral
Lateral [buoys](https://wiki.openstreetmap.org/wiki/Seamarks/Buoys) are anchored, floating makers in waterways that line the edges of channels. The [`seamark:type=buoy_lateral`](https://wiki.openstreetmap.org/wiki/Tag%3Aseamark%3Atype%3Dbuoy_lateral) tag has been used [over 42,000 times](https://taginfo.openstreetmap.org/tags/seamark%3Atype=buoy_lateral#overview), yet it has no preset in iD.

- Name: Lateral Buoy
- Tags: `seamark:type=buoy_lateral`
- Allowed geometry: points
- Common fields: Name, Ref, Operator
    - Note: seamarks mostly use the [`seamark:name`](https://wiki.openstreetmap.org/wiki/Key:seamark:name) key rather than `name` or `ref`
- Speciality fields. These are critical since a buoy's appearance determines its meaning. Each can be edited with dropdown selectors.
    - Color (`seamark:buoy_lateral:colour`)
    - Category (`seamark:buoy_lateral:category`)
    - Shape (`seamark:buoy_lateral:shape`)
    - System (`seamark:buoy_lateral:system`)
- Icon: buoy

### PR DESCRIPTION
**Pull request by quincylvania**
Closes #5285 by adding a Lateral Buoy preset and four related fields: buoy color, category, shape, and system.

### CODE REVIEW

**Comment by bhousel** [comment]
Ohhh [seamark](https://wiki.openstreetmap.org/wiki/Seamark_tagging_schema)..  😭 
I've avoided adding any of these kinds of tags to iD as presets.

The reasons are:
* The practice of embedding `object`, `attribute`, `#` in the key is not always compatible with how iD can setup presets and fields.  For example, specifying [units]( https://wiki.openstreetmap.org/wiki/Seamarks/General_Attributes#Height.2Flength_units_.28HUNITS.29) or sector number of a [sectored light](https://wiki.openstreetmap.org/wiki/Seamarks/Sectored_and_Directional_Lights) (like `seamark:light:1:colour=green`) in the key is a real problem for how iD works.  I actually think we could support most of the basic `seamark:<object>` stuff, but it gets really scary fast.
* I don't think these are the sort of preset an untrained mapper could use.  Most people know what a "buoy" is, but definitely not whether it is "lateral", or how to recognize any of the categories or iala systems.  I think you'd find that people would just add a node for anything that looks like a buoy and the preset would be very likely to be misused.

Are you sure you really want to add this into the main iD for everyone?  I'm inclined to say no, but I could definitely see a "basic seamark preset pack" being a thing once we implement #5049 and people can add their own custom presets to iD at runtime.

**Comment by quincylvania** [comment]
Hi Bryan, thanks for the detailed response. I was thinking there must be a reason that no seamark presets have been added yet. I agree with your points. I'm not set on this addition whatsoever—I'm not even a heavy seamark user myself—but here are some additional thoughts you may consider:

- Seamarks represent a sizable percentage of OSM features. iD shouldn't be all things to all people, but it currently excludes the needs of seamark mappers altogether. I admit the tagging schema is unfortunately complex, though like you said, supporting basic `seamark:<object>` style tagging would be doable and should be considered.
- A "seamark preset pack" sounds like it could be an excellent idea. However, I would still find it amiss to not include _any_ support for so numerous a set of tags out of the box.
- I wonder how often most casual mappers run across nautical features at all. I would assume that most stick to land and wouldn't have much opportunity to mistag seamarks, but I don't have proof of this.
- Presets would help casual mappers understand existing seamarks that they run across, as well as easily follow the links to the seamark documentation. Without presets, encountered seamarks just look confusing and possibly incorrect. If mistagging is truly an issue, a read-only approach by excluding seamark presets from search might be worthwhile.
- As for specifically mistagging the type of buoy, presets such as "Red Buoy" and "Green Buoy" could be added. The color is a sufficient start for identifying the type of buoy, is observable in imagery, and doesn't require the user know the difference between lateral, ordinal, and other buoy types.

Since trepidation remains on the matter, I suggest further discussion with the community before proceeding. I may try implementing more basic seamarks to see how far iD can get with the schema. Ideally, some sort of user testing might tell us how seamark presets would actually be received, but I'm new around here and I'm not sure if that's possible.

Thanks for taking the time to read and consider this ✌️

**Comment by bhousel** [comment]
Thanks for understanding @quincylvania 

The surface area of seamark tagging is huge:
https://wiki.openstreetmap.org/wiki/Seamarks/Seamark_Objects

I'm ok with adding a few of the most common things that casual mappers might come across and understand how to map.  Buoys seem like a good start.

Can you share a location on OpenStreetMap that you think is pretty well mapped seamark-wise?  Most mappers (including me) are pretty unfamiliar with it.  As far as I can tell, it's only ever come up for discussion once before on the iD issue tracker (#2589)

**Comment by quincylvania** [comment]
This PR has been superseded by #5297.

**Pull request closed without merging**
