### PR TITLE
Lanes

### LINKED ISSUE #387: Support for lane and turn lane tagging
The road style should reflect the number and type of lanes added. 

Further a smplified method of tagging lanes should be available.

See http://wiki.openstreetmap.org/wiki/Key:lanes and http://wiki.openstreetmap.org/wiki/Key:turn

### PR DESCRIPTION
**Pull request by kepta**
To bring the awesome (turn) lane editing features to iD.

Things left
* [ ] Bothways
* [ ] Merge icons
* [ ] UI nit picks
* [ ] bugs marked as TODO in code

(closes #387)

### CODE REVIEW

**Comment by kepta** [comment]
single
Oneway turn lane editing

**Comment by pnorman** [comment]
Is this PR still intended to be merged? There's been no activity in over a year and it's got conflicts.

**Comment by bhousel** [comment]
> Is this PR still intended to be merged? There's been no activity in over a year and it's got conflicts.

It would take a lot of work at this point to get it merged, but I think it's still worth trying.  The UI is kind of confusing, so I think best course of action is to start over when I can find a few weeks free.  For now, JOSM is really your best option for tagging lane information.

**Comment by PhillyMay** [comment]
Wow, I think it looks fantastic. That would make lane editing so much easier.
If this gets implemented, maybe there will be a similar editor for changing speed limits on one road for different directions

**Comment by CoderThomasB** [comment]
What was the reason that this MR was closed?

**Comment by 1ec5** [comment]
By the time it was closed, it had already become very stale: lots of merge conflicts, no longer possible to cleanly apply atop the current development branch. But anyways the discussion in #387 went in a different direction design-wise, focusing on an inspector field rather than floating map overlays.

**Pull request closed without merging**
