### PR TITLE
Add telecom exchange preset

### PR DESCRIPTION
**Pull request by simonbilskyrollins**
Fixes issue #6780

### CODE REVIEW

**Comment by bhousel** [comment]
There are a lot of strange tags being included in this request.. 
Did you copy these from the OSM wiki or something?

**Comment by simonbilskyrollins** [comment]
Yes, I added all the tags specified in the linked GitHub issue as well as those listed on the [OSM wiki page for `telecom=exchange`](https://wiki.openstreetmap.org/wiki/Tag:telecom%3Dexchange). I put mandatory and recommended tags in the `fields` list and optional tags in the `moreFields` list.

**Comment by bhousel** [comment]
> Yes, I added all the tags specified in the linked GitHub issue as well as those listed on the [OSM wiki page for `telecom=exchange`](https://wiki.openstreetmap.org/wiki/Tag:telecom%3Dexchange). I put mandatory and recommended tags in the `fields` list and optional tags in the `moreFields` list.

Ok, I think I'm going to drop `building:prefabricated`, and `owner`.
I also don't see what `man_made` and `street_cabinet` are doing there.
Actually there are some other things about it, like we can't just name it "Exchange".

Thinking about it more, It's easier for me to just close and redo it.  Thanks though!

**Comment by flacombe** [comment]
> Ok, I think I'm going to drop `building:prefabricated`, and `owner`.

No problem, these are really optional tags

> I also don't see what `man_made` and `street_cabinet` are doing there.

telecom=exchange is a functional role of a given site hosting telecom=service_devices.
It can physically consists in building but a simpler street cabinet also (at least in Europe).
If wiki isn't clear enough I can improve it.

> Actually there are some other things about it, like we can't just name it "Exchange".

Although this is reviewed tagging it's always open for suggestions.
This has been discussed for months, not sure a better wording will be found.

**Pull request closed without merging**
