### PR TITLE
adding the option "internet_access:fee=customers"

### PR DESCRIPTION
**Pull request by Elefant-aus-Wuppertal**
make internet_access:fee to an combo field for adding the option "internet_access:fee=customers", see https://wiki.openstreetmap.org/wiki/Key:internet_access:fee

### CODE REVIEW

**Comment by Elefant-aus-Wuppertal** [comment]
At the moment, I unluckily do not understand what the "all checks have failed" field wnts to say to me... :/

**Comment by bhousel** [comment]
There is a syntax error in the file that you changed... Also if you click on "Files Changed" the GitHub diff for this Pull Request highlights the error too.

Screenshot 2020-03-10 12 27 01

**Comment by Elefant-aus-Wuppertal** [comment]
Oh, I see, thanks. I just tried to correct it. I think a { was there which shouldn't have been.

**Comment by quincylvania** [comment]
@Lukas458 I incidentally closed this by renaming the default branch. You'll need to open another PR. Apologies!

**Comment by Elefant-aus-Wuppertal** [comment]
Oh, I see. Okay, so I will open a new one. Thank you for information.

**Pull request closed without merging**
