### PR TITLE
Added clubhouse preset

### PR DESCRIPTION
**Pull request by TheAdventurer64**

### CODE REVIEW

**Comment by quincylvania** [comment]
Thanks, @TheAdventurer64. I changed the name to Golf Clubhouse since there are other types of clubhouses. I also added some fields and terms.

**Comment by TheAdventurer64** [comment]
👍 Thank you for getting back to me on this. I appreciate the preset field improvements, as well as the fixes for the search terms. But I have to ask: Why did you edit the wig extensions?

**Comment by quincylvania** [comment]
> Why did you edit the wig extensions?

@TheAdventurer64 What do you mean? I don't think this relates to the clubhouse preset…

**Comment by TheAdventurer64** [comment]
Well, you edited the wig extension preset in 3e3f56f.

**Comment by quincylvania** [comment]
@TheAdventurer64 That's a link to the merge commit for this PR, so I'm afraid you're mistaken. In #8054 we added a search term to the Wig Shop preset, maybe that's what you mean?

**Comment by TheAdventurer64** [comment]
Yes.

**Comment by quincylvania** [comment]
@TheAdventurer64 We often add more search terms for presets so they'll appear when someone types in related words. In this case, extention is a misspelling of extension, but instead of changing it we just added both.

**Pull request merged**
