### PR TITLE
Fix issue #6617

### PR DESCRIPTION
**Pull request by CarycaKatarzyna**
This concerns issue [#6617](https://github.com/openstreetmap/iD/issues/6617) . When user clicks on "Use a bridge"/"Use a tunnel" it splits edge if is long and creates bridge/tunnel. Later user may correct bridge/tunnel location by manually shifting nodes.

### CODE REVIEW

**Comment by quincylvania** [comment]
Hi @CarycaKatarzyna! Thanks so much for this, it looks really great. I merged it as-is and then followed up with a few tweaks.

**Comment by quincylvania** [comment]
Here's a screencapture. I this feature will be really helpful and will hopefully reduce instances where mappers erroneously select the connection fix since it was the easiest. 

add structure fix demo

**Comment by bhousel** [comment]
So awesome 🎉 
I've wanted this for a while...

**Comment by tordans** [comment]
Awesome, this is perfect for [the way I map](https://github.com/openstreetmap/iD/issues/6501#issuecomment-500100028). Thanks!

**Comment by matkoniecz** [comment]
One more thank you, this is something really useful! It is nice to see iD editing getting easier.

I am now adding missing bridges/tunnels (more than 300 cases of broken data, in Rymanów and in Beijing), I was not expecting that iD has a chance to be better than JOSM for this task.

**Pull request merged**
