### PR TITLE
Update transit presets for Public Transport v2 schema

### LINKED ISSUE #3041: Improve public_transport tagging
_highway=platform_ was obsoleted in 2011 (see http://wiki.openstreetmap.org/wiki/Tag:highway%3Dplatform ), but the ID editor still suggests it when adding a highway.
I suggest we keep the interface as it is, but change the tag added to public_transport=platform instead.

More details on the available option in http://wiki.openstreetmap.org/wiki/Tag:highway%3Dbus_stop .

### LINKED ISSUE #3508: mark public_transport=station as bus station
mark public_transport=station as bus station. The wikipage says [0] that public_transport=station should better be used than amenity=bus_station. So tag bus stations as 'public_transport=station' by default.

Thanks

[0] http://wiki.openstreetmap.org/wiki/Tag:amenity%3Dbus_station

### PR DESCRIPTION
**Pull request by bhousel**
(closes #3041)
(closes #3508)
(closes #4566)

This updates all of the transit-related presets to use the [Public Transport v2 Schema](https://wiki.openstreetmap.org/wiki/Proposed_features/Public_Transport)

Generally what I did was:
* make a bunch of legacy presets non-searchable (existing features will still be recognized by iD, but new features will get both the legacy and the PTv2 tags).
* add new presets under `data/presets/public_transport/` which include the `public_transport=*` tags _and_ also set the legacy tags too.
* add good search terms for everything and update the names of the presets to try to guide users to do the right thing
* make sure that the reference documentation points to the best page (often that's the legacy one).

I still have to test this a bunch, but hope to merge soonish so that translators can get to work 👍

### CODE REVIEW

**Comment by bhousel** [comment]
This is mostly ok.. I'm going to make a few icon tweaks to make sure that all of the different supported transport modes have a good icon.  Maki contains good ones for bus, rail, light-rail, subway(metro), aerialway, ferry.  The internal iD-sprite has a few others, but might be line only: monorail and maybe some others.  

- [ ] Make sure all the icons are consistent (we have a mix of new maki for poi, and old maki for lines)
- [ ] Do something better for tram/light_rail?  (trams have tracks in a road, light-rail is a mostly separated system)
- [ ] Do something for trolleybus (electric rubber-tire bus powered by overheard caternary wires, even just the bus icon with something above it would help)
- [ ] See if the monorail line icon in the iD-spritesheet can be used for poi features (without the line)
- [ ] See if we can better differentiate between platform (where people wait) and stop_position (where vehicle stops).  I've talked to normal people about this and they hate it.  This part of PTv2 is weird and non-intuitive, but we should try.


Consistency and better coverage is important so that people using the presets will know what they are for and map correctly.

**Comment by bhousel** [comment]
Ok I think I have the icons all sorted out - I'm pretty happy with them!

screenshot 2017-12-05 00 18 04screenshot 2017-12-05 00 22 03

**Comment by nlehuby** [comment]
Thanks !

When will it be available in osm.org ?


Le 5 décembre 2017 06:36:30 GMT+01:00, Bryan Housel <notifications@github.com> a écrit :
>Merged #4585.
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/openstreetmap/iD/pull/4585#event-1371944114

-- 
Envoyé de mon appareil Android avec Courriel K-9 Mail. Veuillez excuser ma brièveté.

**Comment by bhousel** [comment]
> When will it be available in osm.org ?

1 or 2 weeks - I need to give a chance for the translators to catch up, and they already have a lot of work to do on the new Help text.  I'll send out some reminders on twitter and mailing lists that we could use help..

**Pull request merged**
