### PR TITLE
Declare missed but used dependencies in package.json

### PR DESCRIPTION
**Pull request by artembert**
I found out that some of the dependencies aren't declared in the package.json. I used [depcheck ](https://www.npmjs.com/package/depcheck) to get the list of missed dependencies and added them to the package.json

### CODE REVIEW

**Comment by artembert** [comment]
@mbrzakovic, do you think the changes are meaningful?

**Comment by mbrzakovic** [comment]
@artembert  thank for contributing! apologies for delayed response.
d3 is kind of special case as a d3 package only re-exports stable versions of d3-* subpackages. So we actually don't need to specifically add each d3-* subpackage as a dependency (and I also wouldn't want dependabot to ping on these).

pbf is a good catch, please do leave that line of code and we can close this PR.

**Comment by artembert** [comment]
@mbrzakovic, thank you for your feedback! I updated my PR

**Comment by artembert** [comment]
@mbrzakovic, could we merge this PR?

**Comment by jguddas** [comment]
There are two instances of `import Protobuf from 'pbf';`, are you sure that pbf can be removed?

https://github.com/openstreetmap/iD/search?q=pbf

**Comment by artembert** [comment]
> There are two instances of `import Protobuf from 'pbf';`, are you sure that pbf can be removed?
> 
> https://github.com/openstreetmap/iD/search?q=pbf

We will not delete it but declare it in "dependencies"

**Pull request merged**
