### PR TITLE
Added landuse=plant_nursery

### PR DESCRIPTION
**Pull request by jmespadero**

### CODE REVIEW

**Comment by pnorman** [comment]
You've got 9 commits that only end up with a diff changing one file. Did something go wrong with your usage of git?

**Comment by bhousel** [comment]
They submitted #2715 but I didn't pull it all in, instead I squashed it, so their master is out of sync with our master.

@jmespadero can you sync your repository up and try this change again?

A really good way to keep your fork up to date is to add our repository as an upstream remote:
`git remote add upstream git@github.com:openstreetmap/iD.git`

Then frequently `git pull upstream master` to keep things in sync.

When you want to make changes, make a feature branch, so that your master branch can always get pulled forward cleanly even if you are working on other things.
`git checkout -b my-new-presets` 

And then do your pull requests from that feature branch.

Another useful tip: if you find yourself making changes and reverting them, do `git commit --amend` to replace your last commit, instead of making a new one.  It makes it easier for us to see what you did :)

Hope that helps... Feel free to email or IRC me if you have any questions.

**Comment by jmespadero** [comment]
Thanks, I have always used SVN, and Git look a bit messy for me. 
I have done:
git remote add upstream git@github.com:openstreetmap/iD.git
git pull upstream master
git push
git status

If I [compare openstreetmap/iD with jmespadero/iD](https://github.com/openstreetmap/iD/compare/master...jmespadero:master) I still see "10 commits. 1 File change" 
I suppose that if I do a pull request, there will be 10 commits again.

So, why are past commits still there?  How do I get rid of them?

**Comment by bhousel** [comment]
It looks like your master branch diverged from ours a while ago... You can try this to sync up:

To preserve your plant-nursery changes someplace:
```
git checkout -b ahead
```

To sync up master:
```
git checkout master
git reset --hard 7b4c6d2
git pull upstream master
git push -f origin
```

To restore your plant-nursery changes at the end of master branch:
```
git checkout -b plant-nursery
git cherry-pick c1d3f41 9038c5d
make
git commit --amend
git push -u origin plant-nursery
```

Ahead branch can be deleted:
```
git branch -D ahead
```

Then you should end up with a plant nursery branch that is just 2 commits ahead of our master and redo your pull request from there..

(Lmk if you get stuck, I didn't actually try all of these commands myself)

**Comment by bhousel** [comment]
Git can be kind of confusing at first if you have a background in SVN.  I was that way too..

One thing that really helped me was making this alias in my `~/.gitconfig` so that I can run `git changes` to see the entire history visually.
```
changes = log --color --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit
```

**Comment by jmespadero** [comment]
Wow...

I suppose that I could also have done a copy of the plant-nursery.json file elsewhere, sync, and then restored the file.

My problem still is... the make command ends with an error. So when I add a preset, somo files are not updated, and my repository gets out of sync. 
If I run make, I don't get much information:

```bash
jmespadero@mc ~/bin/iD $ make
node data/maki_sprite.js
make: *** [css/feature-icons.css] Error 1
```
If I run "make -d",  I got errors related to maki ... which was installed along iD, isn't it?

```bash
jmespadero@mc ~/bin/iD $ make -d
 ...

        Trying pattern rule with stem `maki_sprite.js'.
        Rejecting impossible implicit prerequisite `data/maki_sprite.js.S'.
        Trying pattern rule with stem `maki_sprite.js'.
        Trying implicit prerequisite `data/maki_sprite.js.mod'.
        Looking for a rule with intermediate file `data/maki_sprite.js.mod'.
         Avoiding implicit rule recursion.
         Avoiding implicit rule recursion.
         Trying pattern rule with stem `maki_sprite.js.mod'.
         Trying implicit prerequisite `data/maki_sprite.js.mod,v'.
         Trying pattern rule with stem `maki_sprite.js.mod'.
         Trying implicit prerequisite `data/RCS/maki_sprite.js.mod,v'.
         Trying pattern rule with stem `maki_sprite.js.mod'.
         Trying implicit prerequisite `data/RCS/maki_sprite.js.mod'.
         Trying pattern rule with stem `maki_sprite.js.mod'.
         Trying implicit prerequisite `data/s.maki_sprite.js.mod'.
         Trying pattern rule with stem `maki_sprite.js.mod'.
         Trying implicit prerequisite `data/SCCS/s.maki_sprite.js.mod'.
       Trying pattern rule with stem `maki_sprite.js'.
       Rejecting impossible implicit prerequisite `data/maki_sprite.js.c'.
       Trying pattern rule with stem `maki_sprite.js'.
       Rejecting impossible implicit prerequisite `data/maki_sprite.js.cc'.
       Trying pattern rule with stem `maki_sprite.js'.
       Rejecting impossible implicit prerequisite `data/maki_sprite.js.C'.
       Trying pattern rule with stem `maki_sprite.js'.
       Rejecting impossible implicit prerequisite `data/maki_sprite.js.cpp'.
       Trying pattern rule with stem `maki_sprite.js'.
       Rejecting impossible implicit prerequisite `data/maki_sprite.js.p'.
       Trying pattern rule with stem `maki_sprite.js'.
       Rejecting impossible implicit prerequisite `data/maki_sprite.js.f'.
       Trying pattern rule with stem `maki_sprite.js'.
       Rejecting impossible implicit prerequisite `data/maki_sprite.js.F'.
       Trying pattern rule with stem `maki_sprite.js'.
       Rejecting impossible implicit prerequisite `data/maki_sprite.js.r'.
       Trying pattern rule with stem `maki_sprite.js'.
       Rejecting impossible implicit prerequisite `data/maki_sprite.js.s'.
       Trying pattern rule with stem `maki_sprite.js'.
       Rejecting impossible implicit prerequisite `data/maki_sprite.js.S'.
       Trying pattern rule with stem `maki_sprite.js'.
       Rejecting impossible implicit prerequisite `data/maki_sprite.js.mod'.
       Trying pattern rule with stem `maki_sprite.js'.
       Trying implicit prerequisite `data/maki_sprite.js.sh'.
       Looking for a rule with intermediate file `data/maki_sprite.js.sh'.
        Avoiding implicit rule recursion.
        Trying pattern rule with stem `maki_sprite.js.sh'.
        Trying implicit prerequisite `data/maki_sprite.js.sh,v'.
        Trying pattern rule with stem `maki_sprite.js.sh'.
        Trying implicit prerequisite `data/RCS/maki_sprite.js.sh,v'.
        Trying pattern rule with stem `maki_sprite.js.sh'.
        Trying implicit prerequisite `data/RCS/maki_sprite.js.sh'.
        Trying pattern rule with stem `maki_sprite.js.sh'.
        Trying implicit prerequisite `data/s.maki_sprite.js.sh'.
        Trying pattern rule with stem `maki_sprite.js.sh'.
        Trying implicit prerequisite `data/SCCS/s.maki_sprite.js.sh'.
       No implicit rule found for `data/maki_sprite.js'.
       Finished prerequisites of target file `data/maki_sprite.js'.
      No need to remake target `data/maki_sprite.js'.
     Finished prerequisites of target file `css/feature-icons.css'.
     Prerequisite `data/line-icons.json' is newer than target `css/feature-icons.css'.
     Prerequisite `data/relation-icons.json' is newer than target `css/feature-icons.css'.
     Prerequisite `node_modules/maki/www/maki-sprite.json' is older than target `css/feature-icons.css'.
     Prerequisite `dist/img/maki-sprite.png' is newer than target `css/feature-icons.css'.
     Prerequisite `data/maki_sprite.js' is newer than target `css/feature-icons.css'.
    Must remake target `css/feature-icons.css'.
node data/maki_sprite.js
Putting child 0x0122b5a0 (css/feature-icons.css) PID 3882 on the chain.
Live child 0x0122b5a0 (css/feature-icons.css) PID 3882 
Reaping losing child 0x0122b5a0 PID 3882 
make: *** [css/feature-icons.css] Error 1
Removing child 0x0122b5a0 PID 3882 from chain.

```

**Comment by jmespadero** [comment]
Solved. I owe you a beer.

**Comment by bhousel** [comment]
> I suppose that I could also have done a copy of the plant-nursery.json file elsewhere, sync, and then restored the file.

Haha yes, for just one preset file the git commands are overkill, but maybe next time it will be a bunch of commits that you need preserved.

> I suppose that I should add these file also in the commit.

Yes that's right - sorry I forgot the `add` from the original instructions.
You can just `git add .` to stage them all..

```
git add .
git commit --amend
```

**Pull request closed without merging**
