### PR TITLE
Addition of more visual cue to Rail icons

### LINKED ISSUE #2967: Make icons for disused and abandoned railways more clear
According to the docs, disused railways still have rails. When they are removed, it's abandoned. ~~The icons kind of suggest the reverse~~:
railways

### PR DESCRIPTION
**Pull request by kepta**
screen shot 2016-02-17 at 3 59 58 am

(closes #2967)

### CODE REVIEW

**Comment by bhousel** [comment]
Awesome!   Can you get rid of the diagonal slash lines?   I think they were just adding to the confusion from #2967.   Then you can stick the Abandoned Railway trees right in the middle of the tracks.

**Comment by samanpwbb** [comment]
Hey kepta! I designed these icons way back in the day. I think this is a good start, but before these icons are shippable, the graphics need to be cleaned up:

1. Every tag icon has a consistent margin between the main icon and a representation of the path below the icon – you broke this rule:
  screen shot 2016-02-16 at 6 11 45 pm

2. Every icon is 'pixel aligned' – so all the details look sharp on screens. Here's the regular rail icon with a grid enabled. Notice how all the geometries align to the grid?:
  screen shot 2016-02-16 at 6 12 49 pm

3. When two objects in the icons touch each other, there should be a consistent 1 pixel negative space border:
  screen shot 2016-02-16 at 6 17 16 pm

4. I think you can focus both of your concepts in order to make the communicate more clearly. Remove the unclear diagonal lines, and emphasize the bushes you added to the disused railway icon and the trees over the abandoned railway icon. 

Let me know if you have any questions.

**Comment by kepta** [comment]
Hey @samanpwbb thanks for your feedback on the icons. I have updated the commit as per your suggestions, please have a look.

screen shot 2016-02-18 at 7 13 44 pm

**Comment by samanpwbb** [comment]
These are great, nice work!

**Comment by bhousel** [comment]
Great job @kepta!

**Pull request merged**
