### PR TITLE
Infobox / distance measurement

### PR DESCRIPTION
**Pull request by bhousel**
This adds an information widget with some info about the selected items and distance/area measurement capability per #2519 

* Show/hide with 'i' key
* Toggles metric/imperial

cc @aaronlidman @jfirebaugh 

distance-measurement

### CODE REVIEW

**Comment by pnorman** [comment]
Does this change https://github.com/openstreetmap/iD/issues/2039#issuecomment-56242986?

**Comment by bhousel** [comment]
It may end up being a disabled feature that only advanced users can turn on via forking iD or developer console. Not sure yet.

**Comment by bhousel** [comment]
@aaronlidman and @tristen want to add your thoughts on this?  It's intended for power users to measure distance, perimeter, area.   

I know it feels a bit hacky in its current state.  I would eventually like to change the "widgety" things (map-in-map, mapillary, and this) to be plugins, and give them a clearer plugin UI, i.e. give them a dedicated place in the dom to add themselves, allow users to drag/reposition to their liking, and maybe some UI with the name of what it is, and 'X' to close.  But that's for later.

**Comment by aaronlidman** [comment]
The functionality is good as is we just need a design pass to make it fit in with the rest of iD's aesthetic.

**Comment by tristen** [comment]
Made some small adjustments. In summary:

- Variable height depending on the context list
- Added width that alligns with the grid
- Re-use classnames shared by the interface
- Changes to the unit toggle:
    - Shortened name to current unit of measurement (Accounted for this change in i8n)
    - Display as a button to match other toggle/button like elements in the interface

Looks like this:

infobox

**Comment by bhousel** [comment]
Looks nice, thanks @tristen !

**Comment by aaronlidman** [comment]
Nice!

@bhousel Good to merge?

**Comment by bhousel** [comment]
Sure, looks good to merge to me..

**Comment by sisskind** [comment]
@bhousel @tristen I noticed that when you create a polygon feature, the measurement tool only measures the lines created by the user.  If the user double-clicks to create polygon, the last segment is not included in the perimeter measurement.  Double-checked with line tool.  Will open an issue - but wanted to document here.

**Pull request merged**
