### PR TITLE
Baby steps mode

### PR DESCRIPTION
**Pull request by tmcw**
This turns js/id/actions into CommonJS modules and creates js/id/actions.js with browserify. Refs #891 - this is an approach that would let us gradually transition to modules, by porting them into `modules/`, including them from `dist/modules`, and gradually introducing `require()`

cc @bhousel for the review

### CODE REVIEW

**Comment by kepta** [comment]
thats awesome @tmcw ⭐️⭐️⭐️

**Comment by tmcw** [comment]
Re-ran the tests and they pass now. @kepta and @bhousel want to review, see if this approach will let us do the gradual path? Given that other PRs will land soon, I want to avoid conflict city as soon as someone PRs anything related to actions.

**Comment by bhousel** [comment]
I kind of feel weird generating the file into `dist/modules/actions.js`.  Anything we put into `dist`, people might build on and expect to stick around.

Would it make more sense to put it under something like `js/lib/modules` instead?   When this is done, most of `js/lib` will go away and be replaced by modules, right?

**Comment by bhousel** [comment]
Also, per chat with @kepta, any thoughts on using [rollup](http://rollupjs.org/) instead of browserify?  It seems to support more kinds of module patterns, maybe could be useful if we ever want proper es6 modules.  Downside is it's newish and doesn't have great documentation. 

We aren't opinionated about this, just wondering if you have experience with it.

**Comment by tmcw** [comment]
> Would it make more sense to put it under something like js/lib/modules instead? When this is done, most of js/lib will go away and be replaced by modules, right?

That was my first iteration, but we have `eslint` running on all files in `src`, and browserified bundles do not mix with eslint. We could make an exception, but it does underscore that a bundle is a generated file, not a source file.

> Also, per chat with kepta, any thoughts on using rollup instead of browserify?

I'm totally open to it as an experiment, but I have doubts. Rollup supports _only_ ES6 modules on the way in, and [ES6 modules, while great, have a very uncertain future](https://medium.com/@nodesource/es-modules-and-node-js-hard-choices-2b6995e4d491?utm_source=javascriptweekly&utm_medium=email). There's zero node.js support, and zero browser support, so any node-based or browser-based iD tests, even of pure, non-browser dependent code, would need transpilation. The same with if we ever wanted to provide iD components as standalone modules: they would always need to go through rollup in order to have a `main` entry that's loadable in node. And if we want to provide modules that provide 'es6 goodness' and let people take advantage of the tree-shaking abilities of rollup, we'd need both a transpiled `main` and non-transpiled `jsnext:main`.

The benefits of ES6 modules - slightly smaller filesize and enhanced export semantics - are real, but I'm not convinced that they outweigh the cost of integrating with any other JavaScript and the uncertainty around the standard's future.

But on the other hand ¯\_(ツ)_/¯ it could be fun

**Comment by bhousel** [comment]
Thanks for helping with this @tmcw!  
I moved the intermediate file from `dist/modules` to `js/lib/id`.. For now this is less disruptive to downstream projects like openstreetmap-website.

Sticking with `browserify` for now - we can switch to something else later if it makes sense to do so.

**Pull request merged**
