### PR TITLE
Offset

### LINKED ISSUE #1340: drag to adjust imagery offset
if the imagery is really off, clicking the arrows can be really tedious. i understand if this is intended though to prevent people getting totally wild with the offsets though, could go either way.

### PR DESCRIPTION
**Pull request by kepta**
This patch allows to adjust imagery offset by
    1. dragging
    2. manually entering offset
    3. fine tuning with buttons
 (closes #1340)

### CODE REVIEW

**Comment by kepta** [comment]
@bhousel, 
All functionalities are working. The styling is up for for discussion.
I want to check if the implementation is as desired.

Can you please review and suggest  changes?

**Comment by bhousel** [comment]
I haven't forgotten about this, I'm going to shoot for a Friday release of 1.9.2, and then revisit this over the weekend.

**Comment by bhousel** [comment]
Thanks for your work on this @kepta!  
I made some changes today to show the offset in meters.
I really like how it turned out! :rocket: 

imagery_offset1

**Comment by mjvanderveen** [comment]
Great feature and thank you for implementing it. Would it be possible to add the option to set the offset for a specific source as an url parameter?

**Comment by bhousel** [comment]
> Great feature and thank you for implementing it. Would it be possible to add the option to set the offset for a specific source as an url parameter?

yes, that's a good suggestion - can you open a new ticket for this? 👍

**Pull request merged**
