### PR TITLE
update domain name for ImproveOSM

### LINKED ISSUE #9993: ImproveOSM public service URL changes
We've standardized the DNS names for the ImproveOSM project. As a result, the URLs for the ImproveOSM services publicly available have been updated as follows:
- Missing Geometry Service: https://community.improveosm.org/missingGeoService/
- Direction of Flow Service: https://community.improveosm.org/directionOfFlowService/
- Turn Restriction Service: https://community.improveosm.org/directionOfFlowService/

Please be aware that the URLs presently utilized by the iD tool will continue to be operational until December 4th. Could you arrange a schedule for the modifications of the ImproveOSM service URLs used by the iD tool?

Thank you.

### PR DESCRIPTION
**Pull request by k-yle**
Closes #9993

### CODE REVIEW

**Comment by radubaba-grabtaxi** [comment]
@k-yle Hello Kyle, not sure of the whole process here but do you think we can get this merged soon ? We've extended the deadline of Dec 4th but really need to move forward with decommissioning the old URLs. If there's something needed from our end please let me know.

**Comment by k-yle** [comment]
Hey @radubaba-grabtaxi, sorry only @tyrasd can merge PRs. Releases seem to happen every 3 months, sometimes more often. As far as I know, there is no longer a regular release schedule. @tyrasd would be the best person to ask.

**Comment by tBeata-grab** [comment]
Hello @tyrasd, is there a possibility we could expedite this change? As @radubaba-grabtaxi has previously indicated, our initial Dec 4th deadline has been greatly extended and is blocking our progress with the root URL decommissions. In addition, the certificates for the old URLs have now expired.
Your prompt attention to this matter would be much appreciated.

**Review by tordans — APPROVED** [review]
@tyrasd this looks like a PR that is easy to review and merge.

**Pull request merged**
