### PR TITLE
 Add one-sided triangular markers to ways with sides (e.g. natural=cliff).

### LINKED ISSUE #1475: Better rendering for tags with left/right semantics (e.g. coastline, cliff)
The following tags make ways "non-reversible":(aka the semantics depend on way direction) natural=cliff, natural=coastline,    barrier=retaining_wall and man_made=embankment. 

There is no "good" way of handling these outside of showing an "are you sure" alert or similar, this needs to be done for both explicit reversal and implicit (when merging ways).

Updated list of tags:

natural=cliff
natural=coastline
barrier=retaining_wall
barrier=kerb
barrier=guard_rail 
man_made=embankment. 
barrier=city_wall if two_sided != yes

some people believe that waterway=\* belongs in this list too

### PR DESCRIPTION
**Pull request by huonw**
This generalizes the oneway arrow logic for adding SVG markers along a
line. Using that functionality, certain tags get arrows on their
right-hand side, indicating which side is "inside", e.g. the
right-side of a cliff is the lower side.

The list of tags considered to be sided (unless there's a
two_sided=yes tag) is:

- natural=cliff
- natural=coastline
- barrier=retaining_wall
- barrier=kerb
- barrier=guard_rail
- barrier=city_wall
- man_made=embankment

The triangles attempt to be reminiscent of the triangles used for
rendering cliffs on OSM (and elsewhere). The different tags get
different renderings (e.g. colors that match the main way, and
different spacings). In addition, natural=coastline is special-cased
to have blue markers (despite having a green way), to emphasise that
the "inside" of a coastline is the water.

The triangles attempt to be reminiscent of the triangles used for
rendering cliffs on OSM (and elsewhere).

Fixes #1475.

Picture:

id-triangles

(The two lines for barrier=city_wall demonstrates the boundary of lengths when a new marker appears/disappears.)

(This also adds tests for oneway arrows to check that the generalization doesn't break it.)

### CODE REVIEW

**Comment by bhousel** [comment]
This is sooo good - thank you @huonw 🎉

**Comment by huonw** [comment]
Wow, thanks for the fast merge!

**Comment by RudyTheDev** [comment]
First of all, I love this! Time to to go and click `V` a thousand times.

However, I would suggest these be much subtler. In particular, guard rails are placed along the roads, which means they will run parallel to the road and the arrows will point at the road. In practice, this means they overlap (some here are in the wrong direction):

noisy

Here's a more zoomed-in example, which would be a typical "editing zoom":

noisy2

I would say the arrows should be no more than half the current size and without a gap between the line.

**Comment by bhousel** [comment]
Good suggestions @RudyTheDev - I've spun it off into a new issue #5533

**Pull request merged**
