### PR TITLE
Adding Seychelles and Pitcairn Islands

### PR DESCRIPTION
**Pull request by leighghunt**
Adding Seychelles to list of countries driving on the left.

### CODE REVIEW

**Comment by bhousel** [comment]
The islands you've added are all outside of the normal [-180,180] bounds for longitudes.  Aren't they included in the file already?

Screenshot 2019-09-03 18 48 56

**Comment by leighghunt** [comment]
I can't believe I missed that! - Let me just check all of them and resubmit.

**Comment by bhousel** [comment]
> I can't believe I missed that! - Let me just check all of them and resubmit.

sure! (Seychelles looks correct though)

**Comment by leighghunt** [comment]
Hi @bhousel - think I've got it sorted (living in NZ, I really shouldn't get tripped up by the dateline!) - you already had Samoa, Tokelau, Tonga, Niue, Cook Islands, but I've added the  Pitcairn Islands, so the only two actual changes are habited Pitcairn Islands, and Seychelles.

Thanks for your patience! Would you believe this all started as I wanted to add Hong Kong mainland to another project!?! :-)

**Comment by bhousel** [comment]
> Thanks for your patience! Would you believe this all started as I wanted to add Hong Kong mainland to another project!?! :-)

No worries!  I'm glad this data is helpful to your project..  Thanks for the additions 👍

**Pull request merged**
