### PR TITLE
fix text padding in key-value input field

### PR DESCRIPTION
**Pull request by 51114u9**
When you input/retrive long texts in the ket-value box, the combobox caret hide the end of it

captura de pantalla - 130317 - 01 15 49

### CODE REVIEW

**Comment by bhousel** [comment]
Looks pretty good to me.  Can you check this also with `&rtl=true` in the url, just to make sure it looks ok right-to-left.

**Comment by 51114u9** [comment]
@bhousel no, I will check.

**Comment by 51114u9** [comment]
@bhousel ok, now right-to-left looks good.

**Comment by bhousel** [comment]
Can you double check the css rules?  Now it looks like all the fields have extra padding.. 
(I'm in LTR right now):

screenshot 2017-03-15 16 18 53

**Comment by 51114u9** [comment]
my error, but I fixed. I tested with two directions and looks good.

**Pull request merged**
