### PR TITLE
Create features from geoservices

### LINKED ISSUE #4164: Creating OSM Features in iD from ArcGIS Services
## The Goal
Knowledgeable users can easily contribute reviewed and authoritative data to OpenStreetMap with the iD editor using data extracted from an ArcGIS Map or Feature Services. This issue serves to introduce the concept and ask for feedback from the primary iD contributors and maintainers before submitting a PR (as requested in Contributing.md).

## Background
(edit: the use of authoritative in this statement should be reconsidered)
Many Esri customers using ArcGIS are authoritative data creators and maintainers. In many areas, densely detailed user-submitted data is available in OpenStreetMap, but in many others, there is a limited density of data even though easily-accessible authoritative data exists. Currently, to make use of these datasets OpenStreetMap contributors would need to export the ArcGIS Map Service to a Shapefile or PostGIS database and then use desktop tools such as JOSM to edit and upload to OpenStreetMap, or go through a lengthy import process to import a selected set of data which is not already available in OSM or which is more precise or more accurate than current OSM features.

This proposed feature aims to make it easier for volunteers to add features queried from the GeoServices REST API (ArcGIS Server Map Services and Feature Services) to OpenStreetMap using iD. By connecting directly to the ArcGIS Service form an iD session, contributors are getting the most up to date data and also can more easily contribute this data without the need for complex workflows. The tool will also allow users to match up existing attributes from the source data (for example, house numbers on building footprints) to relevant OSM tags to make adding authoritative attribution straightforward along with geometries.

## Solution

This feature will add the capability for contributors to select “Add GeoService Layer” and then provide the URL to an ArcGIS REST Service or Feature Layer (ex. http://maps2.dcgis.dc.gov/dcgis/rest/services/DCGIS_DATA/Transportation_WebMercator/MapServer/5). Before loading, the contributor will be able to specify whether specific attributes should be mapped from the source layer to specific OSM tags, or whether any other static tags should be added to all features. The iD editor will load the vector features of the current map extent as temporary objects in the browser window (not immediately submitted as edits to OSM). 

The contributor can then select objects generated from the ArcGIS Layer, inspect and alter any tag values or geometries and submit them as edits to OSM (additions or replacements for features). They can then save their changeset, contributing these new objects to OpenStreetMap via iD's existing functions.

## Implementation

An [initial working version of this feature](https://github.com/mapmeld/iD) has already been developed using a branch from the iD GitHub repository and is nearing readiness for submitting a PR to the master iD branch. We have attempted to address potential concerns about ease of import and user experience in the initial version.

cc @jgravois @mapmeld @ajturner

### PR DESCRIPTION
**Pull request by jgravois**
demoed at [SOTMUS US 2017](https://2017.stateofthemap.us/program/adding-arcgis-data-to-id). resolves #4164.

Fetch service metadata and confirm license is valid:
add_new_service

Re-add a service with a license that was previously confirmed:
add_existing_service

Map service attributes to OSM tags and import the features in view:
map_attributes2

Review and approve individual features:
review_and_approve_features5

we can continue to use the fork [issue tracker](https://github.com/mapmeld/iD/issues/
) if the discussion here gets difficult to follow.

cc/ @slibby @mapmeld (primary dev)

### CODE REVIEW

**Comment by slibby** [comment]
A demonstration of this functionality is available at http://mapmeld.com/iD.

Sample location from GIFs is: 
http://mapmeld.com/iD/#background=Bing&map=18.63/40.21001/-105.10642

Sample service (not licensed/vetted, only for demo): http://maps.bouldercounty.org/arcgis/rest/services/PARCELS/BUILDINGS_STRUCTURE_FOOTPRINT/MapServer/0

**Comment by jgravois** [comment]
i published [`esri-to-geojson: v1.0.4`](https://github.com/GeoXForm/esri-to-geojson/releases/tag/v1.0.4) this morning. that _should_ resolve the error uglifying the project.

**Comment by briandaviddavidson** [comment]
[This chunk is also going to fail CI](https://github.com/openstreetmap/iD/pull/4633/files#diff-13a6fc7cfcdc970a06e21de5a143f3e4R32)

The expects below that need to be bumped up one number since `[1]` is now taken by `data-layer-geoservice`

**Comment by bhousel** [comment]
This is awesome!! Thanks @jgravois @mapmeld and @slibby .. I'm eager to try this out..

Let's agree that any testing that we do will be against the OSM dev server - https://api06.dev.openstreetmap.org

**Comment by mmd-osm** [comment]
Recently I tested this feature locally (the URL http://mapmeld.com/iD mentioned earlier doesn't seem to be up and running anymore). Overall, very impressed, so just adding a few comments:

* Approval/Reject feature looks pretty useful, even for other applications in the larger OSM ecosystem, like MapRoulette, or Sophox. You should probably also talk to @mvexel and @nyurik to see if this could be part of some broader adoption, beyond the scope of importing data from Geoservices. Are there any defined APIs for using tihs feature, or is it so tightly coupled with the rest making this real hard? It would be a shame to have such a cool feature and basically limit it to the ESRI world only.

* I noticed an increase of 20% in Javascript size after build process. A plugin concept would be a real blessing for iD, making the Geoservice part optional, and load on demand only (I hope I didn't miss anything here, please correct me if I'm wrong). Also, the number of additional dependencies on new libs adds a bit to that impression.

* Code base is fairly large, adding quite some technical debt to the project. Can you maybe outline in a few words, how the support/bug fixing process will look like? Do you plan running a separate bug tracker for it?

**Comment by jgravois** [comment]
thank you @mmd-osm!

> the URL http://mapmeld.com/iD mentioned earlier doesn't seem to be up and running anymore). 

thats really strange. its running when i visit the page.
screenshot 2018-04-08 18 00 39

> is it so tightly coupled with the rest making this real hard? It would be a shame to have such a cool feature and basically limit it to the ESRI world only.

Not at all, the proposed implementation extends the current generic editing logic, adding an `approvedForEdit` flag to OSM entities that other libs could also take advantage of.

> You should probably also talk to @mvexel and @nyurik to see if this could be part of some broader adoption.

That'd be great. it was intentional on our part to design the code to fetch GeoJSON from Esri services to maximize its _reusability_.

> Can you maybe outline in a few words, how the support/bug fixing process will look like?

We plan on providing support through existing channels and using iD's existing bug tracker. This is how we've tackled the addition of Esri World Imagery and it has worked quite well so far.

https://github.com/openstreetmap/iD/pulls?q=is%3Apr+sort%3Aupdated-desc+author%3Ajgravois+is%3Aclosed

**Comment by mmd-osm** [comment]
Thanks a lot for your feedback!

> thats really strange. its running when i visit the page.

I'm consistently seeing the following Javascript error on different machines: loading failed for <script> from origin: http://dnn506yrbagrg.cloudfront.net/pages/scripts/0013/6714.js

**Comment by mapmeld** [comment]
@mmd-osm I've fixed the locales issue, should be in your language now 👍

**Comment by bhousel** [comment]
I'm looking into this now, I'd love to get this merged.  I reviewed the code a bit today and it looks pretty good and there is not much I would change about it  😁 I also really appreciate that you kept it updated throught the last few iD releases.

The things that stand out to me initially are:

* I have to double check what it is doing with `source` tags, because at first glance, it looks like this would make them readonly all the time, and we should probably adjust this behavior.   Maybe we can just make them readonly on certain things.

* I like that it uses the `import_discussion` changeset tag.  This is also the part of the code that adds the `source` tag.  If you're not too attached to the specific tags, maybe we could make up new tags to keep things organized, like `import:discussion` and `import:source`,  (and I suppose it should also set `import=yes`, which is a common practice).

* The bundle size got a little bit bigger, but this isn't a deal breaker.  It looks like the size of `iD.js.min` grew from about 4.1 MB to 4.7 MB.  This is almost totally because of the `turf-buffer` dependency.  I'm going to look into ways to improve this, but again, I dont see it as a very big deal.

Thanks again for this and I'm going to let you know if I have any other questions as I start using it!

**Comment by mapmeld** [comment]
@bhousel ```turf-buffer``` is used only for an association of two lines (for example, a road and an imported bike lane).  If it's a significant add to the size, I could see making that more flexible or finding a different approach to comparing the overlap of two lines

**Comment by bhousel** [comment]
I got a chance to play around with this today.  Just want to say there is _so much_ potential for this feature.  I'm really excited to pick this up and run with it!

Here are all the street lamps around Montclair State University.. The open data portal is pretty great.
(Don't worry, I'm not going to import them right now 😆)

screenshot 2018-04-26 21 02 54

Right now it's a bit rough but it's a great start..  @jgravois and @mapmeld are you ok if I just start changing things?  I want to make this much more friendly to use and refactor some of the code a bit - move all the api and data processing stuff into a dedicated place under `services/` and add tests, etc.

**Comment by jgravois** [comment]
> are you ok if I just start changing things?

its certainly okay with me! i opened https://github.com/mapmeld/iD/pull/69 yesterday to get our branch in sync w/ `master` yesterday. i doubt if @mapmeld will have any reservations, but he can let everyone know for sure when he reviews that PR.

**Comment by mapmeld** [comment]
@bhousel that would be great if you want to take a look at it and make changes
(I've just applied @jgravois 's sync to iD current master branch)

**Comment by talllguy** [comment]
What does the "Add data to roads" checkbox do?
image
Consider an ℹ️ info hover there.

**Comment by bhousel** [comment]
> What does the "Add data to roads" checkbox do?

I'm not really sure, but I'm planning to go over the entire UI and make sure everything is really easy for a novice to understand.  This will probably involve breaking up the single screen into a several step [wizard](https://uxplanet.org/wizard-design-pattern-8c86e14f2a38).

**Comment by mapmeld** [comment]
@bhousel @tallguy that checkbox is the feature which I mentioned in an earlier comment:

> ```turf-buffer``` is used only for an association of two lines (for example, a road and an imported bike lane).

So it draws a buffer around imported data and visible roads, and tries to add attributes to an existing road.

**Comment by talllguy** [comment]
@mapmeld That is very cool! Import attributes by buffer could be a great way to get road attributes like speed limit or lane count into OSM. Governments usually have that in centerline format.

Come to think of it, I wonder if you could move the road to match the imported centerline, preserving the OSM tags. It would be great for correcting road alignments with good GIS data.

**Comment by tordans** [comment]
This feature will now be more useful than ever:
https://twitter.com/OpenStreetMapUS/status/1012454378685464578
> We're excited to see that the @bingmaps team has released 125 million (!) building polygons for our community to add to the map! Check out their announcement: https://buff.ly/2KeWdyS Tweet übersetzen

**Comment by jgravois** [comment]
looks like @bhousel has pushed a handful of commits with improvements of his own back in April.

what remains on the to do list?

if there's anything you can delegate back to @mapmeld and i, i'd **love** to get this feature landed ✈️.

**Comment by systemed** [comment]
A quick [hup](http://www.groggs.group.cam.ac.uk/jargon.html): any news on this one? I'm working with @OxfordshireCountyCouncil on an OSM-based conflation project and it'd be great to suggest people use iD (even if an externally hosted instance) rather than having to faff with JOSM.

**Comment by bhousel** [comment]
> A quick [hup](http://www.groggs.group.cam.ac.uk/jargon.html): any news on this one? I'm working with @OxfordshireCountyCouncil on an OSM-based conflation project and it'd be great to suggest people use iD (even if an externally hosted instance) rather than having to faff with JOSM.

Sorry, @systemed nothing yet!  Our goals for this year are tackling validation first and then building an amazing version of this next.

In the meantime you can try out @mapmeld's fork here:  https://github.com/mapmeld/iD

**Comment by ajturner** [comment]
@bhousel I see that validation is about to be merged. Yay.

What can we do to accelerate this acceptance? It’s been quite awhile and the next steps are unclear. You mention “building an a amazing version of this” which implies it will be reimplemented. Can you provide some specifics about the plans?

**Comment by iandees** [comment]
Hey @ajturner, I just wanted to point out that wasn't a very friendly way to phrase your question. The "Yay." comes off as pretty sarcastic and frames an otherwise decent question about the status of this PR in a bad light.

**Comment by nyurik** [comment]
> Hey @ajturner, I just wanted to point out that wasn't a very friendly way to phrase your question. The "Yay." comes off as pretty sarcastic and frames an otherwise decent question about the status of this PR in a bad light.

[Assume good faith](https://en.wikipedia.org/wiki/Wikipedia:Assume_good_faith) ;)
some people are not fluent English speakers, and might miss that nuance (I did).

**Comment by jgravois** [comment]
sorry @iandees. I understand what you mean. I've talked to @ajturner though and I _know_ that no sarcasm was intended.

we're excited about the new validation tools and the prospect of moving this feature forward too.

**Comment by slibby** [comment]
Is there a possibility of merging the existing code behind a feature flag so that it could be used by those who know about it and have been trained, but doesn't appear for all of the users of iD? That would let us then move forward with improvements without this PR hanging out there.

**Comment by bhousel** [comment]
Hey @ajturner, @jgravois, @slibby .. 

A few weeks ago I said [on Twitter](https://twitter.com/bhousel/status/1089178593228406785?s=21) that “people will soon be able to import data into @openstreetmap just as easily as they are currently able to trace it from aerial imagery.” and I mean it.. Your PR lays the groundwork to make this ambitious goal a reality, and I am very grateful for the work that your team has done. 

Bringing in data from external services is an idea that makes people in OSM uncomfortable, which is why we decided that stronger validation capability in iD was our first priority.  @quincylvania and others made that a reality and released the initial version of it this week in v2.14. 

When I return from vacation, work on the import tool will be a top priority, and it should ship in the next few months.

**Comment by jgravois** [comment]
I closed this one out because I'm no longer at Esri and it didn't seem like there was much hope of it landing.

whether that is the case or not, we'd love to keep the discussion alive. if there'd be any benefit to re-opening, just say the word.

**Comment by talllguy** [comment]
Where to next @jgravois ?

**Comment by jgravois** [comment]
> Where to next @jgravois ?

🤷‍♂. the folks from RapiD expressed some interest in collaborating on twitter ([ref](https://twitter.com/dongleflop/status/1215270192806350849)), but I'm not longer 'in the loop', as they say.

**Comment by Bonkles** [comment]
RapiD person here- our plans are still in the incubation phase, but we're definitely keeping an eye on this PR (as you can see!) and considering taking parts of it into the work we're doing.

**Pull request closed without merging**
