### PR TITLE
Add hotkey for Visual Diffs 

### PR DESCRIPTION
**Pull request by Bonkles**
This PR adds a new toggle hotkey (g) that highlights all unsaved edits on the screen.

Short video narrated by yours truly: 
https://www.youtube.com/watch?v=Vo4q4D_Uo4o

It has support for lines, vertices, and areas, and when the 'G' key is pressed, green accent is drawn over/in the features in question.  Generally tag edit highlights are lighter /lower opacity than geometry changes. 

Light green denotes a tagging-only change, darker green indicates a geometry change. 
Geometry changes supersede tagging changes, so if both are true for a particular entity, the geometry style will prevail. 

image

highlight_edits_PR_1
highlight_edits_PR_2

I'm interested in feedback on the visual styles I employed to communicate the diff information as well as the color choice!

### CODE REVIEW

**Comment by bhousel** [comment]
haha cool.. I love this, and can't wait to try it out 👍

**Comment by quincylvania** [comment]
@Bonkles Thanks so much for this feature! It looks pretty good so I'm just merging as-is. I will tweak it somewhat but I just wanted to get it in there first 👍

**Comment by quincylvania** [comment]
So I iterated on the original design somewhat:

- Include standalone points
- Render the diff as a halo behind the features
- Render line and area diffs the same way
- Green for added, yellow for tag-only changes, orange for geometry changes

Screen Shot 2019-10-08 at 9 05 00 PM

I think the results are good enough for now but I'm open to feedback and ideas!

**Comment by quincylvania** [comment]
I added a toggle button for this in the Map Data pane. This should make the feature more discoverable, escapable, and mobile-friendly.

Screen Shot 2019-10-10 at 12 39 05 PM

**Pull request merged**
