### PR TITLE
added diaper to amenity=toilets

### PR DESCRIPTION
**Pull request by morray**
http://wiki.openstreetmap.org/wiki/Key%3Adiaper
http://wiki.openstreetmap.org/wiki/Tag:amenity%3Dtoilets

### CODE REVIEW

**Comment by bhousel** [comment]
Thanks, this looks good!

Can you change the label to "Diaper Changing Available"  (we tend to Proper Case the field labels).
Then run `make` and commit the changes to the generated files?

**Comment by morray** [comment]
Hi bhousel, OK changed the case. For you second coment: is there an easy way to do this from within github, or do I have to setup a build system?

**Comment by bhousel** [comment]
Need a build system to run `make`, but that's ok, I'll take care of that step for you later when I'm back at my computer. 

Thanks again!

**Comment by morray** [comment]
Thanks. Over the Christmas  holidays I only have my windows-notebook on me and there it's really a pain to set this up ;-).

**Comment by bkil** [comment]
There is an ongoing proposal to enhance tagging of baby changing tables. Please share with whoever may be concerned and feel free to comment:
https://wiki.openstreetmap.org/wiki/Proposed_features/baby_changing_tables

**Pull request merged**
