### PR TITLE
Add requesting review

### PR DESCRIPTION
**Pull request by kepta**
This adds review request.

### CODE REVIEW

**Comment by pnorman** [comment]
It'd be good to sort the tagging out with the community, not on the iD issue tracker.

**Comment by bhousel** [comment]
> It'd be good to sort the tagging out with the community, not on the iD issue tracker.

Why?  My feeling has always been that:
1. The iD issue tracker is part of the community.  It's open, and anybody who wants can follow what we do or comment or suggest changes.
2. Changeset tags are really more decided by the editor software than by anybody else.
3. We can use [any tags we like](https://wiki.openstreetmap.org/wiki/Any_tags_you_like).

I am really happy to change the tag, if anybody cares.  It doesn't have to be `review_requested=yes`.

**Comment by iandees** [comment]
I realize I could check this out and look, but what are y'all thinking about for prompting the user to ask for review? A popup? A checkbox near the changeset save button?

**Comment by bhousel** [comment]
This request review field is great and I could merge it right now, but instead I'm going to spend some time to refactor the commit pane a little bit - it is like 500 lines of code and getting difficult to manage as we add things to it.  

Managing a bunch of fields and the tags that they change is something that `uiEntityEditor` and `uiPresetEditor` already do well, so I'm going to use that as a model to split `uiCommit` into smaller modules.

@iandees, here's a screenshot showing current placement of the checkbox, along with some dummy fields that I stuck at the top.  The dummy fields are being rendered by the new `uiChangesetEditor` component.

screenshot 2017-08-11 17 29 02

**Comment by bhousel** [comment]
Refactoring the commit pane by using the new `uiChangesetEditor` module is working nicely.  It now creates real `uiField` objects and supports a "more fields" section.  We can let users tag a `source` now.  Here are some things that I need to put back:

- [ ] dropdown for previous changesets
- [ ] placeholder texts
- [ ] google warning
- [ ] enable save button when comment exists
- [ ] double check the warnings and summary sections of `uiCommit`

and some scope creep..

- [ ] #2834 - add hashtags
- [ ] #4230 - <kbd>esc</kbd> should cancel save mode
- [ ] #3968 - few more changeset tags.. `first_edit`, `completed_walkthrough`, others?

**Comment by bhousel** [comment]
Looks like this currently

save mode

**Comment by iandees** [comment]
It would be great to think of a way to call out that "request review" checkbox, especially for new folks. Can it pulsate or be a different color or have an arrow with a friendly [globe](https://mapzen-assets.s3.amazonaws.com/images/introducing-tangram-work/globey.png) suggesting they give it a try?

**Comment by bhousel** [comment]
> It would be great to think of a way to call out that "request review" checkbox, especially for new folks. Can it pulsate or be a different color or have an arrow with a friendly globe suggesting they give it a try?

I have thoughts on this request review checkbox and how it might be perceived by different kinds of users.

Not everybody _wants_ feedback on their edits.  For example, millennials may be more likely to want the feedback, and genx'ers may be more likely to not want the feedback. Majority users may be more comfortable with public edits, and minorities may not feel comfortable having their edits under additional scrutiny.

I think this feature could be very helpful and welcome to a lot of people - especially new users - but I don't want to put assumptions into the software, and so that's why we ask the user whether they want the review or not.

Also at this point we don't know how many people will check the box, or who will step up to do the reviews.  The answer is some combination of - OSMCha, whodidit, bots, rss feeds, dedicated validators, paid mapping teams, and volunteers.

I thought about just checking the box if it's a user's first edit, or having the preference be "sticky", but I don't want to promise something the OSM community can't deliver.  So for now, let's leave the box unchecked, and "opt-in" to review.  We can change this later and encourage more users to check the box, if after a few months we decide that the reviews are working well and helpful.

**Comment by mvexel** [comment]
Agree with @bhousel -- until we know how many requests will actually be honored it's probably better to not call it out too much. If people don't want to review or use discouraging words to do so it would just serve to turn more people off than the other way around.

**Comment by talllguy** [comment]
Here's an idea for frequently used sources as checks, streamlining taginfo a bit 
image

**Comment by bhousel** [comment]
Hey @talllguy, one benefit of the recent refactoring work is that it makes it super easy to just reuse fields like the ones that iD already has other places.  We don't have a field that's an array-of-checkboxes, but we do have a multiselect field that turns the values into a semicolon separated list.

What do you think of this?:

sources

**Comment by talllguy** [comment]
@bhousel I like to see this fields reused this way. This implementation looks cool! I'd use this.

Next steps would be using some an algorithm to analyze the changeset comment and other metadata to suggest source tags. ;)

**Comment by bhousel** [comment]
FYI just pushed a working implementation of hashtags (see #2834).
This is just another semicolon-delimited multiselect field, and I added some extra code to detect hashtags embedded in the comment.

The idea here is to give mapathons, task managers, QA tools, a special field to store their hashtags, instead of (ab)using the comment field, which some people don't like.  Hashtags will also be settable through the API just like comments currently are.

hashtags

**Comment by bhousel** [comment]
Just merged this - thanks for your patience!
Hope these new features will make it easier for other projects to analyze changesets.

**Pull request merged**
