### PR TITLE
StreetSide Integration

### PR DESCRIPTION
**Pull request by jharpster**
Integrates the Microsoft StreetSide imagery in to the iD editor. 
You're welcome.

-Microsoft

### CODE REVIEW

**Comment by pnorman** [comment]
You can't use StreetSide for remote mapping without some other source, a difference from imagery, Mapillary, and OpenStreetCam. How can we make that difference clear to users so they don't break the StreetSide license?

**Comment by jharpster** [comment]
@pnorman We will clarify these terms for you shortly.

**Comment by bhousel** [comment]
Awesome @jharpster - this is a really great start, and this will be huge for OSM.  Thank you!

A few things I'm going to work on, to try to make this even better:

- [x] The pannellum instantiation code was running on every click, causing it to make a new viewer and canvas.  I split this up so that it only happens one time and reuses it each other time
- [ ] I'm going to try to assemble linestrings from the bubble data so that we can render the line go through them, and also show coverage at low zoom. 
- [ ] I'm going to try to add the viewfield showing where the user happens to be looking.  We can get this data from the pannellum viewer itself, and also bind an event so that as the user moves around, the viewfield can adjust. 
- [ ] I turned the compass in the viewer on, but it seems to be not quite oriented correctly. I have to figure this out too.

screenshot 2018-05-28 13 03 45

**Comment by nbolten** [comment]
This is exciting! Is there a public posting somewhere about how to use this when mapping? I'm still unsure about how to use it only as corroborating information, as per the terms of use.

**Comment by jharpster** [comment]
**Question 1:**
<br>
_“The ToU states that the use is limited  to  "non-commercial online editor application"(s). The original letter has similar wording. In any case it would be good to have a clarification on "non-commercial": is this intended to apply to both offering editing as a service contingent on having an account/contract and products that need to be purchased. For example does it exclude the iD instance run by Strava and the SketchUp plugin for OSM that has recently become available, or is the intent something else?”_<br>
<br>
 
**Microsoft’s Answer:**
<br>
Microsoft considers an iD/JOSM or other open source OSM editor run by a commercial company for the sole purpose of contributing to OSM to be non-commercial use. Any software available for purchase, even in a free tier, that features Streetside imagery integration would be a commercial use, and integrating Streetside imagery into such software would not be allowed.  A partner seeking to integrate Streetside imagery in to a commercial product should enter in to a commercial licensing arrangement with Microsoft.

**Comment by jharpster** [comment]
**Question 2:**
"online": is the intent to limit the availability to browser embedded editors (the would exclude at least JOSM, Vespucci and  Merkaartor), or is the intent to not allow caching of the imagery (which would again would exclude at least those three editors, but could be avoided with special casing),  or, again, is the intent something else?”
 
**Microsoft’s Answer:**
The word “online” is not intended to exclude the use of desktop OSM editors.

**Comment by jharpster** [comment]
**Question 3:**
“What are the intents behind the restriction of only letting it be used as a "corroborating ground truth" source? This is substantially different from Bing imagery, which is routinely used by mapping parties where there aren't other sources to confirm. With these terms, editing software will have to be very careful to describe how StreetSide can be used to make sure someone doesn't map solely from it.”
<br>
**Microsoft’s Answer:**
Microsoft’s intent for incorporating Streetside imagery in to OSM editing environments is that it be used as an additional corroborating source of ground truth for validating, updating and creating contributor edits to OSM. There is no place where Streetside imagery exists and corroborating sources (Digital Globe Premium, Esri World Imagery, Mapbox Satellite, Bing Imagery, etc), do not also exist. 
Clarifying Sample scenarios:

1. An OSM Contributor traces a sidewalk on top of Bing imagery using the iD editor. The sidewalk is partially obscured by trees in the imagery so to improve the spatial accuracy the Contributor refers to Streeside for verification.   This is a valid use of the Streetside imagery

2. Contributor 1 uses Esri World Imagery to trace a road and adds a tag surface=paved. Contributor 2 refers to the Streetside imagery and verifies that the road is actually bricks and updates the tag to surface=paving_stones. This is a valid use of the Streetside imagery

3. An OSM Contributor is updating their local neighborhood referring to Bing Imagery and realizes there are a number of stop signs missing from OSM that are clearly visible in the Streetside imagery. The Contributor updates OSM with additional highway=stop nodes. This is a valid use of the Streetside imagery

4.  An OSM contributor builds a computer vision algorithm that iterates over the Streetside imagery attempting to harvest residential addresses. This is an invalid use of Streetside imagery.

**Comment by SK53** [comment]
@jharpster These examples are very good and helpful. 

Can I just test a few of other scenarios which I have been contemplating?

(Streetview coverage in UK is limited but covers my mother's home town, which I know well, but don't visit very frequently):

1. Use Streetside to identify the correct position of a POI identified by open data (i.e., without a direct ground survey). 

In the UK we have a number of good open sources of data which are only geolocated down to the postcode level: notably Food Hygiene data and Companies House (company registrations). Food Hygiene is particularly good because it is updated regularly. The key feature of both datasets is that they provide high-quality address data, and for shops, restaurants & cafes are also visible POIs. So from this data it is possible to identify that a cafe with housenumber 123 is present (typically perhaps with an accuracy of 50 m). If the same cafe is visible on Streetside it then becomes possible to place it more accurately (at the individual building level). In practice I would probably only want to map the address as the POI may have closed/changed both since Streetside imagery and the last snapshot in other open data sources.  Example location: https://binged.it/2t06swf (address is 228 Rake Lane on Food Hygiene: http://ratings.food.gov.uk/business/en-GB/394560/Gills-the-Family-Store-Wirral)

2. Use Streetside to determine the exact bounds of a retail area or other landuse. It is often possible to identify groups of shops from aerial imagery (taller buildings, service yards, parking on the sidewalk), but the actual extent of the retail area may be more extensive with less obvious buildings. Also in some areas former retail areas are getting converted to housing. Example location https://binged.it/2LSxUmI (note the awnings from when this was a large thriving retail location). 

3. If when using Streetside for confirmation of other information I notice an unmapped post box or similar POI is it permissible to add it to OSM? If not directly allowed, can the knowledge gained from Streetside be then used to search other allowable imagery sources (e.g., Mapillary, Geograph)? Example location: https://binged.it/2LTyXmm.

3a. Related directly to the above location. Streetside would be a good source for dropped kcerbs & tactile paving which is often difficult to identify from aerial imagery or other sources. Such usage would clearly be beyond confirmatory. 

4. I note that a branch of a convenience store is present at a particular location from Food Hygiene open data. Aerial imagery shows a particular building which is highly likely to be the location. Can I use Streetside to confirm this supposition? Example location: https://binged.it/2HQ33or 

Sorry for being rather long-winded, but I hope these examples are concrete enough to enable clear guidance.

**Comment by erkinalp** [comment]
> An OSM contributor builds a computer vision algorithm that iterates over the Streetside imagery attempting to harvest residential addresses. This is an invalid use of Streetside imagery.

@SteveC

**Comment by Zverik** [comment]
@jharpster 

> An OSM contributor builds a computer vision algorithm that iterates over the Streetside imagery attempting to harvest residential addresses. This is an invalid use of Streetside imagery.

That is exactly what [Mapbox did](https://www.openstreetmap.org/user/virginiayung/diary/44171) recently. Does that mean that it is invalid use only when Microsoft hasn't been contacted beforehand?

**Comment by SK53** [comment]
@Zverik I  assume from this quote that they did "We generated these turn restriction detections by applying our machine learning computer vision models to Microsoft Streetside Imagery, from which Mapbox has **acquired the right** to contribute these detections to OpenStreetMap." (my emphasis)

**Comment by jharpster** [comment]
@Zverik @SK53 Running computer vision algorithms over the 4.7PB imagery catalog generates significant load on MS infrastructure. Supporting that requires a contractual relationship.

**Comment by pnorman** [comment]
> An OSM contributor builds a computer vision algorithm that iterates over the Streetside imagery attempting to harvest residential addresses. This is an invalid use of Streetside imagery.

Presumably if they used another source of information like aerial imagery to identify buildings they would then be okay, as Streetside is no longer a sole source of ground truth?

**Comment by xuiqzy** [comment]
@jharpster Could you please comment on the common potential use cases mentioned by SK53? :)

**Pull request merged**
