### PR TITLE
Eliminate vendored sexagesimal library

### PR DESCRIPTION
**Pull request by bhousel**
Starting to remove the vendored libraries in js/lib and replace them with modules installed via npm..
Sexagesimal is a simple one to start with - how did I do?  

cc @tmcw @kepta  
re: #3180

### CODE REVIEW

**Comment by tmcw** [comment]
LGTM! As iD starts using modules, we'll need to come to an approach for semver ranges - the new default is the ^ range, this PR uses ~. My gut feeling is shifting towards _no semver specifiers at all_ since semver-automatic upgrading is rarely desired and incidental automatic upgrades are rarely bulletproof.

**Comment by bhousel** [comment]
Good point about semver ranges.   I agree I'd rather not use them at all, because I don't like surprises.

@tmcw can I drop all the range specifiers and set up [Greenkeeper](https://greenkeeper.io/)?

**Comment by tmcw** [comment]
👍 sounds like a plan. I haven't used Greenkeeper before, interested to hear how it goes.

**Comment by kepta** [comment]
Green keeper looks awesome ✌

**Pull request merged**
