### PR TITLE
add preset for route=horse relations

### LINKED ISSUE #3057: add preset for route=horse relations
Please add a preset for route=horse relations (Riding Routes = Reitrouten),
analogous to route=hiking (closed/merged issue https://github.com/openstreetmap/iD/pull/1785)-
The only difference seems to be that you need a new icon.
There are also different network values (ihn, nhn, rhn and lhn) 
but this does not seem to be interesting to iD.

(Riding Routes were recently also added to JOSM,
see https://josm.openstreetmap.de/changeset/10086/josm
and https://josm.openstreetmap.de/changeset/10090/josm)

### PR DESCRIPTION
**Pull request by kepta**
I am not sure if it should be called `Riding route` or `Horse route`
(closes #3057)

### CODE REVIEW

**Comment by bhousel** [comment]
"Bridle route"

**Comment by Hufkratzer** [comment]
Please call it "Riding route" to be consistent with JOSM
(https://josm.openstreetmap.de/browser/josm/trunk/data/defaultpresets.xml?rev=10086#L9901)
and the OSM wiki
(https://wiki.openstreetmap.org/wiki/Riding#Riding_routes)
("Bridle Route" I couldn't find in the wiki.)

German translation is: "Reitroute"
(http://wiki.openstreetmap.org/wiki/DE:Riding#Reitrouten)

**Comment by bhousel** [comment]
> Please call it "Riding route" to be consistent with JOSM

ok, "Riding route" is fine.

**Comment by Hufkratzer** [comment]
Do I have to do something to produce the necessary icon? Do I have to open an issue on
https://github.com/mapbox/maki/issues ?
The icon cannot be very complicated to create because it is just a combination of two others that already exist:
icon-riding
But I can't find the other icons on the maki site either.

**Comment by bhousel** [comment]
merged as 
2ed9b19 2016-05-08 Add style and route-horse icon, rename per #3066 <Bryan Housel>
cdfe243 2016-05-08 add preset for route=horse relations <Kushan Joshi>
7bff5d3 2016-05-08 Add route-horse icon <Bryan Housel>

**Pull request closed without merging**
