### PR TITLE
Add military presets (fixes #2177)

### LINKED ISSUE #2177: Military Presets: Analysis and Proposals
Firstly, please add **Military** landuse, i.e. `landuse=military` as a preset. This [tag maps the area of a military use](http://wiki.openstreetmap.org/wiki/Tag:landuse%3Dmilitary), e.g. base, or proving ground. On the wiki, it also mentions users can add the `military=*` key, for further detail. Interestingly some of these already have presets in iD alone. In the list below, bold keys are in iD already as presets:  
* [`miltary=airfield`](http://wiki.openstreetmap.org/wiki/Tag:military%3Dairfield)
* **[`military=bunker`](http://wiki.openstreetmap.org/wiki/Tag:military%3Dbunker)** :small_red_triangle:
* [`military=checkpoint`](http://wiki.openstreetmap.org/wiki/Tag:military%3Dcheckpoint) :small_red_triangle:
* [`military=danger_area`](http://wiki.openstreetmap.org/wiki/Tag:military%3Ddanger_area)
* [`military=naval_base`](http://wiki.openstreetmap.org/wiki/Tag:military%3Dnaval_base)
* [`military=obstacle_course`](http://wiki.openstreetmap.org/wiki/Tag:military%3Dobstacle_course)
* **[`military=range`](http://wiki.openstreetmap.org/wiki/Tag:military%3Drange)** :small_blue_diamond:
* [`military=training_area`](http://wiki.openstreetmap.org/wiki/Tag:military%3Dtraining_area)

*Notes: :small_red_triangle: indicates tags that usually wouldn't be appropriate as sub tags for the `landuse=military`.
:small_blue_diamond: = `military=range` preset name is* Military Range, *so that is what comes up in search for "military".*

Secondly, I propose that all those `military=*` tags be added to iD as an optional type to the `landuse=military` preset, with the exception of the ones with the :small_red_triangle:. I will leave it up to the iD community to decide if each of them needs its own preset independently. Could that be confusing?

Thirdly, I propose that the synonym terms for this preset would include common things people call military land, such as: base, army base, navy base, naval base, air force base, proving ground, national guard base, national guard depot, etc. It might also make sense to include some countries' militaries' official names in there.

Thoughts welcome. Thank you!

### PR DESCRIPTION
**Pull request by arunasank**
Fix bug #2177 by adding military presets.

I hope I have changed the necessary files.

### CODE REVIEW

**Comment by bhousel** [comment]
Thanks @arunasank!   You should add these presets as new .json files to the `/data/presets/presets/military` folder, then run `make` to regenerate the other files.

Then as a test, [run iD locally](https://github.com/openstreetmap/iD/blob/master/README.md#installation) and try to use the new presets.

**Comment by arunasank** [comment]
Fixed it @bhousel.

I force pushed to master though. Will that be a problem?

**Comment by bhousel** [comment]
> I force pushed to master though. Will that be a problem?

Hehe you scared me!   You force pushed to your own master, so not a problem.

**Comment by arunasank** [comment]
:)

Any chance my PR can get merged soon @bhousel?

**Comment by bhousel** [comment]
Looks good, thanks @arunasank!

**Comment by talllguy** [comment]
Thanks for getting around to this @arunasank !

**Pull request merged**
