### PR TITLE
Add Chinese(PRC) address format

### PR DESCRIPTION
**Pull request by Stenive**
We write provinces and cities first :)

### CODE REVIEW

**Comment by bhousel** [comment]
Great thank you!

After this merges, wait about 10 minutes and check http://preview.ideditor.com/master/ to see if it worked. 

When you test it, can you also verify if the addresses in the walkthrough are localized completely and have all the needed address parts.  If there are parts missing, they can be added on https://www.transifex.com/ideditor/id-editor/dashboard/ - let me know and I can help with this!

**Comment by Stenive** [comment]
Localization is fully completed, including the 'address' field in the walkthrough.

**Comment by Stenive** [comment]
Localization is fully completed, including the 'address' field in the walkthrough.

**Comment by bhousel** [comment]
Thank you @Stenive! 🙇

**Pull request merged**
