### PR TITLE
lodash version bump

### PR DESCRIPTION
**Pull request by kepta**

### CODE REVIEW

**Comment by bhousel** [comment]
you forgot a few steps! 😆 

```bash
01:14 $ make lodash
node_modules/.bin/lodash --development --output js/lib/lodash.js include="any,assign,bind,chunk,clone,compact,contains,debounce,difference,each,every,extend,filter,find,first,forEach,forOwn,groupBy,indexOf,intersection,isEmpty,isEqual,isFunction,keys,last,map,omit,pairs,pluck,reject,some,throttle,union,uniq,unique,values,without,flatten,value,chain,cloneDeep,merge,pick,reduce" exports="global,node"

Invalid `include` entries passed: any, contains, pairs, pluck, unique
For more information type: lodash --help
make: *** [lodash] Error 1
```

**Comment by kepta** [comment]
omg, I was actually wondering I hope I am not missing anything. 
😬

**Comment by bhousel** [comment]
Several functions were renamed/removed, see [release notes](https://github.com/lodash/lodash/wiki/Changelog#v400)

**Comment by kepta** [comment]
@bhousel , if I am not wrong  `any, contains, pairs, pluck, unique` these functions need to be replaced by something the v4 offers.

Am I correct?

**Comment by bhousel** [comment]
> Am I correct?

yep, you got it..  It probably takes this from being a 5 minute change to a few hours of of find/replace throughout the code.

**Comment by kepta** [comment]
I know, and then finally the mysterious performance bump. 
I wonder if the new functions reduce the number of lines of code 🤔.

**Comment by kepta** [comment]
It wasn't as easy as I thought it would be.
I hope there are no bugs lurking around.
@bhousel have a look.

**Comment by bhousel** [comment]
LGTM.. I spent a while editing with it and it seems good.  Go ahead and merge it.. 🚢

**Pull request merged**
