### PR TITLE
Straighten multiple ways in one operation

### PR DESCRIPTION
**Pull request by jguthrie100**
Implements aspects of #2058 (multiple way straightening)

This change allows the user to select a number of joined ways and straighten them all in one operation.

- I've written a number of additional tests to cover some of the new scenarios

straighten

### CODE REVIEW

**Comment by jguthrie100** [comment]
One thing to consider - should joined ways that go in opposite directions be able to be straightened together.
My changes only allow ways that go in the same direction to be straightened, but I could change it to allow for direction to not be an issue..

**Comment by bhousel** [comment]
> Implements aspects of #2058 (multiple way straightening)

Nice, I'll have to check this a bit more thoroughly later this week 👍 

> One thing to consider - should joined ways that go in opposite directions be able to be straightened together.
> My changes only allow ways that go in the same direction to be straightened, but I could change it to allow for direction to not be an issue..

Sure - I don't think the direction matters.

**Comment by jguthrie100** [comment]
Fixed it so that connected ways going in different directions can be straightened

straighten-multiple-directions

Apologies for the commit-history chaos!

**Comment by bhousel** [comment]
Thanks @jguthrie100 , I just merged this..
(It doesn't show as merged on GitHub because I rebased it to avoid conflicts)

**Pull request closed without merging**
