### PR TITLE
Fixes issue #2504

### PR DESCRIPTION
**Pull request by harkirat96**
Instead of redirecting to new user login , it redirects to login page

### CODE REVIEW

**Comment by jfirebaugh** [comment]
Hi @harkirat96, thanks for contributing.

The correct place to make this change is [data/core.yaml](https://github.com/openstreetmap/iD/blob/master/data/core.yaml). `dist/locales/en.json` gets overwritten by the build script.

Also, you've checked in an editor backup file `dist/locales/en.json~`. Please add a rule to your global .gitignore so that these files are ignored.

**Comment by harkirat96** [comment]
@jfirebaugh:Made changes in core.yaml.Ignored en.json

**Comment by jfirebaugh** [comment]
There are even more editor backup files in this PR now. Can you try again with a clean PR?

**Comment by ashish0kumar** [comment]
> Instead of redirecting to new user login , it redirects to login page

Great things started here :)

**Pull request closed without merging**
