### PR TITLE
Add preset for amenity=language_school

### LINKED ISSUE #5245: Add preset for amenity=language_school
https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dlanguage_school

### PR DESCRIPTION
**Pull request by AndreasHae**
Fixes #5245

I had to omit the field for "language" for now, because I could not find a proper way to add it. I guess this functionality has yet to be implemented. If there is already a way, please let me know.

### CODE REVIEW

**Comment by vershwal** [comment]
`npm run build` as suggested [here](https://github.com/openstreetmap/iD/pull/5262#issuecomment-417609571).

**Comment by AndreasHae** [comment]
Sorry, I was busy in the last days. @bhousel thanks for taking a look. May I ask if you have some other issues for me to work on.. maybe something more Javascript-related/advanced?

**Comment by bhousel** [comment]
> I can add a multiselect field for languages, but it won't support the main/yes style of tagging.. just yes or nothing

btw I changed my mind about this part - the language field will support 'main' if people want to add it in the raw tag editor.  see #5291

**Comment by bhousel** [comment]
> Sorry, I was busy in the last days. @bhousel thanks for taking a look. May I ask if you have some other issues for me to work on.. maybe something more Javascript-related/advanced?

Thanks!  There are so many issues.. The "help wanted" ones are a good place to start, but don't limit yourself to that.  Maybe read through the whole list and see if anything sounds interesting?

**Pull request merged**
