### PR TITLE
Remove piste presets for now, as they are likely to delete highways

### PR DESCRIPTION
**Pull request by yvecai**
See #5398 
It seems safer to remove these presets for the time being, contributors being use to tag smaller highway=* with piste:type=* tags.

### CODE REVIEW

**Comment by bhousel** [comment]
> It seems safer to remove these presets for the time being, contributors being use to tag smaller highway=* with piste:type=* tags.

Really? If you remove them then even standalone pistes will not be recognized as pistes - this is probably not what you want.

**Comment by yvecai** [comment]
That's 4 chance out of 10 to delete a track, 60% for piste:type=nordic which is the majority of pistes mapped. 
No, I don't feel like to take the chance.

I hope it's not forever though, I may dig more into the code and also take some advice in the community.

**Comment by bhousel** [comment]
Look, I'm not going to do this.  It would remove even the downhill ski runs.  iD has had piste presets for like 5 years and people seem to be able to figure them out.  We render things so people don't get confused, and local communities are mostly good at watching for unintentional breakage.

Similarly, we aren't removing the tram presets just because we are worried someone might change a street into a tram.  Nobody does that.

**Comment by yvecai** [comment]
Bryan, I've figured this issue while writing a short tutorial to map with iD some nordic pistes the way it's done for maybe 10 years.
Look how it's easy too ... wait, where the track? 


My advice is to think of it for a while and not to hurry. I guess downhill pistes are less subject to follow highways, so the preset could be limited to downhill if this please you.


But we need to figure it out properly in the end.

I say this while I'm a nordic skier, and data consumer at opensnowmap.

**Pull request closed without merging**
