### PR TITLE
Add Taiwan (R.O.C.) address format

### PR DESCRIPTION
**Pull request by david082321**
Sorry. I forget a comma in #3260, so I pull request again.

### CODE REVIEW

**Comment by bhousel** [comment]
Thanks!  It looks like some of the `addr:` keys that you want to use aren't yet added to `address.json`.
Specifically, `addr:village` and `addr:floor` keys seem to be missing:

screenshot 2016-07-21 00 21 52

It might be correct, and I can add them if so, but I'd like to see if these keys are really used anywhere before we "standardize" the tagging of ROC addresses this way.  I did look around in the map but didn't see any tagged this way - all current examples I could find use `addr:city`, `addr:street`, `addr:housenumber`.

Are `addr:village` and `addr:floor` real tags being used?

**Comment by pnorman** [comment]
Both have low usage. `addr:floor` has worldwide usage and a wiki page, `addr:village` isn't documented and may overlap with `addr:city`. 25% of uses of addr:village are in one place.

I'd recommend against adding addr:village and asking a wider audience about addr:floor

**Comment by david082321** [comment]
you're right. 
addr:village is a hide option, only show in full address.
And it would not have same address when hide it.

**Comment by david082321** [comment]
OK! I've removed them.

**Comment by Supaplextw** [comment]
Yeal addr:floor is not well documented but it is use in urban area in Taiwan like Taipei. Maybe use key:level instead of addr:floor for shop or amenity in multilevels building.

**Comment by david082321** [comment]
BUT there are exception.

1.
addr:village
https://www.openstreetmap.org/node/2536763307
default

2.
addr:place
the road without street names
[http://overpass-turbo.eu/s/hpR](url)

3.
addr:floor
 to indicate different floors of the restaurant or company
[http://overpass-turbo.eu/s/hpU](url)

**Comment by Supaplextw** [comment]
Actually "乾華派出所" is not in "阿里荖",  "阿里荖" is the smaller place under the village. "阿里荖" should be place in the addr:place form.

**Comment by bhousel** [comment]
Looks like the latest version includes `addr:floor` and leaves off `addr:village` (which is not a standard documented tag).  This sounds fine to me.

**Comment by bhousel** [comment]
This look ok to everyone?

screenshot 2016-07-21 10 33 30
screenshot 2016-07-21 10 33 36

**Comment by david082321** [comment]
Yes, it's ok.

**Comment by Supaplextw** [comment]
Yes, @bhousel it's ok

**Comment by bhousel** [comment]
Just merged this, thanks everyone!

**Pull request merged**
