### PR TITLE
Live reload documentation

### PR DESCRIPTION
**Pull request by kepta**
I often use `live-server` while working on iD and thought it might be use for others as well.
Let me know if it is necessary 🙃

### CODE REVIEW

**Comment by kepta** [comment]
> can you change it to say "local" server page
I didn't quite get this part.

**Comment by bhousel** [comment]
Oh, it just says "locally server page", and "local server page" sounds a bit better.

**Comment by kepta** [comment]
Oh ya, let me fix that.

**Comment by kepta** [comment]
@bhousel the commit is updated.

**Comment by bhousel** [comment]
Thanks!

**Pull request merged**
