### PR TITLE
Add selected features to minimap

### PR DESCRIPTION
**Pull request by jguthrie100**
This is a work in progress for #5415 

It simply copies any selected features from the main map and replicates them on the minimap. The styles etc are all maintained (which will require some editing most likely as it can look a bit cumbersome, but that can all be fixed)

Multiple features can be selected and they'll all be replicated on the minimap without an issue.

Todo:
 - Modify styles so they are less intrusive
 - Add breathing (i.e. red pulsing on selected features) to minimap features (?)
 - Improve styling of Point markers (currently a plain red dot - maybe better if its a small black dot with breathe effect)
 - Improve relation/area selections (either a big red blob or a thin line atm)

Note that this doesn't fix the selection dropping when the selection is dragged off the screen. I'm looking into sorting that, but its not too easy!

image

### CODE REVIEW

**Comment by jguthrie100** [comment]
It might be worth gathering some suggestions for styling too, and whether the entire feature should be drawn, or whether it should just be a dot at the centre point of the feature for example.

**Comment by slhh** [comment]
I wouldn't use any halo or even breathing. 
The entire feature should be drawn, a centerpoint can be quite confusing. 
The width of the yellow line on the minimap seems to be fine.
Selected features can easily get overlapping on the minimap due to a different zoom levels. Therefore, do not use feature type specific styles.
I'd use four colors/styles:
1. Members of selected relations
2. Selected ways
3. Selected nodes
4. Selected features, which are hovered on the main map or on a sidebar list.

**Comment by bhousel** [comment]
Yes, along the lines of what @slhh said - I would avoid extensive map styling here too.  A simple stroke is enough to show it on the minimap.

I also noticed you're doing a lot of code to generate the GeoJSON that gets displayed.  Each of the entity types `node`, `way`, and `relation` has a `.asGeoJSON()` function.  So could you just do something like:

```js
var resolver = context.graph();
var features = context.selectedIDs()
    .map(context.entity)
    .map(function(entity) { return entity.asGeoJSON(resolver); });

var gj = { 
    type: 'FeatureCollection',
    features: features
};
...
```

**Comment by jguthrie100** [comment]
I've made some changes to the styling and taken out a lot of redundant code. I think the failing tests are completely unrelated to my changes, but not sure..

image

Again, could do with advice on styling/colour/stroke-width choices etc

**Comment by quincylvania** [comment]
> I think the failing tests are completely unrelated to my changes, but not sure..

@jguthrie100 We've been seeing some server-side tests fail lately due to timeouts, so as long as the local tests pass on http://localhost:8080/test/ then don't worry about it.

**Pull request closed without merging**
