### PR TITLE
Dynamic line previews in line preset icons

### LINKED ISSUE #5839: Line icons used on Area features look ugly
This happens when we use the wrong kind of icon on a feature.  

screenshot 2019-02-01 16 01 02

I'd like to fix this by getting rid of the "line" and "relation" icons.  We could just have normal icons, then add the line/relation graphic below the icon with code, only if we need to.

screenshot 2019-02-01 16 05 27

### PR DESCRIPTION
**Pull request by quincylvania**
Closes #5839. Re: #5873, #5882.

- Remove embedded line geometry from iD line feature icons
- Add dynamic line previews to all line preset icons
- Use the same stroke styling for line icons as when rendering the lines in the map
- Icon styling can be overridden. For example, the stroke/casing of cycle paths is reversed for the light background

This PR does not address embedded geometry in relation icons.

- [x] The `stroke-dasharray` could probably be improved for railways, ferry routes

Nicer icons when using line preset as areas:
screen shot 2019-02-13 at 4 17 07 pm

A selection of the new icons:
screen shot 2019-02-14 at 9 59 22 am
screen shot 2019-02-13 at 4 15 01 pm
screen shot 2019-02-13 at 4 14 53 pm
screen shot 2019-02-14 at 9 59 05 am
screen shot 2019-02-13 at 4 14 19 pm
screen shot 2019-02-13 at 4 14 09 pm
screen shot 2019-02-13 at 4 16 16 pm
screen shot 2019-02-13 at 4 15 32 pm
screen shot 2019-02-13 at 4 15 17 pm

### CODE REVIEW

**Comment by SilentSpike** [comment]
It sounds crazy and I've checked your maths (`10.5 + 6/2 = 13.5`), but I swear the vertices are slightly lower than the line 😆

**Comment by quincylvania** [comment]
> It sounds crazy and I've checked your maths (`10.5 + 6/2 = 13.5`), but I swear the vertices are slightly lower than the line 😆

@SilentSpike Are you seeing this in the images or live? Now I'm worried that certain browsers or screens don't like the partial-pixel alignment.

**Comment by SilentSpike** [comment]
@quincylvania I noticed it particularly in the residential road image, then checked a live instance and see the same. Took a screenshot and see a 1px difference:

discrep

**Comment by bhousel** [comment]
> @SilentSpike Are you seeing this in the images or live? Now I'm worried that certain browsers or screens don't like the partial-pixel alignment.

Maybe try -
- setting an explicit `viewBox=0 0 40 20` attribute on the svg.  (width and height should do the same thing, but I'm not 100% sure).
- changing `lineSvg`'s height from 20 to 19 or 21?  (you can open Chrome's dev tools and play with this value live)

Retina screens should handle the half pixel alignment ok - non retina screens would blur it.  Also SVG strokes are measured from the center of the stroke 

OH and I'd draw those vertices as svg circles, not rounded divs.  Actually that's probably the real issue and the lines are probably fine.

**Comment by quincylvania** [comment]
@bhousel Thanks for the tips! I implemented them and this should be ready for review.

@SilentSpike I changed the line casing in the icons to use full-pixel increments, which I think was the problem. Let me know if you're still seeing issues. I updated the railways screenshot so you can check that, or preferably on live.

**Comment by quincylvania** [comment]
@bhousel Thanks! I could do the relation ones but I'm not sure those unblock new features like this did for #5873. Feel free to create an issue.

**Comment by bhousel** [comment]
> @bhousel Thanks! I could do the relation ones but I'm not sure that would unblock new features like this did for #5873. Feel free to create an issue.

It seems kind of silly not to just do all of them at the same time.

**Pull request merged**
