### PR TITLE
building:color -> building:colour deprecation

### PR DESCRIPTION
**Pull request by matkoniecz**
https://taginfo.openstreetmap.org/keys/building%3Acolor

inspired by https://josm.openstreetmap.de/browser/josm/trunk/data/validator/deprecated.mapcss#L569

### CODE REVIEW

**Comment by matkoniecz** [comment]
note: how can I test this one? I want to be sure that it will remove old tag, not just add new one. I am assuming it will work based on very similar rules but I want to be sure.

**Comment by quincylvania** [comment]
> note: how can I test this one? I want to be sure that it will remove old tag, not just add new one. I am assuming it will work based on very similar rules but I want to be sure.

You can just create a feature and add the deprecated tag in the All Tags editor. The warning will appear and you can click a fix and inspect the results.

**Comment by bhousel** [comment]
It would be fantastic to have unit tests for every validator tho..

**Comment by matkoniecz** [comment]
Is there any that I can base it on? i would happily add based on similar ones but I am not going to invent way to test it.

**Comment by quincylvania** [comment]
@matkoniecz Thanks!

> Is there any that I can base it on? i would happily add based on similar ones but I am not going to invent way to test it.

We have https://github.com/openstreetmap/iD/blob/master/test/spec/validations/deprecated_tag.js. It just checks to make sure the tags are flagged. It doesn't even test the fix yet.

**Pull request merged**
