### PR TITLE
It is sculptor not sculpter

### PR DESCRIPTION
**Pull request by simonpoole**
I believe this is a fairly clear typo in the presets

### CODE REVIEW

**Comment by bhousel** [comment]
Thanks @simonpoole good catch!
I'm surprised it has been this way for so long.

Looks like there are 291 of `craft=sculpter` to be cleaned up..
https://taginfo.openstreetmap.org/search?q=craft%3Dsculpter

We should wait until the next iD release and then after the fix goes live, I'll change them.

**Comment by abdeldjalil09** [comment]
and also these tags : "craft=sweep" it should be "chimney_sweeper"

**Comment by simonpoole** [comment]
@abdeldjalil09 sweep is IMHO a legit short form

**Comment by abdeldjalil09** [comment]
see https://wiki.openstreetmap.org/wiki/Tag:craft%3Dchimney_sweeper

**Comment by bhousel** [comment]
> see https://wiki.openstreetmap.org/wiki/Tag:craft%3Dchimney_sweeper

Thanks @abdeldjalil09 I did not know that the tag had changed back in 2014 based on a brief discussion on the tagging@ list.  Please open a new issue.

**Comment by simonpoole** [comment]
In any case it is a wonderful example of, even if completely well intentioned, you shouldn't change tags without really good reasons. And if you do, just changing the wiki is not enough.

**Comment by abdeldjalil09** [comment]
>  Please open a new issue.
I'm going to do it.

**Pull request merged**
