### PR TITLE
feat: multi-select checkboxes added

### PR DESCRIPTION
**Pull request by draunger**
# Description
# Issue
https://github.com/openstreetmap/iD/issues/10465

## Before this PR
image

## After this PR
image

### CODE REVIEW

**Review by tyrasd — CHANGES_REQUESTED** [review]
I don't think simply highlighting the selected search result features is what the intention behind #10465 was. For example, can you explain how this would help with a use case like the following:

> I wanted to change the name of all the items I saw in that search result

**Comment by draunger** [comment]
@tyrasd I think it is beneficial if we want to show someone highlighted multiple things on the map from the search result..

**Comment by tyrasd** [comment]
What I don't understand is how this highlighting would be helpful for a particular mapping task?

**Comment by draunger** [comment]
@tyrasd ok sir I understand, I Mistankly understood this issue wrongly and makes this I am closing this PR

**Pull request closed without merging**
