### PR TITLE
Add missing 60 mph maxspeed option

### PR DESCRIPTION
**Pull request by boothym**

### CODE REVIEW

**Comment by boothym** [comment]
Whoops, not sure why the other change went in with this PR.

**Comment by bhousel** [comment]
Thanks!  merged as:

1c3a250 2016-08-01 Add missing 60 mph maxspeed option

**Comment by bhousel** [comment]
Yes I remember you were having trouble with [your last PR](https://github.com/openstreetmap/iD/pull/3286#issuecomment-235644081) too.. Your master branch has diverged from the main iD master branch.  There's not much you can do about it in the GitHub web interface other than delete and re-fork it.

If you install the git command line tools, it becomes a bit easier because you can `git reset --hard upstream/master` to sync things up.

**Comment by boothym** [comment]
Yeah, I had to deleted and refork it last time to get it working, and I'm now using github desktop.

I've managed to get my copy back in sync though via the command line. What's the best workflow to avoid these problems and to keep things simple? Thanks.

**Pull request closed without merging**
