### PR TITLE
[wip] D3 v4

### PR DESCRIPTION
**Pull request by tmcw**
TODO

* [x] Figure out what to do about d3.rebind deprecation
* [x] Initial map loading is in the wrong place
* [x] Data only loads in the way top left corner of the map
* [x] Fix tests
  * [x] Fix testing of lib (now included under iD.lib)
  * [x] Fix events in tests

Notes:

* Resource for changes: https://github.com/d3/d3/blob/master/CHANGES.md
* d3-zoom is very changed https://github.com/d3/d3-zoom and rather difficult to upgrade
* this now avoids all "throwing stuff onto the d3 object" patterns and instead exports independent functions and objects from add-ons.

Common changes:

* `style` no longer takes an object. change to styles and import d3-selection-multi.
* `transition` no longer does `.each('on', function`, instead do `.on('end'`
* selections are immutable; reassign if you want to reference selections after `enter()` calls
* `rebind` was removed and I added a backport. I'm not 100% it works yet.

### CODE REVIEW

**Comment by tmcw** [comment]
@bhousel any chance you'll get time to check out this branch? I know you're slammed with other work, but this branch is really the final push of the refactor: it totally eliminates non-modular dependencies and vastly simplifies the build step. Once this is in, we can move much faster with iD.

**Comment by bhousel** [comment]
@tmcw, @kepta 

It's September now and I've had it with this refactor.

Why do the source maps in the Chrome Dev tools not match up with actual code in the repository.

screenshot 2016-08-31 22 51 22

I can't fix issues with the D3 upgrade if I can't edit the code and rebuild iD in a reliable way.

If we can't get a basic development environment working in this branch in the next week, let's scrap this summer's work and return to the 1.9.7 branch.   I'm not willing to waste any more time fighting with tools. 

If you think it that what we have works, kindly spell out for me the steps that you are following to build everything and run tests..  Update the README too if you feel like making things easy for me.

Sorry for the angry tone of this but it's getting late and I really hate feeling like I'm wasting my time.

**Comment by bhousel** [comment]
So the answer to _why_ the source maps weren't getting updated.. A syntax error elsewhere caused the build to just fail silently, so the source map and the iD.js bundle were old.  

The server did say "Rebuilding" but never followed up with a "Rebuilt" message.  
The local server should do something on errors, not silently ignore them.

**Comment by tmcw** [comment]
I've fixed the sourcemap issue. How much time can you dedicate to this PR next week? Over the past 20 days, I've done much of the work on this branch, and related efforts - building the development environment, doing d3 upgrades en masse, painstakingly refactoring the build system. I had hoped that looping you in would help resolve the map-loading problem - maybe with the build process clearer, you can finish those changes?

**Comment by bhousel** [comment]
> I've fixed the sourcemap issue. How much time can you dedicate to this PR next week? Over the past 20 days, I've done much of the work on this branch, and related efforts - building the development environment, doing d3 upgrades en masse, painstakingly refactoring the build system. 

I just tried it.  

As a test, I introduced a syntax error, and the server printed
```
{ [SyntaxError: 'return' outside of function (594:4) in /Users/bryan/Projects/iD/modules/renderer/map.js]
  pos: 17582,
  loc: Position { line: 594, column: 4 },
  raisedAt: 17588,
  code: 'PARSE_ERROR',
  file: '/Users/bryan/Projects/iD/modules/renderer/map.js' }
```
This is good!

Then I fixed the error and nothing happened.. no message, no rebuild.   Is this expected?   This seems wrong to me.

**Comment by bhousel** [comment]
So the previous way of doing things was:
```
... edit code...
make
npm run test
python -m SimpleHTTPServer
```

and presumably the new way is:
```
... edit code...
npm run build
npm run test
npm start
```

If I am wrong about that, or if parts of the edit-compile-test loop are still not all the way done, (for example reliable source map generation), all I'm saying is lets take a pause and figure those things out first.

**Comment by tmcw** [comment]
Okay, fixed that in 	f402e6b - that was also a one-line change. The development_server.js is a 50-line utility that I wrote according to what I know of the [rollup API](https://github.com/rollup/rollup/wiki/JavaScript-API), and we need to treat it as a mungible thing that we can all contribute to - neither of these issues should have been a blocker, one was 'ignoring the second callback of a promise', and the second was fixing a mutex. Both were one-line fixes.

**Comment by bhousel** [comment]
> Okay, fixed that in f402e6b - that was also a one-line change.

Thank you, I'll see what I can do with this today...

**Comment by tmcw** [comment]
🎉  woot, nice work with the zoom refactoring!

**Comment by tmcw** [comment]
Making significant progress:

fixed:

* area drawing
* dragging points
* raw tag editor
* map size
* line display
* multi attributes

**Comment by bhousel** [comment]
> Making significant progress:

Nice, thanks!!  Yeah, when I read the v4 release notes I thought we would probably need to put those `merge` calls just about everywhere.  That's a pretty big change to the general update pattern, but immutable selections will be so much easier to reason about.

**Comment by tmcw** [comment]
* Fixed point adding. Line + way adding is still broken. Point adding took a long time to figure out but was not much of a code change.
* Fixed circularize tests. Other tests are failing, mostly because of the behavior of triggerEvent. Some parts of the codebase expect real events, with targets.. maybe we should use happen more and trigger less?

---

Taking a break to read, so if anyone else wants to take a shot at the remaining queue, go for it.

**Comment by bhousel** [comment]
I've been spending the past day trying to understand why the iD global is undefined when run through mocha-phantomjs (even though it works fine in a real browser).

d3 is bundled as a umd module, but they are able to attach to the global window root, so I'm not sure why our bundle won't do it (even with an explicit `window.iD = iD`).  I guess we switched it to iife because of #3356? 

```
    <script>
    console.log('d3 = ' + window.d3);
    console.log('iD = ' + window.iD);
    </script>
```
```
d3 = [object Object]
iD = undefined
ReferenceError: Can't find variable: iD
   in global code at file:///Users/bryan/Projects/iD/test/spec/spec_helpers.js:3
```

Anyway I would be really happy if I could find a way to get `npm run test` (and consequently travis) working again.

**Comment by tmcw** [comment]
Fiddled for a bit and I think 9834f66 will do it. The iD bundle has 'use strict' on it, and phantomjs's interpretation of strict in combination with its pretty quirky semi-browser is all bad news bears. https://travis-ci.org/openstreetmap/iD/builds/157471249 has tests running again.

**Comment by bhousel** [comment]
> Fiddled for a bit and I think 9834f66 will do it. The iD bundle has 'use strict' on it, and phantomjs's interpretation of strict in combination with its pretty quirky semi-browser is all bad news bears. https://travis-ci.org/openstreetmap/iD/builds/157471249 has tests running again.

Thanks!!  👍

**Comment by tmcw** [comment]
* Area & line drawing fixed! More small issues with the event dispatching refactor.

**Comment by tmcw** [comment]
2016-09-05 at 11 17 am

Almost there! Most of the rest of the test-thwacking is dealing with d3.customEvent, dispatch, and so on - help appreciated as always.

**Comment by tmcw** [comment]
Okay, @kepta @bhousel all tests pass. Only took many hours and a can-do attitude.

Shall we do some UI testing before merging this PR?

**Comment by bhousel** [comment]
> Shall we do some UI testing before merging this PR?

Unfortunately we've never had automated test coverage of anything under the old iD.ui namespace, so yes we'll need to do a lot of manual testing before we put up the "mission accomplished" banner.

For example, I notice that all the areas are being filled with black:

screenshot 2016-09-06 20 13 57

Hopefully this won't be too bad. Most of the stuff we uncover will be because of the changes in D3 general update pattern.

**Comment by bhousel** [comment]
Just a quick update:  This branch is actually getting pretty close to merging!   It is useable for editing and saving.  A few things that seem off:

- [ ] certain field elements (like combobox placeholders) aren't showing up on hover the first time (probably because of changes to D3 general update pattern and enter selection no longer flows into update)
- [ ] help screen missing some graphics
- [ ] walkthrough doesn't advance to next chapter

I think this is small stuff and I'll hopefully fix and merge to master within the next few days. 😄

**Comment by bhousel** [comment]
Merged!  🏁 🎉 
Thanks @tmcw for tolerating my crankiness and for keeping this moving!

The D3 upgrade was a massive amount of work, but this is a great step forward for iD and I'm glad we were able to pull it off!

**Pull request merged**
