### PR TITLE
Create antenna.json

### PR DESCRIPTION
**Pull request by obama**
see https://wiki.openstreetmap.org/wiki/Proposed_features/Telecommunications_tower

### CODE REVIEW

**Comment by bhousel** [comment]
Thanks @obama 👍

**Comment by 1ec5** [comment]
#2613 added a preset that could also be called “antenna” (and has been translated as such in at least one language). My understanding is that a standard guyed radio antenna would be tagged `man_made=mast`, as supported by [openstreetmap-carto](https://github.com/gravitystorm/openstreetmap-carto/blob/94fe461654bd1424e775a23207eed6ffb4aa2203/amenity-points.mss#L371-L392). Back when I added the preset, that would’ve been consistent with [this wiki page](https://wiki.openstreetmap.org/wiki/Special:PermanentLink/1181155#First_question:_Is_it_a_mast_or_a_tower.3F), although the page has since been pared back; a separate page now describes the much rarer [`man_made=antenna`](https://wiki.openstreetmap.org/wiki/Tag:man_made%3Dantenna) tag and equivocates as to which tag should be used. So now I’m confused, and I can’t imagine the situation would be any better for the user. 😕

**Comment by bhousel** [comment]
> My understanding is that a standard guyed radio antenna would be tagged man_made=mast, as supported by openstreetmap-carto. Back when I added the preset, that would’ve been consistent with this wiki page, although the page has since been pared back; a separate page now describes the much rarer man_made=antenna tag and equivocates as to which tag should be used. So now I’m confused, and I can’t imagine the situation would be any better for the user.

Hey @1ec5 - yes, this situation is pretty confusing.   Also remember in #3630 that we changed them from "Radio Mast" to simply "Mast".

I was assuming that Mast/Tower is the structure, and Antenna is the thing that attaches to it?  Many people will only tag the Mast/Tower, as its the most visible thing. 

@obama Can you discuss more your motivation for wanting this preset?

For reference:
https://wiki.openstreetmap.org/wiki/Tag:man_made%3Dantenna
https://wiki.openstreetmap.org/wiki/Tag:man_made%3Dtower
https://wiki.openstreetmap.org/wiki/Tag:man_made%3Dmast

**Comment by obama** [comment]
i thought it was OK to add, but if it confuses people than leave it out.

**Pull request merged**
