### PR TITLE
Add ability to revert entity back to base version

### PR DESCRIPTION
**Pull request by bhousel**
see [#537](https://github.com/openstreetmap/iD/issues/537#issuecomment-96315941)

I did not create an operation for it, but may be useful later.  For now I just want it for conflict resolution.

This seems ok to me..
@jfirebaugh @tmcw see any issues?

### CODE REVIEW

**Comment by jfirebaugh** [comment]
What happens in the following scenarios:

* A new node is added to an existing way, and then the node is reverted?
* A new node is added to an existing way, and then the way is reverted?
* A new way is created and added to an existing relation, and then the way is reverted?
* An existing node that's a member of way A is dragged onto way B, connecting them. Then:
  * The node move is reverted
  * Or, one of the ways is reverted

You can see I'm getting at scenarios where multiple entities are involved, but only one of them is reverted -- you can probably think of other scenarios in this vein.

**Comment by bhousel** [comment]
I think calling [`_updateCalculated()`](https://github.com/openstreetmap/iD/commit/6b18066dd695c5b60f998204bf26b0a5aa55edc5#diff-af670b2e1a04df9f14bc9375d65a426fR259) with the base version of the entity (which will be `undefined` if it's a new entity) handles all of these cases.

I did write some tests for a few of these, but I do want to make sure all the scenarios are handled. 
(most of these are really similar)

> A new node is added to an existing way, and then the node is reverted?

New node gets removed, and existing way's nodelist is updated to not include it.

> A new node is added to an existing way, and then the way is reverted?

New node stays (it turns into a point), and existing way's nodelist is updated to not include it.

> A new way is created and added to an existing relation, and then the way is reverted?

New way gets removed and existing relation's memberlist is updated to not include it.

> An existing node that's a member of way A is dragged onto way B, connecting them. Then:
> The node move is reverted
> Or, one of the ways is reverted

I think in all cases `_updateCalculated()` will do the right thing, but just for our sanity I will expand the tests.

**Comment by jfirebaugh** [comment]
` _updateCalculated()` handles bookkeeping internal to `Graph`, but it doesn't update a containing way's `nodes` or relation's `members`.

**Comment by bhousel** [comment]
Good point...   I think `Graph#revert` is ok but I definitely need to fix `iD.actions.Revert`

**Comment by bhousel** [comment]
7adb0dd now updates parent way's `nodes` / parent relation's `members`, for new entities.

We should continue discussion of this on #537 before deciding if it's solid enough for an operation or shortcut key.

I'm pretty sure it is safe for the purpose that I am using it for in [save.js](https://github.com/openstreetmap/iD/commit/a565b72f7da030bbe5ca798a38f1926ec626223b) - to exclude certain local edits from the changeset where the user chooses "keep theirs" in conflict resolution.

**Pull request merged**
