### PR TITLE
rename be-x-old to be-tarask as own language subtag that also used in…

### PR DESCRIPTION
**Pull request by tbicr**
… wikipedia now

http://www.iana.org/assignments/language-subtag-registry/language-subtag-registry

Type: variant
Subtag: tarask
Description: Belarusian in Taraskievica orthography
Added: 2007-04-27
Prefix: be
Comments: The subtag represents Branislau Taraskievic's Belarusian
  orthography as published in "Bielaruski klasycny pravapis" by Juras
  Buslakou, Vincuk Viacorka, Zmicier Sanko, and Zmicier Sauka (Vilnia-
  Miensk 2005).

### CODE REVIEW

**Comment by pnorman** [comment]
I think this file is a generated one, but can't find where it's coming from.

**Comment by tbicr** [comment]
Maybe this https://github.com/openstreetmap/iD/blob/master/Makefile#L127?

**Comment by tyrasd** [comment]
Yes, the relevant repository is [osmlab/wmf-sitematrix](https://github.com/osmlab/wmf-sitematrix), which in turn grabs the data from https://meta.wikimedia.org/wiki/Special:SiteMatrix ([json](https://meta.wikimedia.org/w/api.php?action=sitematrix&uselang=en&format=json)), which still has `be-x-old` as the language *code*, while linking to `https://be-tarask.wikipedia.org`. Strange. Not sure what has to be done to update the code on meta.wikimedia…

**Comment by 1ec5** [comment]
> Not sure what has to be done to update the code on meta.wikimedia…

This is being tracked upstream in [T132008](https://phabricator.wikimedia.org/T132008) at Wikimedia’s Phabricator.

**Comment by tbicr** [comment]
@1ec5 , there are more old ticket https://phabricator.wikimedia.org/T111876

**Comment by bhousel** [comment]
Closing, as this is an upstream issue

**Pull request closed without merging**
