### PR TITLE
Add Using GitHub and Git

### PR DESCRIPTION
**Pull request by manfredbrandl**
See Issue #4324 (comment).

### CODE REVIEW

**Comment by bhousel** [comment]
Very well written, and I like how it links out to other great git resources for beginners, thanks @manfredbrandl !  👍

**Comment by mmd-osm** [comment]
If I'm not completely mistaken, adding simple stuff like new presets, or fixing some documentation could be entirely done from the Github in your browser: this includes forking, creating a new branch, creating or updating some files, creating a pull request, etc.

One example might be this PR: https://github.com/openstreetmap/iD/pull/5233/files

**Comment by manfredbrandl** [comment]
@mmd-osm Can you write a minimal howto or a short step-by-step description of a GitHub-only PR?

**Comment by mmd-osm** [comment]
Sure... a very high level summary would be as follows:

(Creating Github account as before)

1. Navigate to https://github.com/openstreetmap/iD
2. Click on "Fork"
3. Click on "Branch: master"
4. Enter the name of a new branch, create new branch
5. Navigate to the file you want to edit
6. Click on "Edit this file"
7. Apply your changes to your file
Alternatively, you could also "Create a new file"
8. When finished, enter a commit text and description, Commit directly to the _(my-new-branch)_ branch. 
9. Click on "Commit changes"
10. Navigate back to your "id" project - https://github.com/{{user}}/iD
11. Follow https://help.github.com/articles/about-pull-requests/ to create a new pull request for your change

Tested on https://github.com/mmd-osm/iD/tree/my-new-branch

**Comment by manfredbrandl** [comment]
@mmd-osm Can you please look at CONTRIBUTING.md if improvents are still possible?

**Comment by mmd-osm** [comment]
LGTM!

One thing I'm not sure of, is if we should promote https://help.github.com/articles/editing-files-in-another-user-s-repository/ even more, as it would be easier for typical users (I only remembered that this is possible, after finishing the step-by-step list above).

**Pull request merged**
