### PR TITLE
add validation for connecting highway with extension

### PR DESCRIPTION
**Pull request by gaoxm**
but avoid connect when the edge goes in parallel to the other road.
also added tests for the validation.

### CODE REVIEW

**Comment by SilentSpike** [comment]
I believe it should be re-worded to something along the lines of "Almost Junction" as commonly found in QA tools. Reason being that `Potential connection with extension` doesn't sound like an error, but rather a suggestion.

Same for the tooltip, it seems to be suggesting a connection should be made when really the user should investigate more closely and either mark with `noexit` (if there truly is no connection) or map whatever missing connections there are.

**Comment by gaoxm** [comment]
> I believe it should be re-worded to something along the lines of "Almost Junction" as commonly found in QA tools. Reason being that `Potential connection with extension` doesn't sound like an error, but rather a suggestion.
> 
> Same for the tooltip, it seems to be suggesting a connection should be made when really the user should investigate more closely and either mark with `noexit` (if there truly is no connection) or map whatever missing connections there are.

Makes sense. @bhousel @quincylvania would you guys also suggest a better name/message for this? JOSM calls this "way ends near another highway": https://wiki.openstreetmap.org/wiki/JOSM/Validator

**Comment by gaoxm** [comment]
@bhousel @quincylvania ping - do you think I should update the name and message for the validation check before merging this PR?

**Comment by bhousel** [comment]
Hey @gaoxm  - Yes the KeepRight version of this check looks like:
```
          title: 'Almost junction'
          description: 'This node is very close but not connected to way {var1}.'
```

I agree with @SilentSpike , that i like the name "Almost Junction" a bit better.

**Comment by gaoxm** [comment]
@bhousel @quincylvania validation name and messages are all updated.

**Pull request merged**
