### PR TITLE
Update highway colors to match openstreetmap-carto

### PR DESCRIPTION
**Pull request by bhousel**
Changes the highway colors to more closely match the openstreetmap-carto project.
see #2764 

Here's how it looks currently:
screenshot 2015-10-21 01 24 21

A few "action shots":
low zoom:
screenshot 2015-10-21 01 31 54

normal zoom:
screenshot 2015-10-21 01 32 08

something for everyone:
screenshot 2015-10-21 01 35 51

TODO:
- [X] preset icons

/cc @samanpwbb thoughts?

### CODE REVIEW

**Comment by samanpwbb** [comment]
Makes sense, looks good 👍

**Comment by bhousel** [comment]
Just a quick update: going all svg/css on the icons looks gorgeous and makes everything really easy to style.  I'm really glad I stuck with this. I'm going to do a bit more cross-browser testing and merge this today.

Click below to view at full resolution..

Before | After
---- | ----
screenshot 2015-11-04 12 11 25 | screenshot 2015-11-04 12 10 50
---- | ----
screenshot 2015-11-04 12 12 16 | screenshot 2015-11-04 12 12 45

**Comment by samanpwbb** [comment]
Ohhh looks awesome!

**Comment by nebulon42** [comment]
SVG: Big improvement!

**Comment by bhousel** [comment]
Looks nice in IE10,11 too.  Merging!

**Comment by bhousel** [comment]
Once iD 1.8 lands, anyone who depends on the sprite to be a certain way will need to make changes, either in the `svg/iD-sprite.src.svg` file itself, or in the `svg/iD-sprite.json` mapping file.

e.g. @paulmach, I included an "operation-smooth" icon like the one you use for Strava slide.  You can edit `iD-sprite.json` to rename it to "operation-slide", then run `make` and things _should_ just work.

```
diff --git a/svg/iD-sprite.json b/svg/iD-sprite.json
index ec3eec1..d57b55c 100644
--- a/svg/iD-sprite.json
+++ b/svg/iD-sprite.json
@@ -259,7 +259,7 @@
     "operation-orthogonalize":  { "viewBox": "360 380 20 20" },
     "operation-rotate":         { "viewBox": "380 380 20 20" },
     "operation-simplify":       { "viewBox": "400 380 20 20" },
-    "operation-smooth":         { "viewBox": "420 380 20 20" },
+    "operation-smooth":         { "viewBox": "420 380 20 20", "id": "operation-slide" },
     "operation-continue":       { "viewBox": "440 380 20 20" },
```

**Comment by paulmach** [comment]
Thanks @bhousel   Updated our fork to 1.8.0 http://strava.github.com/iD

**Comment by bhousel** [comment]
@paulmach Awesome, looks good!

**Pull request merged**
